/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.reviews

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.MariaTypes
import dev.typr.foundations.Tuple.Tuple18
import dev.typr.foundations.data.Json
import dev.typr.foundations.data.Uint1
import dev.typr.foundations.data.Uint4
import dev.typr.foundations.scala.DbTypeOps
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import dev.typr.foundations.scala.ScalaDbTypes
import java.time.LocalDateTime
import testdb.customers.CustomersId
import testdb.customtypes.Defaulted
import testdb.order_items.OrderItemsId
import testdb.products.ProductsId

/** Table: reviews
 * Primary key: review_id
 */
case class ReviewsRow(
  /** 
   * AUTO_INCREMENT
   */
  @JsonProperty("review_id") reviewId: ReviewsId,
  /** 
   * Points to [[testdb.products.ProductsRow.productId]]
   */
  @JsonProperty("product_id") productId: ProductsId,
  /** 
   * Points to [[testdb.customers.CustomersRow.customerId]]
   */
  @JsonProperty("customer_id") customerId: CustomersId,
  /** 
   * Default: NULL
   * Points to [[testdb.order_items.OrderItemsRow.itemId]]
   */
  @JsonProperty("order_item_id") orderItemId: Option[OrderItemsId],
  /**  */
  rating: Uint1,
  /** 
   * Default: NULL
   */
  title: Option[String],
  /** 
   * Default: NULL
   */
  content: Option[String],
  /** 
   * Default: NULL
   */
  pros: Option[Json],
  /** 
   * Default: NULL
   */
  cons: Option[Json],
  /** Array of image URLs
   * Default: NULL
   */
  images: Option[Json],
  /** 
   * Default: 0
   */
  @JsonProperty("is_verified_purchase") isVerifiedPurchase: Boolean,
  /** 
   * Default: 0
   */
  @JsonProperty("is_approved") isApproved: Boolean,
  /** 
   * Default: 0
   */
  @JsonProperty("helpful_votes") helpfulVotes: Uint4,
  /** 
   * Default: 0
   */
  @JsonProperty("unhelpful_votes") unhelpfulVotes: Uint4,
  /** 
   * Default: NULL
   */
  @JsonProperty("admin_response") adminResponse: Option[String],
  /** 
   * Default: NULL
   */
  @JsonProperty("responded_at") respondedAt: Option[LocalDateTime],
  /** 
   * Default: current_timestamp(6)
   */
  @JsonProperty("created_at") createdAt: LocalDateTime,
  /** 
   * Default: current_timestamp(6)
   */
  @JsonProperty("updated_at") updatedAt: LocalDateTime
) extends Tuple18[ReviewsId, ProductsId, CustomersId, Option[OrderItemsId], Uint1, Option[String], Option[String], Option[Json], Option[Json], Option[Json], Boolean, Boolean, Uint4, Uint4, Option[String], Option[LocalDateTime], LocalDateTime, LocalDateTime] {
  def id: ReviewsId = reviewId

  def toUnsavedRow(
    orderItemId: Defaulted[Option[OrderItemsId]] = Defaulted.Provided(this.orderItemId),
    title: Defaulted[Option[String]] = Defaulted.Provided(this.title),
    content: Defaulted[Option[String]] = Defaulted.Provided(this.content),
    pros: Defaulted[Option[Json]] = Defaulted.Provided(this.pros),
    cons: Defaulted[Option[Json]] = Defaulted.Provided(this.cons),
    images: Defaulted[Option[Json]] = Defaulted.Provided(this.images),
    isVerifiedPurchase: Defaulted[Boolean] = Defaulted.Provided(this.isVerifiedPurchase),
    isApproved: Defaulted[Boolean] = Defaulted.Provided(this.isApproved),
    helpfulVotes: Defaulted[Uint4] = Defaulted.Provided(this.helpfulVotes),
    unhelpfulVotes: Defaulted[Uint4] = Defaulted.Provided(this.unhelpfulVotes),
    adminResponse: Defaulted[Option[String]] = Defaulted.Provided(this.adminResponse),
    respondedAt: Defaulted[Option[LocalDateTime]] = Defaulted.Provided(this.respondedAt),
    createdAt: Defaulted[LocalDateTime] = Defaulted.Provided(this.createdAt),
    updatedAt: Defaulted[LocalDateTime] = Defaulted.Provided(this.updatedAt)
  ): ReviewsRowUnsaved = {
    new ReviewsRowUnsaved(
      productId,
      customerId,
      rating,
      orderItemId,
      title,
      content,
      pros,
      cons,
      images,
      isVerifiedPurchase,
      isApproved,
      helpfulVotes,
      unhelpfulVotes,
      adminResponse,
      respondedAt,
      createdAt,
      updatedAt
    )
  }

  override def `_1`: ReviewsId = reviewId

  override def `_2`: ProductsId = productId

  override def `_3`: CustomersId = customerId

  override def `_4`: Option[OrderItemsId] = orderItemId

  override def `_5`: Uint1 = rating

  override def `_6`: Option[String] = title

  override def `_7`: Option[String] = content

  override def `_8`: Option[Json] = pros

  override def `_9`: Option[Json] = cons

  override def `_10`: Option[Json] = images

  override def `_11`: Boolean = isVerifiedPurchase

  override def `_12`: Boolean = isApproved

  override def `_13`: Uint4 = helpfulVotes

  override def `_14`: Uint4 = unhelpfulVotes

  override def `_15`: Option[String] = adminResponse

  override def `_16`: Option[LocalDateTime] = respondedAt

  override def `_17`: LocalDateTime = createdAt

  override def `_18`: LocalDateTime = updatedAt
}

object ReviewsRow {
  val `_rowParser`: RowParser[ReviewsRow] = RowParsers.of(ReviewsId.dbType, ProductsId.dbType, CustomersId.dbType, OrderItemsId.dbType.nullable, MariaTypes.tinyintUnsigned, MariaTypes.varchar.nullable, MariaTypes.text.nullable, MariaTypes.json.nullable, MariaTypes.json.nullable, MariaTypes.json.nullable, ScalaDbTypes.MariaTypes.bool, ScalaDbTypes.MariaTypes.bool, MariaTypes.intUnsigned, MariaTypes.intUnsigned, MariaTypes.text.nullable, MariaTypes.datetime.nullable, MariaTypes.datetime, MariaTypes.datetime)(ReviewsRow.apply)(row => Array[Any](row.reviewId, row.productId, row.customerId, row.orderItemId, row.rating, row.title, row.content, row.pros, row.cons, row.images, row.isVerifiedPurchase, row.isApproved, row.helpfulVotes, row.unhelpfulVotes, row.adminResponse, row.respondedAt, row.createdAt, row.updatedAt))
}