/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.customer

import com.fasterxml.jackson.annotation.JsonValue
import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.scaladsl.Bijection
import typo.scaladsl.ScalaDbTypes

/** Type for the primary key of table `sales.customer` */
case class CustomerId(@JsonValue value: Int) extends scala.AnyVal

object CustomerId {
  given bijection: Bijection[CustomerId, Int] = Bijection.apply[CustomerId, Int](_.value)(CustomerId.apply)

  given pgType: PgType[CustomerId] = ScalaDbTypes.PgTypes.int4.bimap(CustomerId.apply, _.value)

  given pgTypeArray: PgType[Array[CustomerId]] = PgTypes.int4ArrayUnboxed.bimap(xs => xs.map(CustomerId.apply), xs => xs.map(_.value))
}