/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb;

import java.math.BigDecimal;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Optional;
import java.util.Random;
import testdb.check_constraint_test.CheckConstraintTestId;
import testdb.check_constraint_test.CheckConstraintTestRepoImpl;
import testdb.check_constraint_test.CheckConstraintTestRow;
import testdb.customers.CustomersId;
import testdb.customers.CustomersRepoImpl;
import testdb.customers.CustomersRow;
import testdb.customers.CustomersRowUnsaved;
import testdb.customtypes.Defaulted;
import testdb.db2test.Db2testId;
import testdb.db2test.Db2testRepoImpl;
import testdb.db2test.Db2testRow;
import testdb.db2test_identity_always.Db2testIdentityAlwaysRepoImpl;
import testdb.db2test_identity_always.Db2testIdentityAlwaysRow;
import testdb.db2test_identity_always.Db2testIdentityAlwaysRowUnsaved;
import testdb.db2test_identity_default.Db2testIdentityDefaultId;
import testdb.db2test_identity_default.Db2testIdentityDefaultRepoImpl;
import testdb.db2test_identity_default.Db2testIdentityDefaultRow;
import testdb.db2test_identity_default.Db2testIdentityDefaultRowUnsaved;
import testdb.db2test_unique.Db2testUniqueRepoImpl;
import testdb.db2test_unique.Db2testUniqueRow;
import testdb.db2test_unique.Db2testUniqueRowUnsaved;
import testdb.db2testnull.Db2testnullRepoImpl;
import testdb.db2testnull.Db2testnullRow;
import testdb.distinct_type_test.DistinctTypeTestRepoImpl;
import testdb.distinct_type_test.DistinctTypeTestRow;
import testdb.distinct_type_test.DistinctTypeTestRowUnsaved;
import testdb.identity_params_test.IdentityParamsTestRepoImpl;
import testdb.identity_params_test.IdentityParamsTestRow;
import testdb.identity_params_test.IdentityParamsTestRowUnsaved;
import testdb.nullability_test.NullabilityTestRepoImpl;
import testdb.nullability_test.NullabilityTestRow;
import testdb.nullability_test.NullabilityTestRowUnsaved;
import testdb.order_items.OrderItemsRepoImpl;
import testdb.order_items.OrderItemsRow;
import testdb.orders.OrdersId;
import testdb.orders.OrdersRepoImpl;
import testdb.orders.OrdersRow;
import testdb.orders.OrdersRowUnsaved;

/** Methods to generate random data for `Ident(TestInsert)` */
public record TestInsert(Random random) {
  public TestInsert withRandom(Random random) {
    return new TestInsert(random);
  }
  ;

  public CheckConstraintTestRow CheckConstraintTest(
      Integer age,
      String status,
      CheckConstraintTestId id,
      Optional<BigDecimal> price,
      Connection c) {
    return (new CheckConstraintTestRepoImpl())
        .insert(new CheckConstraintTestRow(id, age, status, price), c);
  }
  ;

  public CustomersRow Customers(
      String name,
      String email,
      Defaulted<CustomersId> customerId,
      Defaulted<Optional<LocalDateTime>> createdAt,
      Connection c) {
    return (new CustomersRepoImpl())
        .insert(new CustomersRowUnsaved(name, email, customerId, createdAt), c);
  }
  ;

  public Db2testRow Db2test(
      byte[] binaryCol,
      byte[] varbinaryCol,
      byte[] blobCol,
      LocalDate dateCol,
      LocalTime timeCol,
      LocalDateTime timestampCol,
      LocalDateTime timestamp6Col,
      LocalDateTime timestamp12Col,
      Short smallintCol,
      Db2testId intCol,
      Long bigintCol,
      BigDecimal decimalCol,
      BigDecimal numericCol,
      BigDecimal decfloat16Col,
      BigDecimal decfloat34Col,
      Float realCol,
      Double doubleCol,
      Boolean boolCol,
      String charCol,
      String varcharCol,
      String clobCol,
      String graphicCol,
      String vargraphicCol,
      String xmlCol,
      Connection c) {
    return (new Db2testRepoImpl())
        .insert(
            new Db2testRow(
                smallintCol,
                intCol,
                bigintCol,
                decimalCol,
                numericCol,
                decfloat16Col,
                decfloat34Col,
                realCol,
                doubleCol,
                boolCol,
                charCol,
                varcharCol,
                clobCol,
                graphicCol,
                vargraphicCol,
                binaryCol,
                varbinaryCol,
                blobCol,
                dateCol,
                timeCol,
                timestampCol,
                timestamp6Col,
                timestamp12Col,
                xmlCol),
            c);
  }
  ;

  public Db2testIdentityAlwaysRow Db2testIdentityAlways(String name, Connection c) {
    return (new Db2testIdentityAlwaysRepoImpl())
        .insert(new Db2testIdentityAlwaysRowUnsaved(name), c);
  }
  ;

  public Db2testIdentityDefaultRow Db2testIdentityDefault(
      String name, Defaulted<Db2testIdentityDefaultId> id, Connection c) {
    return (new Db2testIdentityDefaultRepoImpl())
        .insert(new Db2testIdentityDefaultRowUnsaved(name, id), c);
  }
  ;

  public Db2testUniqueRow Db2testUnique(String email, String code, String category, Connection c) {
    return (new Db2testUniqueRepoImpl())
        .insert(new Db2testUniqueRowUnsaved(email, code, category), c);
  }
  ;

  public Db2testnullRow Db2testnull(
      Optional<Short> smallintCol,
      Optional<Integer> intCol,
      Optional<Long> bigintCol,
      Optional<BigDecimal> decimalCol,
      Optional<BigDecimal> numericCol,
      Optional<BigDecimal> decfloat16Col,
      Optional<BigDecimal> decfloat34Col,
      Optional<Float> realCol,
      Optional<Double> doubleCol,
      Optional<Boolean> boolCol,
      Optional<String> charCol,
      Optional<String> varcharCol,
      Optional<String> clobCol,
      Optional<String> graphicCol,
      Optional<String> vargraphicCol,
      Optional<byte[]> binaryCol,
      Optional<byte[]> varbinaryCol,
      Optional<byte[]> blobCol,
      Optional<LocalDate> dateCol,
      Optional<LocalTime> timeCol,
      Optional<LocalDateTime> timestampCol,
      Optional<LocalDateTime> timestamp6Col,
      Optional<LocalDateTime> timestamp12Col,
      Optional</* XML */ String> xmlCol,
      Connection c) {
    return (new Db2testnullRepoImpl())
        .insert(
            new Db2testnullRow(
                smallintCol,
                intCol,
                bigintCol,
                decimalCol,
                numericCol,
                decfloat16Col,
                decfloat34Col,
                realCol,
                doubleCol,
                boolCol,
                charCol,
                varcharCol,
                clobCol,
                graphicCol,
                vargraphicCol,
                binaryCol,
                varbinaryCol,
                blobCol,
                dateCol,
                timeCol,
                timestampCol,
                timestamp6Col,
                timestamp12Col,
                xmlCol),
            c);
  }
  ;

  public DistinctTypeTestRow DistinctTypeTest(
      EmailAddress email, Optional<MoneyAmount> balance, Connection c) {
    return (new DistinctTypeTestRepoImpl())
        .insert(new DistinctTypeTestRowUnsaved(email, balance), c);
  }
  ;

  public IdentityParamsTestRow IdentityParamsTest(String name, Connection c) {
    return (new IdentityParamsTestRepoImpl()).insert(new IdentityParamsTestRowUnsaved(name), c);
  }
  ;

  public NullabilityTestRow NullabilityTest(
      Integer id,
      String requiredCol,
      Optional<String> optionalCol,
      Defaulted<Optional<String>> defaultedCol,
      Connection c) {
    return (new NullabilityTestRepoImpl())
        .insert(new NullabilityTestRowUnsaved(id, requiredCol, optionalCol, defaultedCol), c);
  }
  ;

  public OrderItemsRow OrderItems(
      OrdersId orderId,
      Integer itemNumber,
      String productName,
      Integer quantity,
      BigDecimal unitPrice,
      Connection c) {
    return (new OrderItemsRepoImpl())
        .insert(new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice), c);
  }
  ;

  public OrdersRow Orders(
      CustomersId customerId,
      Optional<BigDecimal> totalAmount,
      Defaulted<LocalDate> orderDate,
      Defaulted<Optional<String>> status,
      Connection c) {
    return (new OrdersRepoImpl())
        .insert(new OrdersRowUnsaved(customerId, totalAmount, orderDate, status), c);
  }
  ;
}
