/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.category;

import java.sql.Connection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;

public interface CategoryRepo {
  DeleteBuilder<CategoryFields, CategoryRow> delete();

  Boolean deleteById(
    CategoryId id,
    Connection c
  );

  Integer deleteByIds(
    CategoryId[] ids,
    Connection c
  );

  CategoryRow insert(
    CategoryRow unsaved,
    Connection c
  );

  CategoryRow insert(
    CategoryRowUnsaved unsaved,
    Connection c
  );

  Long insertStreaming(
    Iterator<CategoryRow> unsaved,
    Integer batchSize,
    Connection c
  );

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  Long insertUnsavedStreaming(
    Iterator<CategoryRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  );

  SelectBuilder<CategoryFields, CategoryRow> select();

  List<CategoryRow> selectAll(Connection c);

  Optional<CategoryRow> selectById(
    CategoryId id,
    Connection c
  );

  List<CategoryRow> selectByIds(
    CategoryId[] ids,
    Connection c
  );

  Map<CategoryId, CategoryRow> selectByIdsTracked(
    CategoryId[] ids,
    Connection c
  );

  UpdateBuilder<CategoryFields, CategoryRow> update();

  Boolean update(
    CategoryRow row,
    Connection c
  );

  CategoryRow upsert(
    CategoryRow unsaved,
    Connection c
  );

  List<CategoryRow> upsertBatch(
    Iterator<CategoryRow> unsaved,
    Connection c
  );

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  Integer upsertStreaming(
    Iterator<CategoryRow> unsaved,
    Integer batchSize,
    Connection c
  );
}