/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.category;

import frontpage.customtypes.Defaulted;
import frontpage.customtypes.Defaulted.UseDefault;
import typo.runtime.PgText;
import typo.runtime.PgTypes;

/** This class corresponds to a row in table `frontpage.category` which has not been persisted yet */
public record CategoryRowUnsaved(
  String name,
  /** Default: gen_random_uuid() */
  Defaulted<CategoryId> id
) {
  public CategoryRowUnsaved(String name) {
    this(name, new UseDefault<>());
  };

  public CategoryRowUnsaved withName(String name) {
    return new CategoryRowUnsaved(name, id);
  };

  /** Default: gen_random_uuid() */
  public CategoryRowUnsaved withId(Defaulted<CategoryId> id) {
    return new CategoryRowUnsaved(name, id);
  };

  static public PgText<CategoryRowUnsaved> pgText =
    PgText.instance((row, sb) -> {
      PgTypes.text.pgText().unsafeEncode(row.name, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(CategoryId.pgType.pgText()).unsafeEncode(row.id, sb);
    });

  public CategoryRow toRow(java.util.function.Supplier<CategoryId> idDefault) {
    return new CategoryRow(id.getOrElse(idDefault), name);
  };
}