/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.category;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import typo.dsl.DeleteBuilder;
import typo.dsl.DeleteBuilder.DeleteBuilderMock;
import typo.dsl.DeleteParams;
import typo.dsl.SelectBuilder;
import typo.dsl.SelectBuilderMock;
import typo.dsl.SelectParams;
import typo.dsl.UpdateBuilder;
import typo.dsl.UpdateBuilder.UpdateBuilderMock;
import typo.dsl.UpdateParams;
import static typo.runtime.internal.stringInterpolator.str;

public record CategoryRepoMock(
  java.util.function.Function<CategoryRowUnsaved, CategoryRow> toRow,
  HashMap<CategoryId, CategoryRow> map
) implements CategoryRepo {
  public CategoryRepoMock(java.util.function.Function<CategoryRowUnsaved, CategoryRow> toRow) {
    this(toRow, new HashMap<CategoryId, CategoryRow>());
  };

  public CategoryRepoMock withToRow(java.util.function.Function<CategoryRowUnsaved, CategoryRow> toRow) {
    return new CategoryRepoMock(toRow, map);
  };

  public CategoryRepoMock withMap(HashMap<CategoryId, CategoryRow> map) {
    return new CategoryRepoMock(toRow, map);
  };

  public DeleteBuilder<CategoryFields, CategoryRow> delete() {
    return new DeleteBuilderMock<>(CategoryFields.structure(), () -> new ArrayList<>(map.values()), DeleteParams.empty(), row -> row.id(), id -> map.remove(id));
  };

  public Boolean deleteById(
    CategoryId id,
    Connection c
  ) {
    return Optional.ofNullable(map.remove(id)).isPresent();
  };

  public Integer deleteByIds(
    CategoryId[] ids,
    Connection c
  ) {
    var count = 0;
      for (var id : ids) { if (Optional.ofNullable(map.remove(id)).isPresent()) {
        count = count + 1;
      } };
    return count;
  };

  public CategoryRow insert(
    CategoryRow unsaved,
    Connection c
  ) {
    if (map.containsKey(unsaved.id())) {
        throw new RuntimeException(str("id $unsaved.id() already exists"));
      };
      map.put(unsaved.id(), unsaved);
    return unsaved;
  };

  public CategoryRow insert(
    CategoryRowUnsaved unsaved,
    Connection c
  ) {
    return insert(toRow.apply(unsaved), c);
  };

  public Long insertStreaming(
    Iterator<CategoryRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        count = count + 1L;
      };
    return count;
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<CategoryRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var unsavedRow = unsaved.next();
        var row = toRow.apply(unsavedRow);
        map.put(row.id(), row);
        count = count + 1L;
      };
    return count;
  };

  public SelectBuilder<CategoryFields, CategoryRow> select() {
    return new SelectBuilderMock<>(CategoryFields.structure(), () -> new ArrayList<>(map.values()), SelectParams.empty());
  };

  public List<CategoryRow> selectAll(Connection c) {
    return new ArrayList<>(map.values());
  };

  public Optional<CategoryRow> selectById(
    CategoryId id,
    Connection c
  ) {
    return Optional.ofNullable(map.get(id));
  };

  public List<CategoryRow> selectByIds(
    CategoryId[] ids,
    Connection c
  ) {
    var result = new ArrayList<CategoryRow>();
      for (var id : ids) { var opt = Optional.ofNullable(map.get(id));
      if (opt.isPresent()) result.add(opt.get()); };
    return result;
  };

  public Map<CategoryId, CategoryRow> selectByIdsTracked(
    CategoryId[] ids,
    Connection c
  ) {
    return selectByIds(ids, c).stream().collect(Collectors.toMap((frontpage.frontpage.category.CategoryRow row) -> row.id(), Function.identity()));
  };

  public UpdateBuilder<CategoryFields, CategoryRow> update() {
    return new UpdateBuilderMock<>(CategoryFields.structure(), () -> new ArrayList<>(map.values()), UpdateParams.empty(), row -> row);
  };

  public Boolean update(
    CategoryRow row,
    Connection c
  ) {
    var shouldUpdate = Optional.ofNullable(map.get(row.id())).filter(oldRow -> !oldRow.equals(row)).isPresent();
      if (shouldUpdate) {
        map.put(row.id(), row);
      };
    return shouldUpdate;
  };

  public CategoryRow upsert(
    CategoryRow unsaved,
    Connection c
  ) {
    map.put(unsaved.id(), unsaved);
    return unsaved;
  };

  public List<CategoryRow> upsertBatch(
    Iterator<CategoryRow> unsaved,
    Connection c
  ) {
    var result = new ArrayList<CategoryRow>();
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        result.add(row);
      };
    return result;
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<CategoryRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        count = count + 1;
      };
    return count;
  };
}