/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_stats

import dev.typr.foundations.scala.SelectBuilder
import java.sql.Connection

trait CustomerStatsMVRepo {
  def select: SelectBuilder[CustomerStatsMVFields, CustomerStatsMVRow]

  def selectAll(using c: Connection): List[CustomerStatsMVRow]
}