/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_stats

import dev.typr.foundations.Db2Types
import dev.typr.foundations.RowParser
import dev.typr.foundations.dsl.FieldsExpr0
import dev.typr.foundations.dsl.Path
import dev.typr.foundations.dsl.SqlExpr.FieldLike
import dev.typr.foundations.scala.RelationStructure
import dev.typr.foundations.scala.ScalaDbTypes
import dev.typr.foundations.scala.SqlExpr.Field

trait CustomerStatsMVFields extends FieldsExpr0[CustomerStatsMVRow] {
  def customerId: Field[Int, CustomerStatsMVRow]

  def customerName: Field[String, CustomerStatsMVRow]

  def totalOrders: Field[Int, CustomerStatsMVRow]

  def totalRevenue: Field[BigDecimal, CustomerStatsMVRow]

  override def columns: java.util.List[FieldLike[?, CustomerStatsMVRow]]

  override def rowParser: RowParser[CustomerStatsMVRow] = CustomerStatsMVRow._rowParser.underlying
}

object CustomerStatsMVFields {
  case class Impl(val `_path`: java.util.List[Path]) extends CustomerStatsMVFields with RelationStructure[CustomerStatsMVFields, CustomerStatsMVRow] {

    override def customerId: Field[Int, CustomerStatsMVRow] = {
      new Field[Int, CustomerStatsMVRow](
        _path,
        "CUSTOMER_ID",
        _.customerId,
        None,
        None,
        (row, value) => row.copy(customerId = value),
        ScalaDbTypes.Db2Types.integer
      )
    }

    override def customerName: Field[String, CustomerStatsMVRow] = {
      new Field[String, CustomerStatsMVRow](
        _path,
        "CUSTOMER_NAME",
        _.customerName,
        None,
        None,
        (row, value) => row.copy(customerName = value),
        Db2Types.varchar
      )
    }

    override def totalOrders: Field[Int, CustomerStatsMVRow] = {
      new Field[Int, CustomerStatsMVRow](
        _path,
        "TOTAL_ORDERS",
        _.totalOrders,
        None,
        None,
        (row, value) => row.copy(totalOrders = value),
        ScalaDbTypes.Db2Types.integer
      )
    }

    override def totalRevenue: Field[BigDecimal, CustomerStatsMVRow] = {
      new Field[BigDecimal, CustomerStatsMVRow](
        _path,
        "TOTAL_REVENUE",
        _.totalRevenue,
        None,
        None,
        (row, value) => row.copy(totalRevenue = value),
        ScalaDbTypes.Db2Types.decimal
      )
    }

    override def columns: java.util.List[FieldLike[?, CustomerStatsMVRow]] = java.util.List.of(this.customerId.underlying, this.customerName.underlying, this.totalOrders.underlying, this.totalRevenue.underlying)

    override def withPaths(`_path`: java.util.List[Path]): RelationStructure[CustomerStatsMVFields, CustomerStatsMVRow] = new Impl(`_path`)
  }

  def structure: Impl = new Impl(java.util.Collections.emptyList())
}