/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_stats;

import dev.typr.foundations.Db2Types;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.dsl.FieldsExpr;
import dev.typr.foundations.dsl.Path;
import dev.typr.foundations.dsl.RelationStructure;
import dev.typr.foundations.dsl.SqlExpr.Field;
import dev.typr.foundations.dsl.SqlExpr.FieldLike;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

public interface CustomerStatsMVFields extends FieldsExpr<CustomerStatsMVRow> {
  record Impl(List<Path> _path)
      implements CustomerStatsMVFields,
          RelationStructure<CustomerStatsMVFields, CustomerStatsMVRow> {
    @Override
    public Field<Integer, CustomerStatsMVRow> customerId() {
      return new Field<Integer, CustomerStatsMVRow>(
          _path,
          "CUSTOMER_ID",
          CustomerStatsMVRow::customerId,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withCustomerId(value),
          Db2Types.integer);
    }
    ;

    @Override
    public Field<String, CustomerStatsMVRow> customerName() {
      return new Field<String, CustomerStatsMVRow>(
          _path,
          "CUSTOMER_NAME",
          CustomerStatsMVRow::customerName,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withCustomerName(value),
          Db2Types.varchar);
    }
    ;

    @Override
    public Field<Integer, CustomerStatsMVRow> totalOrders() {
      return new Field<Integer, CustomerStatsMVRow>(
          _path,
          "TOTAL_ORDERS",
          CustomerStatsMVRow::totalOrders,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withTotalOrders(value),
          Db2Types.integer);
    }
    ;

    @Override
    public Field<BigDecimal, CustomerStatsMVRow> totalRevenue() {
      return new Field<BigDecimal, CustomerStatsMVRow>(
          _path,
          "TOTAL_REVENUE",
          CustomerStatsMVRow::totalRevenue,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withTotalRevenue(value),
          Db2Types.decimal);
    }
    ;

    @Override
    public List<FieldLike<?, CustomerStatsMVRow>> columns() {
      return java.util.List.of(
          this.customerId(), this.customerName(), this.totalOrders(), this.totalRevenue());
    }
    ;

    @Override
    public RelationStructure<CustomerStatsMVFields, CustomerStatsMVRow> withPaths(
        List<Path> _path) {
      return new Impl(_path);
    }
    ;
  }
  ;

  static Impl structure() {
    return new Impl(java.util.Collections.emptyList());
  }
  ;

  Field<Integer, CustomerStatsMVRow> customerId();

  Field<String, CustomerStatsMVRow> customerName();

  Field<Integer, CustomerStatsMVRow> totalOrders();

  Field<BigDecimal, CustomerStatsMVRow> totalRevenue();

  @Override
  List<FieldLike<?, CustomerStatsMVRow>> columns();

  @Override
  default RowParser<CustomerStatsMVRow> rowParser() {
    return CustomerStatsMVRow._rowParser;
  }
  ;
}
