/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.customer

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import frontpage.Text
import frontpage.customtypes.TypoUUID
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typo.dsl.Bijection

/** Type for the primary key of table `frontpage.customer` */
case class CustomerId(value: TypoUUID) extends scala.AnyVal

object CustomerId {
  given arrayColumn: Column[Array[CustomerId]] = Column.columnToArray(using column, implicitly)

  given arrayToStatement: ToStatement[Array[CustomerId]] = TypoUUID.arrayToStatement.contramap(_.map(_.value))

  given bijection: Bijection[CustomerId, TypoUUID] = Bijection.apply[CustomerId, TypoUUID](_.value)(CustomerId.apply)

  given column: Column[CustomerId] = TypoUUID.column.map(CustomerId.apply)

  given parameterMetadata: ParameterMetaData[CustomerId] = {
    new ParameterMetaData[CustomerId] {
      override def sqlType: String = TypoUUID.parameterMetadata.sqlType
      override def jdbcType: Int = TypoUUID.parameterMetadata.jdbcType
    }
  }

  given pgText: Text[CustomerId] = {
    new Text[CustomerId] {
      override def unsafeEncode(v: CustomerId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: CustomerId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeArrayEncode(v.value, sb)
    }
  }

  given reads: Reads[CustomerId] = TypoUUID.reads.map(CustomerId.apply)

  given toStatement: ToStatement[CustomerId] = TypoUUID.toStatement.contramap(_.value)

  given writes: Writes[CustomerId] = TypoUUID.writes.contramap(_.value)
}