/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage;

import frontpage.frontpage.Email;
import java.util.Random;

/** Methods to generate random data for domain types */
public interface TestDomainInsert {
  /** Domain `frontpage.email`
    * Constraint: CHECK ((VALUE ~ '^[^@]+@[^@]+\.[^@]+$'::text))
    */
  Email frontpageEmail(Random random);
}