/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.order_items;

import com.fasterxml.jackson.annotation.JsonProperty;
import dev.typr.foundations.Db2Types;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.RowParsers;
import java.math.BigDecimal;
import testdb.orders.OrdersId;

/** Table: ORDER_ITEMS Composite primary key: ORDER_ID, ITEM_NUMBER */
public record OrderItemsRow(
    /** Points to {@link testdb.orders.OrdersRow#orderId()} */
    @JsonProperty("ORDER_ID") OrdersId orderId,
    @JsonProperty("ITEM_NUMBER") Integer itemNumber,
    @JsonProperty("PRODUCT_NAME") String productName,
    @JsonProperty("QUANTITY") Integer quantity,
    @JsonProperty("UNIT_PRICE") BigDecimal unitPrice) {
  /** Points to {@link testdb.orders.OrdersRow#orderId()} */
  public OrderItemsRow withOrderId(OrdersId orderId) {
    return new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice);
  }
  ;

  public OrderItemsRow withItemNumber(Integer itemNumber) {
    return new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice);
  }
  ;

  public OrderItemsRow withProductName(String productName) {
    return new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice);
  }
  ;

  public OrderItemsRow withQuantity(Integer quantity) {
    return new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice);
  }
  ;

  public OrderItemsRow withUnitPrice(BigDecimal unitPrice) {
    return new OrderItemsRow(orderId, itemNumber, productName, quantity, unitPrice);
  }
  ;

  public static RowParser<OrderItemsRow> _rowParser =
      RowParsers.of(
          OrdersId.pgType,
          Db2Types.integer,
          Db2Types.varchar,
          Db2Types.integer,
          Db2Types.decimal,
          OrderItemsRow::new,
          row ->
              new Object[] {
                row.orderId(), row.itemNumber(), row.productName(), row.quantity(), row.unitPrice()
              });
  ;

  public static OrderItemsRow apply(
      OrderItemsId compositeId, String productName, Integer quantity, BigDecimal unitPrice) {
    return new OrderItemsRow(
        compositeId.orderId(), compositeId.itemNumber(), productName, quantity, unitPrice);
  }
  ;

  public OrderItemsId compositeId() {
    return new OrderItemsId(orderId, itemNumber);
  }
  ;

  public OrderItemsId id() {
    return this.compositeId();
  }
  ;
}
