/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.mariatest_unique

import dev.typr.foundations.MariaTypes
import dev.typr.foundations.Tuple.Tuple4
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers

/** Table: mariatest_unique
 * Primary key: id
 */
case class MariatestUniqueRow(
  /** 
   * AUTO_INCREMENT
   */
  id: MariatestUniqueId,
  /**  */
  email: String,
  /**  */
  code: String,
  /**  */
  category: String
) extends Tuple4[MariatestUniqueId, String, String, String] {
  def toUnsavedRow: MariatestUniqueRowUnsaved = new MariatestUniqueRowUnsaved(email, code, category)

  override def `_1`: MariatestUniqueId = id

  override def `_2`: String = email

  override def `_3`: String = code

  override def `_4`: String = category
}

object MariatestUniqueRow {
  val `_rowParser`: RowParser[MariatestUniqueRow] = RowParsers.of(MariatestUniqueId.dbType, MariaTypes.varchar, MariaTypes.varchar, MariaTypes.varchar)(MariatestUniqueRow.apply)(row => Array[Any](row.id, row.email, row.code, row.category))
}