/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.v_daily_sales;

import java.sql.Connection;
import java.util.List;
import typo.dsl.Dialect;
import typo.dsl.SelectBuilder;
import typo.runtime.Fragment;
import static typo.runtime.Fragment.interpolate;

public class VDailySalesViewRepoImpl implements VDailySalesViewRepo {
  @Override
  public SelectBuilder<VDailySalesViewFields, VDailySalesViewRow> select() {
    return SelectBuilder.of("`v_daily_sales`", VDailySalesViewFields.structure(), VDailySalesViewRow._rowParser, Dialect.MARIADB);
  };

  @Override
  public List<VDailySalesViewRow> selectAll(Connection c) {
    return interpolate(Fragment.lit("select `order_date`, `order_count`, `unique_customers`, `items_sold`, `gross_sales`, `total_discounts`, `total_shipping`, `total_tax`, `net_sales`, `avg_order_value`\nfrom `v_daily_sales`\n")).query(VDailySalesViewRow._rowParser.all()).runUnchecked(c);
  };
}