/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.businessentity

import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class BusinessentityRepoMock(
  toRow: BusinessentityRowUnsaved => BusinessentityRow,
  map: scala.collection.mutable.Map[BusinessentityId, BusinessentityRow] = scala.collection.mutable.Map.empty[BusinessentityId, BusinessentityRow]
) extends BusinessentityRepo {
  def delete: DeleteBuilder[BusinessentityFields, BusinessentityRow] = DeleteBuilderMock(DeleteParams.empty, BusinessentityFields.structure, map)

  def deleteById(businessentityid: BusinessentityId)(using c: Connection): Boolean = map.remove(businessentityid).isDefined

  def deleteByIds(businessentityids: Array[BusinessentityId])(using c: Connection): Int = businessentityids.map(id => map.remove(id)).count(_.isDefined)

  def insert(unsaved: BusinessentityRow)(using c: Connection): BusinessentityRow = {
    val _ = if (map.contains(unsaved.businessentityid))
      sys.error(s"id ${unsaved.businessentityid} already exists")
    else
      map.put(unsaved.businessentityid, unsaved)
  
    unsaved
  }

  def insert(unsaved: BusinessentityRowUnsaved)(using c: Connection): BusinessentityRow = insert(toRow(unsaved))

  def insertStreaming(
    unsaved: Iterator[BusinessentityRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { row =>
      map += (row.businessentityid -> row)
    }
    unsaved.size.toLong
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[BusinessentityRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { unsavedRow =>
      val row = toRow(unsavedRow)
      map += (row.businessentityid -> row)
    }
    unsaved.size.toLong
  }

  def select: SelectBuilder[BusinessentityFields, BusinessentityRow] = SelectBuilderMock(BusinessentityFields.structure, () => map.values.toList, SelectParams.empty)

  def selectAll(using c: Connection): List[BusinessentityRow] = map.values.toList

  def selectById(businessentityid: BusinessentityId)(using c: Connection): Option[BusinessentityRow] = map.get(businessentityid)

  def selectByIds(businessentityids: Array[BusinessentityId])(using c: Connection): List[BusinessentityRow] = businessentityids.flatMap(map.get).toList

  def selectByIdsTracked(businessentityids: Array[BusinessentityId])(using c: Connection): Map[BusinessentityId, BusinessentityRow] = {
    val byId = selectByIds(businessentityids).view.map(x => (x.businessentityid, x)).toMap
    businessentityids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def update: UpdateBuilder[BusinessentityFields, BusinessentityRow] = UpdateBuilderMock(UpdateParams.empty, BusinessentityFields.structure, map)

  def update(row: BusinessentityRow)(using c: Connection): Option[BusinessentityRow] = {
    map.get(row.businessentityid).map { _ =>
      map.put(row.businessentityid, row): @nowarn
      row
    }
  }

  def upsert(unsaved: BusinessentityRow)(using c: Connection): BusinessentityRow = {
    map.put(unsaved.businessentityid, unsaved): @nowarn
    unsaved
  }

  def upsertBatch(unsaved: Iterable[BusinessentityRow])(using c: Connection): List[BusinessentityRow] = {
    unsaved.map { row =>
      map += (row.businessentityid -> row)
      row
    }.toList
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[BusinessentityRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    unsaved.foreach { row =>
      map += (row.businessentityid -> row)
    }
    unsaved.size
  }
}