/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.order_items

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import dev.typr.foundations.scala.ScalaDbTypes
import testdb.orders.OrdersId

/** Type for the composite primary key of table `ORDER_ITEMS` */
case class OrderItemsId(
  @JsonProperty("ORDER_ID") orderId: OrdersId,
  @JsonProperty("ITEM_NUMBER") itemNumber: Int
)

object OrderItemsId {
  val `_rowParser`: RowParser[OrderItemsId] = RowParsers.of(OrdersId.pgType, ScalaDbTypes.Db2Types.integer)(OrderItemsId.apply)(row => Array[Any](row.orderId, row.itemNumber))
}