/**
 * File automatically generated by `typo` for its own test suite.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN
 */
package testdb.hardcoded.myschema.football_club;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import testdb.hardcoded.myschema.football_club.FootballClubFieldValue.id;
import testdb.hardcoded.myschema.football_club.FootballClubFieldValue.name;
import typo.runtime.Fragment;
import typo.runtime.PgTypes;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public record FootballClubRepoImpl() implements FootballClubRepo {
  public Boolean deleteById(
    FootballClubId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "myschema"."football_club" where "id" = 
      """),
      FootballClubId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };
  public Integer deleteByIds(
    FootballClubId[] ids,
    Connection c
  ) {
    return interpolate(
               typo.runtime.Fragment.lit("""
                  delete
                  from "myschema"."football_club"
                  where "id" = ANY("""),
               FootballClubId.pgTypeArray.encode(ids),
               typo.runtime.Fragment.lit(")")
             )
      .update()
      .runUnchecked(c);
  };
  public FootballClubRow insert(
    FootballClubRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "myschema"."football_club"("id", "name")
         values ("""),
      FootballClubId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::int8, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         returning "id", "name"
      """)
    )
      .updateReturning(FootballClubRow._rowParser.exactlyOne()).runUnchecked(c);
  };
  public Long insertStreaming(
    Iterator<FootballClubRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "myschema"."football_club"("id", "name") FROM STDIN
    """), batchSize, unsaved, c, FootballClubRow.pgText);
  };
  public List<FootballClubRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "name"
       from "myschema"."football_club"
    """)).as(FootballClubRow._rowParser.all()).runUnchecked(c);
  };
  public List<FootballClubRow> selectByFieldValues(
    List<FootballClubFieldValue<?>> fieldValues,
    Connection c
  ) {
    Fragment where = Fragment.whereAnd(
        fieldValues.stream().map(
          fv -> switch (fv) {
                  case id x -> interpolate(
                    typo.runtime.Fragment.lit("""
                    "id" = 
                    """),
                    FootballClubId.pgType.encode(x.value()),
                    typo.runtime.Fragment.lit("")
                  );
                  case name x -> interpolate(
                    typo.runtime.Fragment.lit("""
                    "name" = 
                    """),
                    PgTypes.text.encode(x.value()),
                    typo.runtime.Fragment.lit("")
                  );
                }
        ).toList()
      );;
    return interpolate(
             typo.runtime.Fragment.lit("""
             select "id", "name" from "myschema"."football_club" 
             """),
             where,
             typo.runtime.Fragment.lit("")
           ).as(FootballClubRow._rowParser.all()).runUnchecked(c);
  };
  public Optional<FootballClubRow> selectById(
    FootballClubId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name"
         from "myschema"."football_club"
         where "id" = """),
      FootballClubId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).as(FootballClubRow._rowParser.first()).runUnchecked(c);
  };
  public List<FootballClubRow> selectByIds(
    FootballClubId[] ids,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name"
         from "myschema"."football_club"
         where "id" = ANY("""),
      FootballClubId.pgTypeArray.encode(ids),
      typo.runtime.Fragment.lit(")")
    ).as(FootballClubRow._rowParser.all()).runUnchecked(c);
  };
  public Map<FootballClubId, FootballClubRow> selectByIdsTracked(
    FootballClubId[] ids,
    Connection c
  ) {
    Map<FootballClubId, FootballClubRow> ret = new HashMap<>();;
      for (var row : selectByIds(ids, c)) {
          ret.put(row.id(), row);
      };
    return ret;
  };
  public Boolean update(
    FootballClubRow row,
    Connection c
  ) {
    FootballClubId id = row.id();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "myschema"."football_club"
                set "name" = """),
             PgTypes.text.encode(row.name()),
             typo.runtime.Fragment.lit("""
   
                where "id" = """),
             FootballClubId.pgType.encode(id),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };
  public Boolean updateFieldValues(
    FootballClubId id,
    List<FootballClubFieldValue<?>> fieldValues,
    Connection c
  ) {
    List<Fragment> updates = fieldValues.stream().map(
        fv -> switch (fv) {
                case id x -> interpolate(
                  typo.runtime.Fragment.lit("""
                  "id" = 
                  """),
                  FootballClubId.pgType.encode(x.value()),
                  typo.runtime.Fragment.lit("")
                );
                case name x -> interpolate(
                  typo.runtime.Fragment.lit("""
                  "name" = 
                  """),
                  PgTypes.text.encode(x.value()),
                  typo.runtime.Fragment.lit("")
                );
              }
      ).toList();;
    return updates.isEmpty()
             ? false
             : interpolate(
                     typo.runtime.Fragment.lit("""
                     update "myschema"."football_club"

                     """),
                     Fragment.set(updates),
                     typo.runtime.Fragment.lit("""
   
                        where "id" = """),
                     FootballClubId.pgType.encode(id),
                     typo.runtime.Fragment.lit("")
                   )
                 .update().runUnchecked(c) > 0;
  };
  public FootballClubRow upsert(
    FootballClubRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "myschema"."football_club"("id", "name")
         values ("""),
      FootballClubId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::int8, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         on conflict ("id")
         do update set
           "name" = EXCLUDED."name"
         returning "id", "name"
      """)
    )
      .updateReturning(FootballClubRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };
  public List<FootballClubRow> upsertBatch(
    Iterator<FootballClubRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "myschema"."football_club"("id", "name")
                values (?::int8, ?)
                on conflict ("id")
                do update set
                  "name" = EXCLUDED."name"
                returning "id", "name"
             """))
      .updateManyReturning(FootballClubRow._rowParser, unsaved)
      .runUnchecked(c);
  };
  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<FootballClubRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table football_club_TEMP (like "myschema"."football_club") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy football_club_TEMP("id", "name") from stdin
      """), batchSize, unsaved, c, FootballClubRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "myschema"."football_club"("id", "name")
              select * from football_club_TEMP
              on conflict ("id")
              do update set
                "name" = EXCLUDED."name"
              ;
              drop table football_club_TEMP;""")).update().runUnchecked(c);
  };
}