/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.product_images

import com.fasterxml.jackson.annotation.JsonProperty
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import testdb.products.ProductsId
import typo.runtime.MariaText
import typo.runtime.MariaTypes
import typo.scaladsl.MariaTypeOps
import typo.scaladsl.ScalaDbTypes

/** This class corresponds to a row in table `product_images` which has not been persisted yet */
case class ProductImagesRowUnsaved(
  /** 
   * Points to [[testdb.products.ProductsRow.productId]]
   */
  @JsonProperty("product_id") productId: ProductsId,
  /**  */
  @JsonProperty("image_url") imageUrl: String,
  /** Default: NULL

   */
  @JsonProperty("thumbnail_url") thumbnailUrl: Defaulted[Option[String]] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("alt_text") altText: Defaulted[Option[String]] = new UseDefault(),
  /** Default: 0

   */
  @JsonProperty("sort_order") sortOrder: Defaulted[Short] = new UseDefault(),
  /** Default: 0

   */
  @JsonProperty("is_primary") isPrimary: Defaulted[Boolean] = new UseDefault(),
  /** Default: NULL
   * Optional embedded image data
   */
  @JsonProperty("image_data") imageData: Defaulted[Option[Array[Byte]]] = new UseDefault()
) {
  def toRow(
    thumbnailUrlDefault: => Option[String],
    altTextDefault: => Option[String],
    sortOrderDefault: => Short,
    isPrimaryDefault: => Boolean,
    imageDataDefault: => Option[Array[Byte]],
    imageIdDefault: => ProductImagesId
  ): ProductImagesRow = {
    new ProductImagesRow(
      imageId = imageIdDefault,
      productId = productId,
      imageUrl = imageUrl,
      thumbnailUrl = thumbnailUrl.getOrElse(thumbnailUrlDefault),
      altText = altText.getOrElse(altTextDefault),
      sortOrder = sortOrder.getOrElse(sortOrderDefault),
      isPrimary = isPrimary.getOrElse(isPrimaryDefault),
      imageData = imageData.getOrElse(imageDataDefault)
    )
  }
}

object ProductImagesRowUnsaved {
  given mariaText: MariaText[ProductImagesRowUnsaved] = MariaText.instance((row, sb) => { ProductsId.pgType.mariaText.unsafeEncode(row.productId, sb); sb.append(MariaText.DELIMETER); MariaTypes.varchar.mariaText.unsafeEncode(row.imageUrl, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.varchar.nullable.mariaText).unsafeEncode(row.thumbnailUrl, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.varchar.nullable.mariaText).unsafeEncode(row.altText, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using ScalaDbTypes.MariaTypes.tinyintUnsigned.mariaText).unsafeEncode(row.sortOrder, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using ScalaDbTypes.MariaTypes.bool.mariaText).unsafeEncode(row.isPrimary, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.longblob.nullable.mariaText).unsafeEncode(row.imageData, sb) })
}