/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.payment_methods;

import com.fasterxml.jackson.annotation.JsonValue;
import typo.dsl.Bijection;
import typo.runtime.MariaType;
import typo.runtime.MariaTypes;

/** Type for the primary key of table `payment_methods` */
public record PaymentMethodsId(@JsonValue Short value) {
  public PaymentMethodsId withValue(Short value) {
    return new PaymentMethodsId(value);
  };

  @Override
  public java.lang.String toString() {
    return value.toString();
  };

  static public Bijection<PaymentMethodsId, Short> bijection =
    Bijection.of(PaymentMethodsId::value, PaymentMethodsId::new);

  static public MariaType<PaymentMethodsId> pgType =
    MariaTypes.tinyintUnsigned.bimap(PaymentMethodsId::new, PaymentMethodsId::value);
}