/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customers

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.MariaTypes
import dev.typr.foundations.Tuple.Tuple14
import dev.typr.foundations.data.Json
import dev.typr.foundations.scala.DbTypeOps
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import java.time.LocalDateTime
import testdb.EmailMailPushSmsSet
import testdb.customer_status.CustomerStatusId
import testdb.customtypes.Defaulted

/** Table: customers
 * Primary key: customer_id
 */
case class CustomersRow(
  /** 
   * AUTO_INCREMENT
   */
  @JsonProperty("customer_id") customerId: CustomersId,
  /**  */
  email: String,
  /**  */
  @JsonProperty("password_hash") passwordHash: Array[Byte],
  /**  */
  @JsonProperty("first_name") firstName: String,
  /**  */
  @JsonProperty("last_name") lastName: String,
  /** 
   * Default: NULL
   */
  phone: Option[String],
  /** 
   * Default: 'pending'
   * Points to [[testdb.customer_status.CustomerStatusRow.statusCode]]
   */
  status: CustomerStatusId,
  /** 
   * Default: 'bronze'
   */
  tier: String,
  /** 
   * Default: NULL
   */
  preferences: Option[Json],
  /** 
   * Default: NULL
   */
  @JsonProperty("marketing_flags") marketingFlags: Option[EmailMailPushSmsSet],
  /** 
   * Default: NULL
   */
  notes: Option[String],
  /** 
   * Default: current_timestamp(6)
   */
  @JsonProperty("created_at") createdAt: LocalDateTime,
  /** 
   * Default: current_timestamp(6)
   */
  @JsonProperty("updated_at") updatedAt: LocalDateTime,
  /** 
   * Default: NULL
   */
  @JsonProperty("last_login_at") lastLoginAt: Option[LocalDateTime]
) extends Tuple14[CustomersId, String, Array[Byte], String, String, Option[String], CustomerStatusId, String, Option[Json], Option[EmailMailPushSmsSet], Option[String], LocalDateTime, LocalDateTime, Option[LocalDateTime]] {
  def id: CustomersId = customerId

  def toUnsavedRow(
    phone: Defaulted[Option[String]] = Defaulted.Provided(this.phone),
    status: Defaulted[CustomerStatusId] = Defaulted.Provided(this.status),
    tier: Defaulted[String] = Defaulted.Provided(this.tier),
    preferences: Defaulted[Option[Json]] = Defaulted.Provided(this.preferences),
    marketingFlags: Defaulted[Option[EmailMailPushSmsSet]] = Defaulted.Provided(this.marketingFlags),
    notes: Defaulted[Option[String]] = Defaulted.Provided(this.notes),
    createdAt: Defaulted[LocalDateTime] = Defaulted.Provided(this.createdAt),
    updatedAt: Defaulted[LocalDateTime] = Defaulted.Provided(this.updatedAt),
    lastLoginAt: Defaulted[Option[LocalDateTime]] = Defaulted.Provided(this.lastLoginAt)
  ): CustomersRowUnsaved = {
    new CustomersRowUnsaved(
      email,
      passwordHash,
      firstName,
      lastName,
      phone,
      status,
      tier,
      preferences,
      marketingFlags,
      notes,
      createdAt,
      updatedAt,
      lastLoginAt
    )
  }

  override def `_1`: CustomersId = customerId

  override def `_2`: String = email

  override def `_3`: Array[Byte] = passwordHash

  override def `_4`: String = firstName

  override def `_5`: String = lastName

  override def `_6`: Option[String] = phone

  override def `_7`: CustomerStatusId = status

  override def `_8`: String = tier

  override def `_9`: Option[Json] = preferences

  override def `_10`: Option[EmailMailPushSmsSet] = marketingFlags

  override def `_11`: Option[String] = notes

  override def `_12`: LocalDateTime = createdAt

  override def `_13`: LocalDateTime = updatedAt

  override def `_14`: Option[LocalDateTime] = lastLoginAt
}

object CustomersRow {
  val `_rowParser`: RowParser[CustomersRow] = RowParsers.of(CustomersId.dbType, MariaTypes.varchar, MariaTypes.binary, MariaTypes.varchar, MariaTypes.varchar, MariaTypes.varchar.nullable, CustomerStatusId.dbType, MariaTypes.text, MariaTypes.json.nullable, EmailMailPushSmsSet.dbType.nullable, MariaTypes.text.nullable, MariaTypes.datetime, MariaTypes.datetime, MariaTypes.datetime.nullable)(CustomersRow.apply)(row => Array[Any](row.customerId, row.email, row.passwordHash, row.firstName, row.lastName, row.phone, row.status, row.tier, row.preferences, row.marketingFlags, row.notes, row.createdAt, row.updatedAt, row.lastLoginAt))
}