/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.table_with_generated_columns

import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.streamingInsert
import typo.runtime.FragmentInterpolator.interpolate

class TableWithGeneratedColumnsRepoImpl extends TableWithGeneratedColumnsRepo {
  def delete: DeleteBuilder[TableWithGeneratedColumnsFields, TableWithGeneratedColumnsRow] = DeleteBuilder.of("public.table-with-generated-columns", TableWithGeneratedColumnsFields.structure)

  def deleteById(name: TableWithGeneratedColumnsId)(using c: Connection): java.lang.Boolean = interpolate"""delete from "public"."table-with-generated-columns" where "name" = ${TableWithGeneratedColumnsId.pgType.encode(name)}""".update().runUnchecked(c) > 0

  def deleteByIds(names: Array[TableWithGeneratedColumnsId])(using c: Connection): Integer = {
    interpolate"""delete
    from "public"."table-with-generated-columns"
    where "name" = ANY(${TableWithGeneratedColumnsId.pgTypeArray.encode(names)})"""
      .update()
      .runUnchecked(c)
  }

  def insert(unsaved: TableWithGeneratedColumnsRow)(using c: Connection): TableWithGeneratedColumnsRow = {
  interpolate"""insert into "public"."table-with-generated-columns"("name")
    values (${TableWithGeneratedColumnsId.pgType.encode(unsaved.name)})
    returning "name", "name-type-always"
    """
    .updateReturning(TableWithGeneratedColumnsRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insert(unsaved: TableWithGeneratedColumnsRowUnsaved)(using c: Connection): TableWithGeneratedColumnsRow = {
    val columns: java.util.List[Literal] = new ArrayList()
    val values: java.util.List[Fragment] = new ArrayList()
    columns.add(Fragment.lit(""""name"""")): @scala.annotation.nowarn
    values.add(interpolate"${TableWithGeneratedColumnsId.pgType.encode(unsaved.name)}"): @scala.annotation.nowarn
    val q: Fragment = {
      interpolate"""insert into "public"."table-with-generated-columns"(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning "name", "name-type-always"
      """
    }
    q.updateReturning(TableWithGeneratedColumnsRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insertStreaming(
    unsaved: java.util.Iterator[TableWithGeneratedColumnsRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "public"."table-with-generated-columns"("name") FROM STDIN""", batchSize, unsaved, c, TableWithGeneratedColumnsRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[TableWithGeneratedColumnsRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "public"."table-with-generated-columns"("name") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved, c, TableWithGeneratedColumnsRowUnsaved.pgText)

  def select: SelectBuilder[TableWithGeneratedColumnsFields, TableWithGeneratedColumnsRow] = SelectBuilder.of("public.table-with-generated-columns", TableWithGeneratedColumnsFields.structure, TableWithGeneratedColumnsRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[TableWithGeneratedColumnsRow] = {
    interpolate"""select "name", "name-type-always"
    from "public"."table-with-generated-columns"
    """.as(TableWithGeneratedColumnsRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectById(name: TableWithGeneratedColumnsId)(using c: Connection): Optional[TableWithGeneratedColumnsRow] = {
    interpolate"""select "name", "name-type-always"
    from "public"."table-with-generated-columns"
    where "name" = ${TableWithGeneratedColumnsId.pgType.encode(name)}""".as(TableWithGeneratedColumnsRow.`_rowParser`.first()).runUnchecked(c)
  }

  def selectByIds(names: Array[TableWithGeneratedColumnsId])(using c: Connection): java.util.List[TableWithGeneratedColumnsRow] = {
    interpolate"""select "name", "name-type-always"
    from "public"."table-with-generated-columns"
    where "name" = ANY(${TableWithGeneratedColumnsId.pgTypeArray.encode(names)})""".as(TableWithGeneratedColumnsRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectByIdsTracked(names: Array[TableWithGeneratedColumnsId])(using c: Connection): java.util.Map[TableWithGeneratedColumnsId, TableWithGeneratedColumnsRow] = {
    val ret: java.util.Map[TableWithGeneratedColumnsId, TableWithGeneratedColumnsRow] = new HashMap()
    selectByIds(names)(using c).forEach(row => ret.put(row.name, row): @scala.annotation.nowarn)
    ret
  }

  def update: UpdateBuilder[TableWithGeneratedColumnsFields, TableWithGeneratedColumnsRow] = UpdateBuilder.of("public.table-with-generated-columns", TableWithGeneratedColumnsFields.structure, TableWithGeneratedColumnsRow.`_rowParser`.all())

  def upsert(unsaved: TableWithGeneratedColumnsRow)(using c: Connection): TableWithGeneratedColumnsRow = {
  interpolate"""insert into "public"."table-with-generated-columns"("name")
    values (${TableWithGeneratedColumnsId.pgType.encode(unsaved.name)})
    on conflict ("name")
    do update set "name" = EXCLUDED."name"
    returning "name", "name-type-always"
    """
    .updateReturning(TableWithGeneratedColumnsRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  def upsertBatch(unsaved: java.util.Iterator[TableWithGeneratedColumnsRow])(using c: Connection): java.util.List[TableWithGeneratedColumnsRow] = {
    interpolate"""insert into "public"."table-with-generated-columns"("name")
    values (?)
    on conflict ("name")
    do nothing
    returning "name", "name-type-always"
    """
      .updateManyReturning(TableWithGeneratedColumnsRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[TableWithGeneratedColumnsRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    interpolate"""create temporary table table-with-generated-columns_TEMP (like "public"."table-with-generated-columns") on commit drop""".update().runUnchecked(c): @scala.annotation.nowarn
    streamingInsert.insertUnchecked(s"""copy table-with-generated-columns_TEMP("name") from stdin""", batchSize, unsaved, c, TableWithGeneratedColumnsRow.pgText): @scala.annotation.nowarn
    interpolate"""insert into "public"."table-with-generated-columns"("name")
    select * from table-with-generated-columns_TEMP
    on conflict ("name")
    do nothing
    ;
    drop table table-with-generated-columns_TEMP;""".update().runUnchecked(c)
  }
}