/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_.only_pk_columns;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import typo.dsl.DeleteBuilder;
import typo.dsl.DeleteBuilder.DeleteBuilderMock;
import typo.dsl.DeleteParams;
import typo.dsl.SelectBuilder;
import typo.dsl.SelectBuilderMock;
import typo.dsl.SelectParams;
import typo.dsl.UpdateBuilder;
import typo.dsl.UpdateBuilder.UpdateBuilderMock;
import typo.dsl.UpdateParams;
import static typo.runtime.internal.stringInterpolator.str;

public record OnlyPkColumnsRepoMock(HashMap<OnlyPkColumnsId, OnlyPkColumnsRow> map) implements OnlyPkColumnsRepo {
  public OnlyPkColumnsRepoMock() {
    this(new HashMap<OnlyPkColumnsId, OnlyPkColumnsRow>());
  };

  public OnlyPkColumnsRepoMock withMap(HashMap<OnlyPkColumnsId, OnlyPkColumnsRow> map) {
    return new OnlyPkColumnsRepoMock(map);
  };

  public DeleteBuilder<OnlyPkColumnsFields, OnlyPkColumnsRow> delete() {
    return new DeleteBuilderMock<>(OnlyPkColumnsFields.structure(), () -> new ArrayList<>(map.values()), DeleteParams.empty(), row -> row.compositeId(), id -> map.remove(id));
  };

  public Boolean deleteById(
    OnlyPkColumnsId compositeId,
    Connection c
  ) {
    return Optional.ofNullable(map.remove(compositeId)).isPresent();
  };

  public Integer deleteByIds(
    OnlyPkColumnsId[] compositeIds,
    Connection c
  ) {
    var count = 0;
      for (var id : compositeIds) { if (Optional.ofNullable(map.remove(id)).isPresent()) {
        count = count + 1;
      } };
    return count;
  };

  public OnlyPkColumnsRow insert(
    OnlyPkColumnsRow unsaved,
    Connection c
  ) {
    if (map.containsKey(unsaved.compositeId())) {
        throw new RuntimeException(str("id $unsaved.compositeId() already exists"));
      };
      map.put(unsaved.compositeId(), unsaved);
    return unsaved;
  };

  public Long insertStreaming(
    Iterator<OnlyPkColumnsRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.compositeId(), row);
        count = count + 1L;
      };
    return count;
  };

  public SelectBuilder<OnlyPkColumnsFields, OnlyPkColumnsRow> select() {
    return new SelectBuilderMock<>(OnlyPkColumnsFields.structure(), () -> new ArrayList<>(map.values()), SelectParams.empty());
  };

  public List<OnlyPkColumnsRow> selectAll(Connection c) {
    return new ArrayList<>(map.values());
  };

  public Optional<OnlyPkColumnsRow> selectById(
    OnlyPkColumnsId compositeId,
    Connection c
  ) {
    return Optional.ofNullable(map.get(compositeId));
  };

  public List<OnlyPkColumnsRow> selectByIds(
    OnlyPkColumnsId[] compositeIds,
    Connection c
  ) {
    var result = new ArrayList<OnlyPkColumnsRow>();
      for (var id : compositeIds) { var opt = Optional.ofNullable(map.get(id));
      if (opt.isPresent()) result.add(opt.get()); };
    return result;
  };

  public Map<OnlyPkColumnsId, OnlyPkColumnsRow> selectByIdsTracked(
    OnlyPkColumnsId[] compositeIds,
    Connection c
  ) {
    return selectByIds(compositeIds, c).stream().collect(Collectors.toMap((adventureworks.public_.only_pk_columns.OnlyPkColumnsRow row) -> row.compositeId(), Function.identity()));
  };

  public UpdateBuilder<OnlyPkColumnsFields, OnlyPkColumnsRow> update() {
    return new UpdateBuilderMock<>(OnlyPkColumnsFields.structure(), () -> new ArrayList<>(map.values()), UpdateParams.empty(), row -> row);
  };

  public OnlyPkColumnsRow upsert(
    OnlyPkColumnsRow unsaved,
    Connection c
  ) {
    map.put(unsaved.compositeId(), unsaved);
    return unsaved;
  };

  public List<OnlyPkColumnsRow> upsertBatch(
    Iterator<OnlyPkColumnsRow> unsaved,
    Connection c
  ) {
    var result = new ArrayList<OnlyPkColumnsRow>();
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.compositeId(), row);
        result.add(row);
      };
    return result;
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<OnlyPkColumnsRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.compositeId(), row);
        count = count + 1;
      };
    return count;
  };
}