/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.user

import anorm.BatchSql
import anorm.NamedParameter
import anorm.ParameterMetaData
import anorm.ParameterValue
import anorm.RowParser
import anorm.SQL
import anorm.SimpleSql
import anorm.ToStatement
import frontpage.customtypes.Defaulted
import frontpage.customtypes.TypoLocalDateTime
import frontpage.frontpage.Email
import frontpage.frontpage.UserRole
import frontpage.frontpage.UserStatus
import frontpage.frontpage.department.DepartmentId
import frontpage.streamingInsert
import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import anorm.SqlStringInterpolation

class UserRepoImpl extends UserRepo {
  def delete: DeleteBuilder[UserFields, UserRow] = DeleteBuilder.of(""""frontpage"."user"""", UserFields.structure, UserRow.rowParser(1).*)

  def deleteById(id: UserId)(using c: Connection): Boolean = SQL"""delete from "frontpage"."user" where "id" = ${ParameterValue(id, null, UserId.toStatement)}""".executeUpdate() > 0

  def deleteByIds(ids: Array[UserId])(using c: Connection): Int = {
    SQL"""delete
    from "frontpage"."user"
    where "id" = ANY(${ParameterValue(ids, null, UserId.arrayToStatement)})
    """.executeUpdate()
  }

  def insert(unsaved: UserRow)(using c: Connection): UserRow = {
  SQL"""insert into "frontpage"."user"("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role")
    values (${ParameterValue(unsaved.id, null, UserId.toStatement)}::uuid, ${ParameterValue(unsaved.email, null, Email.toStatement)}::text, ${ParameterValue(unsaved.name, null, ToStatement.stringToStatement)}, ${ParameterValue(unsaved.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp, ${ParameterValue(unsaved.departmentId, null, ToStatement.optionToStatement(using DepartmentId.toStatement, DepartmentId.parameterMetadata))}::uuid, ${ParameterValue(unsaved.status, null, ToStatement.optionToStatement(using UserStatus.toStatement, UserStatus.parameterMetadata))}::frontpage.user_status, ${ParameterValue(unsaved.verified, null, ToStatement.optionToStatement(using ToStatement.booleanToStatement, ParameterMetaData.BooleanParameterMetaData))}, ${ParameterValue(unsaved.managerId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid, ${ParameterValue(unsaved.role, null, ToStatement.optionToStatement(using UserRole.toStatement, UserRole.parameterMetadata))}::frontpage.user_role)
    returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    """
    .executeInsert(UserRow.rowParser(1).single)
  }

  def insert(unsaved: UserRowUnsaved)(using c: Connection): UserRow = {
    val namedParameters = List(
      Some((NamedParameter("email", ParameterValue(unsaved.email, null, Email.toStatement)), "::text")),
      Some((NamedParameter("name", ParameterValue(unsaved.name, null, ToStatement.stringToStatement)), "")),
      Some((NamedParameter("department_id", ParameterValue(unsaved.departmentId, null, ToStatement.optionToStatement(using DepartmentId.toStatement, DepartmentId.parameterMetadata))), "::uuid")),
      Some((NamedParameter("manager_id", ParameterValue(unsaved.managerId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))), "::uuid")),
      unsaved.id match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("id", ParameterValue(value, null, UserId.toStatement)), "::uuid"))
      },
      unsaved.createdAt match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("created_at", ParameterValue(value, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))), "::timestamp"))
      },
      unsaved.status match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("status", ParameterValue(value, null, ToStatement.optionToStatement(using UserStatus.toStatement, UserStatus.parameterMetadata))), "::frontpage.user_status"))
      },
      unsaved.verified match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("verified", ParameterValue(value, null, ToStatement.optionToStatement(using ToStatement.booleanToStatement, ParameterMetaData.BooleanParameterMetaData))), ""))
      },
      unsaved.role match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("role", ParameterValue(value, null, ToStatement.optionToStatement(using UserRole.toStatement, UserRole.parameterMetadata))), "::frontpage.user_role"))
      }
    ).flatten
    val quote = '"'.toString
    if (namedParameters.isEmpty) {
      SQL"""insert into "frontpage"."user" default values
      returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
      """
        .executeInsert(UserRow.rowParser(1).single)
    } else {
      val q = s"""insert into "frontpage"."user"(${namedParameters.map{case (x, _) => quote + x.name + quote}.mkString(", ")})
              values (${namedParameters.map{ case (np, cast) => s"{${np.name}}$cast"}.mkString(", ")})
              returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
              """
      SimpleSql(SQL(q), namedParameters.map { case (np, _) => np.tupled }.toMap, RowParser.successful)
        .executeInsert(UserRow.rowParser(1).single)
    }
  }

  def insertStreaming(
    unsaved: Iterator[UserRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."user"("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role") FROM STDIN""", batchSize, unsaved)(using UserRow.pgText, c)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[UserRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."user"("email", "name", "department_id", "manager_id", "id", "created_at", "status", "verified", "role") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved)(using UserRowUnsaved.pgText, c)

  def select: SelectBuilder[UserFields, UserRow] = SelectBuilder.of(""""frontpage"."user"""", UserFields.structure, UserRow.rowParser)

  def selectAll(using c: Connection): List[UserRow] = {
    SQL"""select "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    from "frontpage"."user"
    """.as(UserRow.rowParser(1).*)
  }

  def selectById(id: UserId)(using c: Connection): Option[UserRow] = {
    SQL"""select "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    from "frontpage"."user"
    where "id" = ${ParameterValue(id, null, UserId.toStatement)}
    """.as(UserRow.rowParser(1).singleOpt)
  }

  def selectByIds(ids: Array[UserId])(using c: Connection): List[UserRow] = {
    SQL"""select "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    from "frontpage"."user"
    where "id" = ANY(${ParameterValue(ids, null, UserId.arrayToStatement)})
    """.as(UserRow.rowParser(1).*)
  }

  def selectByIdsTracked(ids: Array[UserId])(using c: Connection): Map[UserId, UserRow] = {
    val byId = selectByIds(ids).view.map(x => (x.id, x)).toMap
    ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def selectByUniqueEmail(email: Email)(using c: Connection): Option[UserRow] = {
    SQL"""select "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    from "frontpage"."user"
    where "email" = ${ParameterValue(email, null, Email.toStatement)}
    """.as(UserRow.rowParser(1).singleOpt)
  }

  def update: UpdateBuilder[UserFields, UserRow] = UpdateBuilder.of(""""frontpage"."user"""", UserFields.structure, UserRow.rowParser(1).*)

  def update(row: UserRow)(using c: Connection): Option[UserRow] = {
    val id = row.id
    SQL"""update "frontpage"."user"
    set "email" = ${ParameterValue(row.email, null, Email.toStatement)}::text,
    "name" = ${ParameterValue(row.name, null, ToStatement.stringToStatement)},
    "created_at" = ${ParameterValue(row.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp,
    "department_id" = ${ParameterValue(row.departmentId, null, ToStatement.optionToStatement(using DepartmentId.toStatement, DepartmentId.parameterMetadata))}::uuid,
    "status" = ${ParameterValue(row.status, null, ToStatement.optionToStatement(using UserStatus.toStatement, UserStatus.parameterMetadata))}::frontpage.user_status,
    "verified" = ${ParameterValue(row.verified, null, ToStatement.optionToStatement(using ToStatement.booleanToStatement, ParameterMetaData.BooleanParameterMetaData))},
    "manager_id" = ${ParameterValue(row.managerId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid,
    "role" = ${ParameterValue(row.role, null, ToStatement.optionToStatement(using UserRole.toStatement, UserRole.parameterMetadata))}::frontpage.user_role
    where "id" = ${ParameterValue(id, null, UserId.toStatement)}
    returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    """.executeInsert(UserRow.rowParser(1).singleOpt)
  }

  def upsert(unsaved: UserRow)(using c: Connection): UserRow = {
  SQL"""insert into "frontpage"."user"("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role")
    values (
      ${ParameterValue(unsaved.id, null, UserId.toStatement)}::uuid,
    ${ParameterValue(unsaved.email, null, Email.toStatement)}::text,
    ${ParameterValue(unsaved.name, null, ToStatement.stringToStatement)},
    ${ParameterValue(unsaved.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp,
    ${ParameterValue(unsaved.departmentId, null, ToStatement.optionToStatement(using DepartmentId.toStatement, DepartmentId.parameterMetadata))}::uuid,
    ${ParameterValue(unsaved.status, null, ToStatement.optionToStatement(using UserStatus.toStatement, UserStatus.parameterMetadata))}::frontpage.user_status,
    ${ParameterValue(unsaved.verified, null, ToStatement.optionToStatement(using ToStatement.booleanToStatement, ParameterMetaData.BooleanParameterMetaData))},
    ${ParameterValue(unsaved.managerId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid,
    ${ParameterValue(unsaved.role, null, ToStatement.optionToStatement(using UserRole.toStatement, UserRole.parameterMetadata))}::frontpage.user_role
    )
    on conflict ("id")
    do update set
      "email" = EXCLUDED."email",
    "name" = EXCLUDED."name",
    "created_at" = EXCLUDED."created_at",
    "department_id" = EXCLUDED."department_id",
    "status" = EXCLUDED."status",
    "verified" = EXCLUDED."verified",
    "manager_id" = EXCLUDED."manager_id",
    "role" = EXCLUDED."role"
    returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
    """
    .executeInsert(UserRow.rowParser(1).single)
  }

  def upsertBatch(unsaved: Iterable[UserRow])(using c: Connection): List[UserRow] = {
    def toNamedParameter(row: UserRow): List[NamedParameter] = List(
      NamedParameter("id", ParameterValue(row.id, null, UserId.toStatement)),
      NamedParameter("email", ParameterValue(row.email, null, Email.toStatement)),
      NamedParameter("name", ParameterValue(row.name, null, ToStatement.stringToStatement)),
      NamedParameter("created_at", ParameterValue(row.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))),
      NamedParameter("department_id", ParameterValue(row.departmentId, null, ToStatement.optionToStatement(using DepartmentId.toStatement, DepartmentId.parameterMetadata))),
      NamedParameter("status", ParameterValue(row.status, null, ToStatement.optionToStatement(using UserStatus.toStatement, UserStatus.parameterMetadata))),
      NamedParameter("verified", ParameterValue(row.verified, null, ToStatement.optionToStatement(using ToStatement.booleanToStatement, ParameterMetaData.BooleanParameterMetaData))),
      NamedParameter("manager_id", ParameterValue(row.managerId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))),
      NamedParameter("role", ParameterValue(row.role, null, ToStatement.optionToStatement(using UserRole.toStatement, UserRole.parameterMetadata)))
    )
    unsaved.toList match {
      case Nil => Nil
      case head :: rest =>
        new anorm.frontpage.ExecuteReturningSyntax.Ops(
          BatchSql(
            s"""insert into "frontpage"."user"("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role")
            values ({id}::uuid, {email}::text, {name}, {created_at}::timestamp, {department_id}::uuid, {status}::frontpage.user_status, {verified}, {manager_id}::uuid, {role}::frontpage.user_role)
            on conflict ("id")
            do update set
              "email" = EXCLUDED."email",
            "name" = EXCLUDED."name",
            "created_at" = EXCLUDED."created_at",
            "department_id" = EXCLUDED."department_id",
            "status" = EXCLUDED."status",
            "verified" = EXCLUDED."verified",
            "manager_id" = EXCLUDED."manager_id",
            "role" = EXCLUDED."role"
            returning "id", "email", "name", "created_at"::text, "department_id", "status", "verified", "manager_id", "role"
            """,
            toNamedParameter(head),
            rest.map(toNamedParameter)*
          )
        ).executeReturning(UserRow.rowParser(1).*)
    }
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[UserRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    SQL"""create temporary table user_TEMP (like "frontpage"."user") on commit drop""".execute(): @nowarn
    streamingInsert(s"""copy user_TEMP("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role") from stdin""", batchSize, unsaved)(using UserRow.pgText, c): @nowarn
    SQL"""insert into "frontpage"."user"("id", "email", "name", "created_at", "department_id", "status", "verified", "manager_id", "role")
    select * from user_TEMP
    on conflict ("id")
    do update set
      "email" = EXCLUDED."email",
    "name" = EXCLUDED."name",
    "created_at" = EXCLUDED."created_at",
    "department_id" = EXCLUDED."department_id",
    "status" = EXCLUDED."status",
    "verified" = EXCLUDED."verified",
    "manager_id" = EXCLUDED."manager_id",
    "role" = EXCLUDED."role"
    ;
    drop table user_TEMP;""".executeUpdate()
  }
}