/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_stats

import dev.typr.foundations.kotlin.Dialect
import dev.typr.foundations.kotlin.Fragment
import dev.typr.foundations.kotlin.SelectBuilder
import java.sql.Connection
import kotlin.collections.List

class CustomerStatsMVRepoImpl() : CustomerStatsMVRepo {
  override fun select(): SelectBuilder<CustomerStatsMVFields, CustomerStatsMVRow> = SelectBuilder.of("\"CUSTOMER_STATS\"", CustomerStatsMVFields.structure, CustomerStatsMVRow._rowParser, Dialect.DB2)

  override fun selectAll(c: Connection): List<CustomerStatsMVRow> = Fragment.interpolate(Fragment.lit("select \"CUSTOMER_ID\", \"CUSTOMER_NAME\", \"TOTAL_ORDERS\", \"TOTAL_REVENUE\"\nfrom \"CUSTOMER_STATS\"\n")).query(CustomerStatsMVRow._rowParser.all()).runUnchecked(c)
}