/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.foundations.PgType
import dev.typr.foundations.PgTypes
import dev.typr.foundations.dsl.Bijection

/** Domain `showcase.positive_money`
 * Constraint: CHECK ((VALUE >= (0)::numeric))
 */
case class PositiveMoney(@JsonValue value: java.math.BigDecimal)

object PositiveMoney {
  given bijection: Bijection[PositiveMoney, java.math.BigDecimal] = Bijection.apply[PositiveMoney, java.math.BigDecimal](_.value)(PositiveMoney.apply)

  given pgType: PgType[PositiveMoney] = PgTypes.numeric.bimap(PositiveMoney.apply, _.value).renamed(""""showcase"."positive_money"""")

  given pgTypeArray: PgType[Array[PositiveMoney]] = PgTypes.numericArray.bimap(xs => xs.map(PositiveMoney.apply), xs => xs.map(_.value)).renamed(""""showcase"."positive_money"[]""")
}