/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.address;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.PgTypes;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public class AddressRepoImpl implements AddressRepo {
  public DeleteBuilder<AddressFields, AddressRow> delete() {
    return DeleteBuilder.of("frontpage.address", AddressFields.structure());
  };

  public Boolean deleteById(
    AddressId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "frontpage"."address" where "id" = 
      """),
      AddressId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  public Integer deleteByIds(
    AddressId[] ids,
    Connection c
  ) {
    return interpolate(
               typo.runtime.Fragment.lit("""
                  delete
                  from "frontpage"."address"
                  where "id" = ANY("""),
               AddressId.pgTypeArray.encode(ids),
               typo.runtime.Fragment.lit(")")
             )
      .update()
      .runUnchecked(c);
  };

  public AddressRow insert(
    AddressRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."address"("id", "city", "country")
         values ("""),
      AddressId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.city()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.text.encode(unsaved.country()),
      typo.runtime.Fragment.lit("""
         )
         returning "id", "city", "country"
      """)
    )
      .updateReturning(AddressRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public AddressRow insert(
    AddressRowUnsaved unsaved,
    Connection c
  ) {
    List<Literal> columns = new ArrayList<>();;
      List<Fragment> values = new ArrayList<>();;
      columns.add(Fragment.lit("\"city\""));
      values.add(interpolate(
        PgTypes.text.encode(unsaved.city()),
        typo.runtime.Fragment.lit("""
        """)
      ));
      columns.add(Fragment.lit("\"country\""));
      values.add(interpolate(
        PgTypes.text.encode(unsaved.country()),
        typo.runtime.Fragment.lit("""
        """)
      ));
      unsaved.id().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"id\""));
          values.add(interpolate(
            AddressId.pgType.encode(value),
            typo.runtime.Fragment.lit("::uuid")
          ));
        }
      );;
      Fragment q = interpolate(
        typo.runtime.Fragment.lit("""
        insert into "frontpage"."address"(
        """),
        Fragment.comma(columns),
        typo.runtime.Fragment.lit("""
           )
           values ("""),
        Fragment.comma(values),
        typo.runtime.Fragment.lit("""
           )
           returning "id", "city", "country"
        """)
      );;
    return q.updateReturning(AddressRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public Long insertStreaming(
    Iterator<AddressRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."address"("id", "city", "country") FROM STDIN
    """), batchSize, unsaved, c, AddressRow.pgText);
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<AddressRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."address"("city", "country", "id") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')
    """), batchSize, unsaved, c, AddressRowUnsaved.pgText);
  };

  public SelectBuilder<AddressFields, AddressRow> select() {
    return SelectBuilder.of("frontpage.address", AddressFields.structure(), AddressRow._rowParser);
  };

  public List<AddressRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "city", "country"
       from "frontpage"."address"
    """)).as(AddressRow._rowParser.all()).runUnchecked(c);
  };

  public Optional<AddressRow> selectById(
    AddressId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "city", "country"
         from "frontpage"."address"
         where "id" = """),
      AddressId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).as(AddressRow._rowParser.first()).runUnchecked(c);
  };

  public List<AddressRow> selectByIds(
    AddressId[] ids,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "city", "country"
         from "frontpage"."address"
         where "id" = ANY("""),
      AddressId.pgTypeArray.encode(ids),
      typo.runtime.Fragment.lit(")")
    ).as(AddressRow._rowParser.all()).runUnchecked(c);
  };

  public Map<AddressId, AddressRow> selectByIdsTracked(
    AddressId[] ids,
    Connection c
  ) {
    Map<AddressId, AddressRow> ret = new HashMap<>();;
      selectByIds(ids, c).forEach(row -> ret.put(row.id(), row));
    return ret;
  };

  public UpdateBuilder<AddressFields, AddressRow> update() {
    return UpdateBuilder.of("frontpage.address", AddressFields.structure(), AddressRow._rowParser.all());
  };

  public Boolean update(
    AddressRow row,
    Connection c
  ) {
    AddressId id = row.id();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "frontpage"."address"
                set "city" = """),
             PgTypes.text.encode(row.city()),
             typo.runtime.Fragment.lit("""
                ,
                "country" = """),
             PgTypes.text.encode(row.country()),
             typo.runtime.Fragment.lit("""
   
                where "id" = """),
             AddressId.pgType.encode(id),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };

  public AddressRow upsert(
    AddressRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."address"("id", "city", "country")
         values ("""),
      AddressId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.city()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.text.encode(unsaved.country()),
      typo.runtime.Fragment.lit("""
         )
         on conflict ("id")
         do update set
           "city" = EXCLUDED."city",
         "country" = EXCLUDED."country"
         returning "id", "city", "country"
      """)
    )
      .updateReturning(AddressRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  public List<AddressRow> upsertBatch(
    Iterator<AddressRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "frontpage"."address"("id", "city", "country")
                values (?::uuid, ?, ?)
                on conflict ("id")
                do update set
                  "city" = EXCLUDED."city",
                "country" = EXCLUDED."country"
                returning "id", "city", "country"
             """))
      .updateManyReturning(AddressRow._rowParser, unsaved)
      .runUnchecked(c);
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<AddressRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table address_TEMP (like "frontpage"."address") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy address_TEMP("id", "city", "country") from stdin
      """), batchSize, unsaved, c, AddressRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "frontpage"."address"("id", "city", "country")
              select * from address_TEMP
              on conflict ("id")
              do update set
                "city" = EXCLUDED."city",
              "country" = EXCLUDED."country"
              ;
              drop table address_TEMP;""")).update().runUnchecked(c);
  };
}