/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.address;

import com.fasterxml.jackson.annotation.JsonValue;
import frontpage.customtypes.TypoUUID;
import typo.dsl.Bijection;
import typo.runtime.PgType;
import typo.runtime.internal.arrayMap;

/** Type for the primary key of table `frontpage.address` */
public record AddressId(@JsonValue TypoUUID value) {
  public AddressId withValue(TypoUUID value) {
    return new AddressId(value);
  };

  static public Bijection<AddressId, TypoUUID> bijection =
    Bijection.of(AddressId::value, AddressId::new);

  static public PgType<AddressId> pgType =
    TypoUUID.pgType.bimap(AddressId::new, AddressId::value);

  static public PgType<AddressId[]> pgTypeArray =
    TypoUUID.pgTypeArray.bimap(xs -> arrayMap.map(xs, AddressId::new, AddressId.class), xs -> arrayMap.map(xs, AddressId::value, TypoUUID.class));
}