/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.employeepayhistory;

import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.person.businessentity.BusinessentityId;

/** Type for the composite primary key of table `humanresources.employeepayhistory` */
public record EmployeepayhistoryId(
  BusinessentityId businessentityid,
  TypoLocalDateTime ratechangedate
) {
  public EmployeepayhistoryId withBusinessentityid(BusinessentityId businessentityid) {
    return new EmployeepayhistoryId(businessentityid, ratechangedate);
  };

  public EmployeepayhistoryId withRatechangedate(TypoLocalDateTime ratechangedate) {
    return new EmployeepayhistoryId(businessentityid, ratechangedate);
  };
}