/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase;

import com.fasterxml.jackson.annotation.JsonValue;
import dev.typr.foundations.PgType;
import dev.typr.foundations.PgTypes;
import dev.typr.foundations.dsl.Bijection;
import dev.typr.foundations.internal.arrayMap;

/**
 * Domain `showcase.postal_code` Constraint: CHECK (((VALUE)::text ~ '^[A-Z0-9\-\s]{3,20}$'::text))
 */
public record PostalCode(@JsonValue String value) {
  public PostalCode withValue(String value) {
    return new PostalCode(value);
  }
  ;

  public static Bijection<PostalCode, String> bijection =
      Bijection.of(PostalCode::value, PostalCode::new);

  public static PgType<PostalCode> pgType =
      PgTypes.text
          .bimap(PostalCode::new, PostalCode::value)
          .renamed("\"showcase\".\"postal_code\"");

  public static PgType<PostalCode[]> pgTypeArray =
      PgTypes.textArray
          .bimap(
              xs -> arrayMap.map(xs, PostalCode::new, PostalCode.class),
              xs -> arrayMap.map(xs, PostalCode::value, String.class))
          .renamed("\"showcase\".\"postal_code\"[]");
}
