/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.distinct_type_test;

import dev.typr.foundations.dsl.DeleteBuilder;
import dev.typr.foundations.dsl.SelectBuilder;
import dev.typr.foundations.dsl.UpdateBuilder;
import java.sql.Connection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface DistinctTypeTestRepo {
  DeleteBuilder<DistinctTypeTestFields, DistinctTypeTestRow> delete();

  Boolean deleteById(DistinctTypeTestId id, Connection c);

  Integer deleteByIds(DistinctTypeTestId[] ids, Connection c);

  DistinctTypeTestRow insert(DistinctTypeTestRow unsaved, Connection c);

  DistinctTypeTestRow insert(DistinctTypeTestRowUnsaved unsaved, Connection c);

  SelectBuilder<DistinctTypeTestFields, DistinctTypeTestRow> select();

  List<DistinctTypeTestRow> selectAll(Connection c);

  Optional<DistinctTypeTestRow> selectById(DistinctTypeTestId id, Connection c);

  List<DistinctTypeTestRow> selectByIds(DistinctTypeTestId[] ids, Connection c);

  Map<DistinctTypeTestId, DistinctTypeTestRow> selectByIdsTracked(
      DistinctTypeTestId[] ids, Connection c);

  UpdateBuilder<DistinctTypeTestFields, DistinctTypeTestRow> update();

  Boolean update(DistinctTypeTestRow row, Connection c);

  void upsert(DistinctTypeTestRow unsaved, Connection c);

  void upsertBatch(Iterator<DistinctTypeTestRow> unsaved, Connection c);
}
