/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.distinct_type_test;

import com.fasterxml.jackson.annotation.JsonProperty;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.RowParsers;
import java.util.Optional;
import testdb.EmailAddress;
import testdb.MoneyAmount;

/** Table: DISTINCT_TYPE_TEST Primary key: ID */
public record DistinctTypeTestRow(
    /** Identity ALWAYS */
    @JsonProperty("ID") DistinctTypeTestId id,
    @JsonProperty("EMAIL") EmailAddress email,
    @JsonProperty("BALANCE") Optional<MoneyAmount> balance) {
  /** Identity ALWAYS */
  public DistinctTypeTestRow withId(DistinctTypeTestId id) {
    return new DistinctTypeTestRow(id, email, balance);
  }
  ;

  public DistinctTypeTestRow withEmail(EmailAddress email) {
    return new DistinctTypeTestRow(id, email, balance);
  }
  ;

  public DistinctTypeTestRow withBalance(Optional<MoneyAmount> balance) {
    return new DistinctTypeTestRow(id, email, balance);
  }
  ;

  public static RowParser<DistinctTypeTestRow> _rowParser =
      RowParsers.of(
          DistinctTypeTestId.pgType,
          EmailAddress.pgType,
          MoneyAmount.pgType.opt(),
          DistinctTypeTestRow::new,
          row -> new Object[] {row.id(), row.email(), row.balance()});
  ;

  public DistinctTypeTestRowUnsaved toUnsavedRow() {
    return new DistinctTypeTestRowUnsaved(email, balance);
  }
  ;
}
