/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.db2testnull;

import static dev.typr.foundations.Fragment.interpolate;

import dev.typr.foundations.Db2Types;
import dev.typr.foundations.Fragment;
import dev.typr.foundations.dsl.DeleteBuilder;
import dev.typr.foundations.dsl.Dialect;
import dev.typr.foundations.dsl.SelectBuilder;
import dev.typr.foundations.dsl.UpdateBuilder;
import java.sql.Connection;
import java.util.List;

public class Db2testnullRepoImpl implements Db2testnullRepo {
  @Override
  public DeleteBuilder<Db2testnullFields, Db2testnullRow> delete() {
    return DeleteBuilder.of("\"DB2TESTNULL\"", Db2testnullFields.structure, Dialect.DB2);
  }

  @Override
  public Db2testnullRow insert(Db2testnullRow unsaved, Connection c) {
    return interpolate(
            Fragment.lit(
                "SELECT \"SMALLINT_COL\", \"INT_COL\", \"BIGINT_COL\", \"DECIMAL_COL\","
                    + " \"NUMERIC_COL\", \"DECFLOAT16_COL\", \"DECFLOAT34_COL\", \"REAL_COL\","
                    + " \"DOUBLE_COL\", \"BOOL_COL\", \"CHAR_COL\", \"VARCHAR_COL\", \"CLOB_COL\","
                    + " \"GRAPHIC_COL\", \"VARGRAPHIC_COL\", \"BINARY_COL\", \"VARBINARY_COL\","
                    + " \"BLOB_COL\", \"DATE_COL\", \"TIME_COL\", \"TIMESTAMP_COL\","
                    + " \"TIMESTAMP6_COL\", \"TIMESTAMP12_COL\", \"XML_COL\" FROM FINAL TABLE"
                    + " (INSERT INTO \"DB2TESTNULL\"(\"SMALLINT_COL\", \"INT_COL\", \"BIGINT_COL\","
                    + " \"DECIMAL_COL\", \"NUMERIC_COL\", \"DECFLOAT16_COL\", \"DECFLOAT34_COL\","
                    + " \"REAL_COL\", \"DOUBLE_COL\", \"BOOL_COL\", \"CHAR_COL\", \"VARCHAR_COL\","
                    + " \"CLOB_COL\", \"GRAPHIC_COL\", \"VARGRAPHIC_COL\", \"BINARY_COL\","
                    + " \"VARBINARY_COL\", \"BLOB_COL\", \"DATE_COL\", \"TIME_COL\","
                    + " \"TIMESTAMP_COL\", \"TIMESTAMP6_COL\", \"TIMESTAMP12_COL\", \"XML_COL\")\n"
                    + "VALUES ("),
            Fragment.encode(Db2Types.smallint.opt(), unsaved.smallintCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.integer.opt(), unsaved.intCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.bigint.opt(), unsaved.bigintCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.decimal.opt(), unsaved.decimalCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.decimal.opt(), unsaved.numericCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.decfloat.opt(), unsaved.decfloat16Col()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.decfloat.opt(), unsaved.decfloat34Col()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.real.opt(), unsaved.realCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.double_.opt(), unsaved.doubleCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.boolean_.opt(), unsaved.boolCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.char_.opt(), unsaved.charCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.varchar.opt(), unsaved.varcharCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.clob.opt(), unsaved.clobCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.graphic.opt(), unsaved.graphicCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.vargraphic.opt(), unsaved.vargraphicCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.binary.opt(), unsaved.binaryCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.varbinary.opt(), unsaved.varbinaryCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.blob.opt(), unsaved.blobCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.date.opt(), unsaved.dateCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.time.opt(), unsaved.timeCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.timestamp.opt(), unsaved.timestampCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.timestamp.opt(), unsaved.timestamp6Col()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.timestamp.opt(), unsaved.timestamp12Col()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.xml.opt(), unsaved.xmlCol()),
            Fragment.lit("))\n"))
        .updateReturning(Db2testnullRow._rowParser.exactlyOne())
        .runUnchecked(c);
  }

  @Override
  public SelectBuilder<Db2testnullFields, Db2testnullRow> select() {
    return SelectBuilder.of(
        "\"DB2TESTNULL\"", Db2testnullFields.structure, Db2testnullRow._rowParser, Dialect.DB2);
  }

  @Override
  public List<Db2testnullRow> selectAll(Connection c) {
    return interpolate(
            Fragment.lit(
                "select \"SMALLINT_COL\", \"INT_COL\", \"BIGINT_COL\", \"DECIMAL_COL\","
                    + " \"NUMERIC_COL\", \"DECFLOAT16_COL\", \"DECFLOAT34_COL\", \"REAL_COL\","
                    + " \"DOUBLE_COL\", \"BOOL_COL\", \"CHAR_COL\", \"VARCHAR_COL\", \"CLOB_COL\","
                    + " \"GRAPHIC_COL\", \"VARGRAPHIC_COL\", \"BINARY_COL\", \"VARBINARY_COL\","
                    + " \"BLOB_COL\", \"DATE_COL\", \"TIME_COL\", \"TIMESTAMP_COL\","
                    + " \"TIMESTAMP6_COL\", \"TIMESTAMP12_COL\", \"XML_COL\"\n"
                    + "from \"DB2TESTNULL\"\n"))
        .query(Db2testnullRow._rowParser.all())
        .runUnchecked(c);
  }

  @Override
  public UpdateBuilder<Db2testnullFields, Db2testnullRow> update() {
    return UpdateBuilder.of(
        "\"DB2TESTNULL\"", Db2testnullFields.structure, Db2testnullRow._rowParser, Dialect.DB2);
  }
}
