/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.titledperson

import adventureworks.public.title.TitleId
import adventureworks.public.title_domain.TitleDomainId
import doobie.free.connection.ConnectionIO
import doobie.postgres.syntax.FragmentOps
import doobie.syntax.SqlInterpolator.SingleFragment.fromWrite
import doobie.util.Write
import doobie.util.meta.Meta
import fs2.Stream
import org.springframework.stereotype.Repository
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import doobie.syntax.string.toSqlInterpolator

@Repository
class TitledpersonRepoImpl extends TitledpersonRepo {
  def delete: DeleteBuilder[TitledpersonFields, TitledpersonRow] = DeleteBuilder.of(""""public"."titledperson"""", TitledpersonFields.structure, TitledpersonRow.read)

  def insert(unsaved: TitledpersonRow): ConnectionIO[TitledpersonRow] = {
    sql"""insert into "public"."titledperson"("title_short", "title", "name")
    values (${fromWrite(unsaved.titleShort)(using new Write.Single(TitleDomainId.put))}::text, ${fromWrite(unsaved.title)(using new Write.Single(TitleId.put))}, ${fromWrite(unsaved.name)(using new Write.Single(Meta.StringMeta.put))})
    returning "title_short", "title", "name"
    """.query(using TitledpersonRow.read).unique
  }

  def insertStreaming(
    unsaved: Stream[ConnectionIO, TitledpersonRow],
    batchSize: Int = 10000
  ): ConnectionIO[Long] = new FragmentOps(sql"""COPY "public"."titledperson"("title_short", "title", "name") FROM STDIN""").copyIn(unsaved, batchSize)(using TitledpersonRow.pgText)

  def select: SelectBuilder[TitledpersonFields, TitledpersonRow] = SelectBuilder.of(""""public"."titledperson"""", TitledpersonFields.structure, TitledpersonRow.read)

  def selectAll: Stream[ConnectionIO, TitledpersonRow] = sql"""select "title_short", "title", "name" from "public"."titledperson"""".query(using TitledpersonRow.read).stream

  def update: UpdateBuilder[TitledpersonFields, TitledpersonRow] = UpdateBuilder.of(""""public"."titledperson"""", TitledpersonFields.structure, TitledpersonRow.read)
}