/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.brands

import com.fasterxml.jackson.annotation.JsonProperty
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import typo.runtime.MariaText
import typo.runtime.MariaTypes
import typo.scaladsl.MariaTypeOps
import typo.scaladsl.ScalaDbTypes

/** This class corresponds to a row in table `brands` which has not been persisted yet */
case class BrandsRowUnsaved(
  /**  */
  name: String,
  /**  */
  slug: String,
  /** Default: NULL

   */
  @JsonProperty("logo_blob") logoBlob: Defaulted[Option[Array[Byte]]] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("website_url") websiteUrl: Defaulted[Option[String]] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("country_of_origin") countryOfOrigin: Defaulted[Option[String]] = new UseDefault(),
  /** Default: 1

   */
  @JsonProperty("is_active") isActive: Defaulted[Boolean] = new UseDefault()
) {
  def toRow(
    logoBlobDefault: => Option[Array[Byte]],
    websiteUrlDefault: => Option[String],
    countryOfOriginDefault: => Option[String],
    isActiveDefault: => Boolean,
    brandIdDefault: => BrandsId
  ): BrandsRow = {
    new BrandsRow(
      brandId = brandIdDefault,
      name = name,
      slug = slug,
      logoBlob = logoBlob.getOrElse(logoBlobDefault),
      websiteUrl = websiteUrl.getOrElse(websiteUrlDefault),
      countryOfOrigin = countryOfOrigin.getOrElse(countryOfOriginDefault),
      isActive = isActive.getOrElse(isActiveDefault)
    )
  }
}

object BrandsRowUnsaved {
  given mariaText: MariaText[BrandsRowUnsaved] = MariaText.instance((row, sb) => { MariaTypes.varchar.mariaText.unsafeEncode(row.name, sb); sb.append(MariaText.DELIMETER); MariaTypes.varchar.mariaText.unsafeEncode(row.slug, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.mediumblob.nullable.mariaText).unsafeEncode(row.logoBlob, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.varchar.nullable.mariaText).unsafeEncode(row.websiteUrl, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.char_.nullable.mariaText).unsafeEncode(row.countryOfOrigin, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using ScalaDbTypes.MariaTypes.bool.mariaText).unsafeEncode(row.isActive, sb) })
}