/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.salesreason;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.Defaulted.UseDefault;
import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.public_.Name;
import typo.runtime.PgText;

/** This class corresponds to a row in table `sales.salesreason` which has not been persisted yet */
public record SalesreasonRowUnsaved(
  /** Sales reason description. */
  Name name,
  /** Category the sales reason belongs to. */
  Name reasontype,
  /** Default: nextval('sales.salesreason_salesreasonid_seq'::regclass)
    * Primary key for SalesReason records.
    */
  Defaulted<SalesreasonId> salesreasonid,
  /** Default: now() */
  Defaulted<TypoLocalDateTime> modifieddate
) {
  public SalesreasonRowUnsaved(
    /** Sales reason description. */
    Name name,
    /** Category the sales reason belongs to. */
    Name reasontype
  ) {
    this(name, reasontype, new UseDefault<>(), new UseDefault<>());
  };

  /** Sales reason description. */
  public SalesreasonRowUnsaved withName(Name name) {
    return new SalesreasonRowUnsaved(name, reasontype, salesreasonid, modifieddate);
  };

  /** Category the sales reason belongs to. */
  public SalesreasonRowUnsaved withReasontype(Name reasontype) {
    return new SalesreasonRowUnsaved(name, reasontype, salesreasonid, modifieddate);
  };

  /** Default: nextval('sales.salesreason_salesreasonid_seq'::regclass)
    * Primary key for SalesReason records.
    */
  public SalesreasonRowUnsaved withSalesreasonid(Defaulted<SalesreasonId> salesreasonid) {
    return new SalesreasonRowUnsaved(name, reasontype, salesreasonid, modifieddate);
  };

  /** Default: now() */
  public SalesreasonRowUnsaved withModifieddate(Defaulted<TypoLocalDateTime> modifieddate) {
    return new SalesreasonRowUnsaved(name, reasontype, salesreasonid, modifieddate);
  };

  static public PgText<SalesreasonRowUnsaved> pgText =
    PgText.instance((row, sb) -> {
      Name.pgType.pgText().unsafeEncode(row.name, sb);
      sb.append(PgText.DELIMETER);
      Name.pgType.pgText().unsafeEncode(row.reasontype, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(SalesreasonId.pgType.pgText()).unsafeEncode(row.salesreasonid, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoLocalDateTime.pgType.pgText()).unsafeEncode(row.modifieddate, sb);
    });

  public SalesreasonRow toRow(
    java.util.function.Supplier<SalesreasonId> salesreasonidDefault,
    java.util.function.Supplier<TypoLocalDateTime> modifieddateDefault
  ) {
    return new SalesreasonRow(salesreasonid.getOrElse(salesreasonidDefault), name, reasontype, modifieddate.getOrElse(modifieddateDefault));
  };
}