/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.department

import frontpage.Text
import frontpage.customtypes.Defaulted
import frontpage.customtypes.Defaulted.UseDefault
import frontpage.frontpage.company.CompanyId
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** This class corresponds to a row in table `frontpage.department` which has not been persisted yet */
case class DepartmentRowUnsaved(
  name: String,
  budget: Option[BigDecimal] = None,
  /** Points to [[frontpage.frontpage.company.CompanyRow.id]] */
  companyId: Option[CompanyId] = None,
  /** Default: gen_random_uuid() */
  id: Defaulted[DepartmentId] = new UseDefault()
) {
  def toRow(idDefault: => DepartmentId): DepartmentRow = {
    new DepartmentRow(
      id = id.getOrElse(idDefault),
      name = name,
      budget = budget,
      companyId = companyId
    )
  }
}

object DepartmentRowUnsaved {
  given pgText: Text[DepartmentRowUnsaved] = {
    Text.instance[DepartmentRowUnsaved]{ (row, sb) =>
      Text.stringInstance.unsafeEncode(row.name, sb)
      sb.append(Text.DELIMETER)
      Text.option(using Text.bigDecimalInstance).unsafeEncode(row.budget, sb)
      sb.append(Text.DELIMETER)
      Text.option(using CompanyId.pgText).unsafeEncode(row.companyId, sb)
      sb.append(Text.DELIMETER)
      Defaulted.pgText(using DepartmentId.pgText).unsafeEncode(row.id, sb)
    }
  }

  given reads: Reads[DepartmentRowUnsaved] = {
    Reads[DepartmentRowUnsaved](json => JsResult.fromTry(
        Try(
          DepartmentRowUnsaved(
            name = json.\("name").as(Reads.StringReads),
            budget = json.\("budget").toOption.map(_.as(Reads.bigDecReads)),
            companyId = json.\("company_id").toOption.map(_.as(CompanyId.reads)),
            id = json.\("id").as(Defaulted.reads(using DepartmentId.reads))
          )
        )
      ),
    )
  }

  given writes: OWrites[DepartmentRowUnsaved] = {
    OWrites[DepartmentRowUnsaved](o =>
      new JsObject(ListMap[String, JsValue](
        "name" -> Writes.StringWrites.writes(o.name),
        "budget" -> Writes.OptionWrites(using Writes.BigDecimalWrites).writes(o.budget),
        "company_id" -> Writes.OptionWrites(using CompanyId.writes).writes(o.companyId),
        "id" -> Defaulted.writes(using DepartmentId.writes).writes(o.id)
      ))
    )
  }
}