/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.role

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import frontpage.Text
import frontpage.customtypes.TypoUUID
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typo.dsl.Bijection

/** Type for the primary key of table `frontpage.role` */
case class RoleId(value: TypoUUID) extends scala.AnyVal

object RoleId {
  given arrayColumn: Column[Array[RoleId]] = Column.columnToArray(using column, implicitly)

  given arrayToStatement: ToStatement[Array[RoleId]] = TypoUUID.arrayToStatement.contramap(_.map(_.value))

  given bijection: Bijection[RoleId, TypoUUID] = Bijection.apply[RoleId, TypoUUID](_.value)(RoleId.apply)

  given column: Column[RoleId] = TypoUUID.column.map(RoleId.apply)

  given parameterMetadata: ParameterMetaData[RoleId] = {
    new ParameterMetaData[RoleId] {
      override def sqlType: String = TypoUUID.parameterMetadata.sqlType
      override def jdbcType: Int = TypoUUID.parameterMetadata.jdbcType
    }
  }

  given pgText: Text[RoleId] = {
    new Text[RoleId] {
      override def unsafeEncode(v: RoleId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: RoleId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeArrayEncode(v.value, sb)
    }
  }

  given reads: Reads[RoleId] = TypoUUID.reads.map(RoleId.apply)

  given toStatement: ToStatement[RoleId] = TypoUUID.toStatement.contramap(_.value)

  given writes: Writes[RoleId] = TypoUUID.writes.contramap(_.value)
}