/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.role

import java.sql.Connection
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder

trait RoleRepo {
  def delete: DeleteBuilder[RoleFields, RoleRow]

  def deleteById(id: RoleId)(using c: Connection): Boolean

  def deleteByIds(ids: Array[RoleId])(using c: Connection): Int

  def insert(unsaved: RoleRow)(using c: Connection): RoleRow

  def insert(unsaved: RoleRowUnsaved)(using c: Connection): RoleRow

  def insertStreaming(
    unsaved: Iterator[RoleRow],
    batchSize: Int = 10000
  )(using c: Connection): Long

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[RoleRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long

  def select: SelectBuilder[RoleFields, RoleRow]

  def selectAll(using c: Connection): List[RoleRow]

  def selectById(id: RoleId)(using c: Connection): Option[RoleRow]

  def selectByIds(ids: Array[RoleId])(using c: Connection): List[RoleRow]

  def selectByIdsTracked(ids: Array[RoleId])(using c: Connection): Map[RoleId, RoleRow]

  def selectByUniqueName(name: String)(using c: Connection): Option[RoleRow]

  def update: UpdateBuilder[RoleFields, RoleRow]

  def update(row: RoleRow)(using c: Connection): Option[RoleRow]

  def upsert(unsaved: RoleRow)(using c: Connection): RoleRow

  def upsertBatch(unsaved: Iterable[RoleRow])(using c: Connection): List[RoleRow]

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[RoleRow],
    batchSize: Int = 10000
  )(using c: Connection): Int
}