/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.test_utdanningstilbud

import adventureworks.public.test_organisasjon.TestOrganisasjonId
import typo.runtime.PgText
import typo.runtime.PgTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers
import typo.runtime.RowParsers.Tuple2

/** Table: public.test_utdanningstilbud
 * Composite primary key: organisasjonskode, utdanningsmulighet_kode
 */
case class TestUtdanningstilbudRow(
  /** Points to [[adventureworks.public.test_organisasjon.TestOrganisasjonRow.organisasjonskode]] */
  organisasjonskode: TestOrganisasjonId,
  utdanningsmulighetKode: String
) {
  def compositeId: TestUtdanningstilbudId = new TestUtdanningstilbudId(organisasjonskode, utdanningsmulighetKode)

  def id: TestUtdanningstilbudId = this.compositeId
}

object TestUtdanningstilbudRow {
  val `_rowParser`: RowParser[TestUtdanningstilbudRow] = RowParsers.of(TestOrganisasjonId.pgType, PgTypes.text, TestUtdanningstilbudRow.apply, row => new Tuple2(row.organisasjonskode, row.utdanningsmulighetKode))

  def apply(compositeId: TestUtdanningstilbudId): TestUtdanningstilbudRow = new TestUtdanningstilbudRow(compositeId.organisasjonskode, compositeId.utdanningsmulighetKode)

  given pgText: PgText[TestUtdanningstilbudRow] = PgText.from(`_rowParser`)
}