/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.store;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.Defaulted.UseDefault;
import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.customtypes.TypoUUID;
import adventureworks.customtypes.TypoXml;
import adventureworks.person.businessentity.BusinessentityId;
import adventureworks.public_.Name;
import java.util.Optional;
import typo.runtime.PgText;

/** This class corresponds to a row in table `sales.store` which has not been persisted yet */
public record StoreRowUnsaved(
  /** Primary key. Foreign key to Customer.BusinessEntityID.
    * Points to {@link adventureworks.person.businessentity.BusinessentityRow#businessentityid()}
    */
  BusinessentityId businessentityid,
  /** Name of the store. */
  Name name,
  /** ID of the sales person assigned to the customer. Foreign key to SalesPerson.BusinessEntityID.
    * Points to {@link adventureworks.sales.salesperson.SalespersonRow#businessentityid()}
    */
  Optional<BusinessentityId> salespersonid,
  /** Demographic informationg about the store such as the number of employees, annual sales and store type. */
  Optional<TypoXml> demographics,
  /** Default: uuid_generate_v1() */
  Defaulted<TypoUUID> rowguid,
  /** Default: now() */
  Defaulted<TypoLocalDateTime> modifieddate
) {
  public StoreRowUnsaved(
    /** Primary key. Foreign key to Customer.BusinessEntityID.
      * Points to {@link adventureworks.person.businessentity.BusinessentityRow#businessentityid()}
      */
    BusinessentityId businessentityid,
    /** Name of the store. */
    Name name
  ) {
    this(businessentityid, name, Optional.empty(), Optional.empty(), new UseDefault<>(), new UseDefault<>());
  };

  /** Primary key. Foreign key to Customer.BusinessEntityID.
    * Points to {@link adventureworks.person.businessentity.BusinessentityRow#businessentityid()}
    */
  public StoreRowUnsaved withBusinessentityid(BusinessentityId businessentityid) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  /** Name of the store. */
  public StoreRowUnsaved withName(Name name) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  /** ID of the sales person assigned to the customer. Foreign key to SalesPerson.BusinessEntityID.
    * Points to {@link adventureworks.sales.salesperson.SalespersonRow#businessentityid()}
    */
  public StoreRowUnsaved withSalespersonid(Optional<BusinessentityId> salespersonid) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  /** Demographic informationg about the store such as the number of employees, annual sales and store type. */
  public StoreRowUnsaved withDemographics(Optional<TypoXml> demographics) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  /** Default: uuid_generate_v1() */
  public StoreRowUnsaved withRowguid(Defaulted<TypoUUID> rowguid) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  /** Default: now() */
  public StoreRowUnsaved withModifieddate(Defaulted<TypoLocalDateTime> modifieddate) {
    return new StoreRowUnsaved(businessentityid, name, salespersonid, demographics, rowguid, modifieddate);
  };

  static public PgText<StoreRowUnsaved> pgText =
    PgText.instance((row, sb) -> {
      BusinessentityId.pgType.pgText().unsafeEncode(row.businessentityid, sb);
      sb.append(PgText.DELIMETER);
      Name.pgType.pgText().unsafeEncode(row.name, sb);
      sb.append(PgText.DELIMETER);
      BusinessentityId.pgType.opt().pgText().unsafeEncode(row.salespersonid, sb);
      sb.append(PgText.DELIMETER);
      TypoXml.pgType.opt().pgText().unsafeEncode(row.demographics, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoUUID.pgType.pgText()).unsafeEncode(row.rowguid, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoLocalDateTime.pgType.pgText()).unsafeEncode(row.modifieddate, sb);
    });

  public StoreRow toRow(
    java.util.function.Supplier<TypoUUID> rowguidDefault,
    java.util.function.Supplier<TypoLocalDateTime> modifieddateDefault
  ) {
    return new StoreRow(businessentityid, name, salespersonid, demographics, rowguid.getOrElse(rowguidDefault), modifieddate.getOrElse(modifieddateDefault));
  };
}