/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.pmi

import doobie.free.connection.ConnectionIO
import fs2.Stream
import org.springframework.stereotype.Repository
import typo.dsl.SelectBuilder
import doobie.syntax.string.toSqlInterpolator

@Repository
class PmiViewRepoImpl extends PmiViewRepo {
  def select: SelectBuilder[PmiViewFields, PmiViewRow] = SelectBuilder.of(""""pr"."pmi"""", PmiViewFields.structure, PmiViewRow.read)

  def selectAll: Stream[ConnectionIO, PmiViewRow] = sql"""select "productmodelid", "illustrationid", "modifieddate"::text from "pr"."pmi"""".query(using PmiViewRow.read).stream
}