/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.product

import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class ProductRepoMock(
  toRow: ProductRowUnsaved => ProductRow,
  map: scala.collection.mutable.Map[ProductId, ProductRow] = scala.collection.mutable.Map.empty[ProductId, ProductRow]
) extends ProductRepo {
  def delete: DeleteBuilder[ProductFields, ProductRow] = DeleteBuilderMock(DeleteParams.empty, ProductFields.structure, map)

  def deleteById(id: ProductId)(using c: Connection): Boolean = map.remove(id).isDefined

  def deleteByIds(ids: Array[ProductId])(using c: Connection): Int = ids.map(id => map.remove(id)).count(_.isDefined)

  def insert(unsaved: ProductRow)(using c: Connection): ProductRow = {
    val _ = if (map.contains(unsaved.id))
      sys.error(s"id ${unsaved.id} already exists")
    else
      map.put(unsaved.id, unsaved)
  
    unsaved
  }

  def insert(unsaved: ProductRowUnsaved)(using c: Connection): ProductRow = insert(toRow(unsaved))

  def insertStreaming(
    unsaved: Iterator[ProductRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { row =>
      map += (row.id -> row)
    }
    unsaved.size.toLong
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[ProductRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { unsavedRow =>
      val row = toRow(unsavedRow)
      map += (row.id -> row)
    }
    unsaved.size.toLong
  }

  def select: SelectBuilder[ProductFields, ProductRow] = SelectBuilderMock(ProductFields.structure, () => map.values.toList, SelectParams.empty)

  def selectAll(using c: Connection): List[ProductRow] = map.values.toList

  def selectById(id: ProductId)(using c: Connection): Option[ProductRow] = map.get(id)

  def selectByIds(ids: Array[ProductId])(using c: Connection): List[ProductRow] = ids.flatMap(map.get).toList

  def selectByIdsTracked(ids: Array[ProductId])(using c: Connection): Map[ProductId, ProductRow] = {
    val byId = selectByIds(ids).view.map(x => (x.id, x)).toMap
    ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def update: UpdateBuilder[ProductFields, ProductRow] = UpdateBuilderMock(UpdateParams.empty, ProductFields.structure, map)

  def update(row: ProductRow)(using c: Connection): Option[ProductRow] = {
    map.get(row.id).map { _ =>
      map.put(row.id, row): @nowarn
      row
    }
  }

  def upsert(unsaved: ProductRow)(using c: Connection): ProductRow = {
    map.put(unsaved.id, unsaved): @nowarn
    unsaved
  }

  def upsertBatch(unsaved: Iterable[ProductRow])(using c: Connection): List[ProductRow] = {
    unsaved.map { row =>
      map += (row.id -> row)
      row
    }.toList
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[ProductRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    unsaved.foreach { row =>
      map += (row.id -> row)
    }
    unsaved.size
  }
}