/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.sth

import java.sql.Connection
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.interpolate

class SthViewRepoImpl extends SthViewRepo {
  override def select: SelectBuilder[SthViewFields, SthViewRow] = SelectBuilder.of(""""sa"."sth"""", SthViewFields.structure, SthViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): java.util.List[SthViewRow] = {
    interpolate(Fragment.lit("""select "id", "businessentityid", "territoryid", "startdate", "enddate", "rowguid", "modifieddate"
    from "sa"."sth"
    """)).query(SthViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}