/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.pp

import typo.dsl.SelectBuilder
import zio.jdbc.ZConnection
import zio.stream.ZStream
import zio.jdbc.sqlInterpolator

class PpViewRepoImpl extends PpViewRepo {
  def select: SelectBuilder[PpViewFields, PpViewRow] = SelectBuilder.of(""""pr"."pp"""", PpViewFields.structure, PpViewRow.jdbcDecoder)

  def selectAll: ZStream[ZConnection, Throwable, PpViewRow] = sql"""select "id", "productphotoid", "thumbnailphoto", "thumbnailphotofilename", "largephoto", "largephotofilename", "modifieddate"::text from "pr"."pp"""".query(using PpViewRow.jdbcDecoder).selectStream()
}