/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.db2test_identity_always;

import dev.typr.foundations.Db2Types;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.dsl.FieldsExpr;
import dev.typr.foundations.dsl.Path;
import dev.typr.foundations.dsl.RelationStructure;
import dev.typr.foundations.dsl.SqlExpr.Field;
import dev.typr.foundations.dsl.SqlExpr.FieldLike;
import dev.typr.foundations.dsl.SqlExpr.IdField;
import java.util.List;
import java.util.Optional;

public interface Db2testIdentityAlwaysFields extends FieldsExpr<Db2testIdentityAlwaysRow> {
  record Impl(List<Path> _path)
      implements Db2testIdentityAlwaysFields,
          RelationStructure<Db2testIdentityAlwaysFields, Db2testIdentityAlwaysRow> {
    @Override
    public IdField<Db2testIdentityAlwaysId, Db2testIdentityAlwaysRow> id() {
      return new IdField<Db2testIdentityAlwaysId, Db2testIdentityAlwaysRow>(
          _path,
          "ID",
          Db2testIdentityAlwaysRow::id,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withId(value),
          Db2testIdentityAlwaysId.pgType);
    }
    ;

    @Override
    public Field<String, Db2testIdentityAlwaysRow> name() {
      return new Field<String, Db2testIdentityAlwaysRow>(
          _path,
          "NAME",
          Db2testIdentityAlwaysRow::name,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withName(value),
          Db2Types.varchar);
    }
    ;

    @Override
    public List<FieldLike<?, Db2testIdentityAlwaysRow>> columns() {
      return java.util.List.of(this.id(), this.name());
    }
    ;

    @Override
    public RelationStructure<Db2testIdentityAlwaysFields, Db2testIdentityAlwaysRow> withPaths(
        List<Path> _path) {
      return new Impl(_path);
    }
    ;
  }
  ;

  static Impl structure() {
    return new Impl(java.util.Collections.emptyList());
  }
  ;

  IdField<Db2testIdentityAlwaysId, Db2testIdentityAlwaysRow> id();

  Field<String, Db2testIdentityAlwaysRow> name();

  @Override
  List<FieldLike<?, Db2testIdentityAlwaysRow>> columns();

  @Override
  default RowParser<Db2testIdentityAlwaysRow> rowParser() {
    return Db2testIdentityAlwaysRow._rowParser;
  }
  ;
}
