/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.sci

import java.sql.Connection
import typo.dsl.SelectBuilder
import typo.runtime.FragmentInterpolator.interpolate

class SciViewRepoImpl extends SciViewRepo {
  def select: SelectBuilder[SciViewFields, SciViewRow] = SelectBuilder.of("sa.sci", SciViewFields.structure, SciViewRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[SciViewRow] = {
    interpolate"""select "id", "shoppingcartitemid", "shoppingcartid", "quantity", "productid", "datecreated"::text, "modifieddate"::text
    from "sa"."sci"
    """.as(SciViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}