/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.soh

import java.sql.Connection
import typo.dsl.SelectBuilder
import typo.runtime.FragmentInterpolator.interpolate

class SohViewRepoImpl extends SohViewRepo {
  def select: SelectBuilder[SohViewFields, SohViewRow] = SelectBuilder.of("sa.soh", SohViewFields.structure, SohViewRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[SohViewRow] = {
    interpolate"""select "id", "salesorderid", "revisionnumber", "orderdate"::text, "duedate"::text, "shipdate"::text, "status", "onlineorderflag", "purchaseordernumber", "accountnumber", "customerid", "salespersonid", "territoryid", "billtoaddressid", "shiptoaddressid", "shipmethodid", "creditcardid", "creditcardapprovalcode", "currencyrateid", "subtotal", "taxamt", "freight", "totaldue", "comment", "rowguid", "modifieddate"::text
    from "sa"."soh"
    """.as(SohViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}