/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.db2testnull

import dev.typr.foundations.scala.DeleteBuilder
import dev.typr.foundations.scala.SelectBuilder
import dev.typr.foundations.scala.UpdateBuilder
import java.sql.Connection

trait Db2testnullRepo {
  def delete: DeleteBuilder[Db2testnullFields, Db2testnullRow]

  def insert(unsaved: Db2testnullRow)(using c: Connection): Db2testnullRow

  def select: SelectBuilder[Db2testnullFields, Db2testnullRow]

  def selectAll(using c: Connection): List[Db2testnullRow]

  def update: UpdateBuilder[Db2testnullFields, Db2testnullRow]
}