/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders_by_customer;

import static dev.typr.foundations.Fragment.interpolate;

import dev.typr.foundations.Db2Types;
import dev.typr.foundations.Fragment;
import java.sql.Connection;
import java.util.List;

public class OrdersByCustomerSqlRepoImpl implements OrdersByCustomerSqlRepo {
  @Override
  public List<OrdersByCustomerSqlRow> apply(Integer customerId, Connection c) {
    return interpolate(
            Fragment.lit(
                "-- Orders by customer with order items\n"
                    + "SELECT o.order_id, o.order_date, o.total_amount, o.status,\n"
                    + "       i.item_number, i.product_name, i.quantity, i.unit_price\n"
                    + "FROM orders o\n"
                    + "INNER JOIN order_items i ON o.order_id = i.order_id\n"
                    + "WHERE o.customer_id = "),
            Fragment.encode(Db2Types.integer, customerId),
            Fragment.lit("\nORDER BY o.order_date DESC, i.item_number\n"))
        .query(OrdersByCustomerSqlRow._rowParser.all())
        .runUnchecked(c);
  }
  ;
}
