/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.title

import typo.dsl.FieldsExpr0
import typo.dsl.Path
import typo.dsl.SqlExpr.FieldLike
import typo.runtime.RowParser
import typo.scaladsl.RelationStructure
import typo.scaladsl.SqlExpr.IdField

trait TitleFields extends FieldsExpr0[TitleRow] {
  def code: IdField[TitleId, TitleRow]

  override def columns: java.util.List[FieldLike[?, TitleRow]]

  override def rowParser: RowParser[TitleRow] = TitleRow._rowParser.underlying
}

object TitleFields {
  case class Impl(val `_path`: java.util.List[Path]) extends TitleFields with RelationStructure[TitleFields, TitleRow] {

    override def code: IdField[TitleId, TitleRow] = {
      new IdField[TitleId, TitleRow](
        _path,
        "code",
        _.code,
        None,
        None,
        (row, value) => row.copy(code = value),
        TitleId.pgType
      )
    }

    override def columns: java.util.List[FieldLike[?, TitleRow]] = java.util.List.of(this.code.underlying)

    override def withPaths(`_path`: java.util.List[Path]): RelationStructure[TitleFields, TitleRow] = new Impl(`_path`)
  }

  def structure: Impl = new Impl(java.util.Collections.emptyList())
}