/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.mariatest_unique

import dev.typr.foundations.MariaTypes
import dev.typr.foundations.Tuple.Tuple4
import dev.typr.foundations.kotlin.RowParser
import dev.typr.foundations.kotlin.RowParsers

/** Table: mariatest_unique
  * Primary key: id
  */
data class MariatestUniqueRow(
  /** 
    * AUTO_INCREMENT
    */
  val id: MariatestUniqueId,
  /**  */
  val email: String,
  /**  */
  val code: String,
  /**  */
  val category: String
) : Tuple4<MariatestUniqueId, String, String, String> {
  override fun _1(): MariatestUniqueId = id

  override fun _2(): String = email

  override fun _3(): String = code

  override fun _4(): String = category

  fun toUnsavedRow(): MariatestUniqueRowUnsaved = MariatestUniqueRowUnsaved(email, code, category)

  companion object {
    val _rowParser: RowParser<MariatestUniqueRow> = RowParsers.of(MariatestUniqueId.dbType, MariaTypes.varchar, MariaTypes.varchar, MariaTypes.varchar, { t0, t1, t2, t3 -> MariatestUniqueRow(t0, t1, t2, t3) }, { row -> arrayOf<Any?>(row.id, row.email, row.code, row.category) })
  }
}