/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.productinventory;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.Defaulted.UseDefault;
import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.customtypes.TypoShort;
import adventureworks.customtypes.TypoUUID;
import adventureworks.production.location.LocationId;
import adventureworks.production.product.ProductId;
import typo.runtime.PgText;
import typo.runtime.PgTypes;

/** This class corresponds to a row in table `production.productinventory` which has not been persisted yet */
public record ProductinventoryRowUnsaved(
  /** Product identification number. Foreign key to Product.ProductID.
    * Points to {@link adventureworks.production.product.ProductRow#productid()}
    */
  ProductId productid,
  /** Inventory location identification number. Foreign key to Location.LocationID.
    * Points to {@link adventureworks.production.location.LocationRow#locationid()}
    */
  LocationId locationid,
  /** Storage compartment within an inventory location. */
  /* max 10 chars */ String shelf,
  /** Storage container on a shelf in an inventory location.
    * Constraint CK_ProductInventory_Bin affecting columns bin:  (((bin >= 0) AND (bin <= 100)))
    */
  TypoShort bin,
  /** Default: 0
    * Quantity of products in the inventory location.
    */
  Defaulted<TypoShort> quantity,
  /** Default: uuid_generate_v1() */
  Defaulted<TypoUUID> rowguid,
  /** Default: now() */
  Defaulted<TypoLocalDateTime> modifieddate
) {
  public ProductinventoryRowUnsaved(
    /** Product identification number. Foreign key to Product.ProductID.
      * Points to {@link adventureworks.production.product.ProductRow#productid()}
      */
    ProductId productid,
    /** Inventory location identification number. Foreign key to Location.LocationID.
      * Points to {@link adventureworks.production.location.LocationRow#locationid()}
      */
    LocationId locationid,
    /** Storage compartment within an inventory location. */
    /* max 10 chars */ String shelf,
    /** Storage container on a shelf in an inventory location.
      * Constraint CK_ProductInventory_Bin affecting columns bin:  (((bin >= 0) AND (bin <= 100)))
      */
    TypoShort bin
  ) {
    this(productid, locationid, shelf, bin, new UseDefault<>(), new UseDefault<>(), new UseDefault<>());
  };

  /** Product identification number. Foreign key to Product.ProductID.
    * Points to {@link adventureworks.production.product.ProductRow#productid()}
    */
  public ProductinventoryRowUnsaved withProductid(ProductId productid) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Inventory location identification number. Foreign key to Location.LocationID.
    * Points to {@link adventureworks.production.location.LocationRow#locationid()}
    */
  public ProductinventoryRowUnsaved withLocationid(LocationId locationid) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Storage compartment within an inventory location. */
  public ProductinventoryRowUnsaved withShelf(/* max 10 chars */ String shelf) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Storage container on a shelf in an inventory location.
    * Constraint CK_ProductInventory_Bin affecting columns bin:  (((bin >= 0) AND (bin <= 100)))
    */
  public ProductinventoryRowUnsaved withBin(TypoShort bin) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Default: 0
    * Quantity of products in the inventory location.
    */
  public ProductinventoryRowUnsaved withQuantity(Defaulted<TypoShort> quantity) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Default: uuid_generate_v1() */
  public ProductinventoryRowUnsaved withRowguid(Defaulted<TypoUUID> rowguid) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  /** Default: now() */
  public ProductinventoryRowUnsaved withModifieddate(Defaulted<TypoLocalDateTime> modifieddate) {
    return new ProductinventoryRowUnsaved(productid, locationid, shelf, bin, quantity, rowguid, modifieddate);
  };

  static public PgText<ProductinventoryRowUnsaved> pgText =
    PgText.instance((row, sb) -> {
      ProductId.pgType.pgText().unsafeEncode(row.productid, sb);
      sb.append(PgText.DELIMETER);
      LocationId.pgType.pgText().unsafeEncode(row.locationid, sb);
      sb.append(PgText.DELIMETER);
      PgTypes.text.pgText().unsafeEncode(row.shelf, sb);
      sb.append(PgText.DELIMETER);
      TypoShort.pgType.pgText().unsafeEncode(row.bin, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoShort.pgType.pgText()).unsafeEncode(row.quantity, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoUUID.pgType.pgText()).unsafeEncode(row.rowguid, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoLocalDateTime.pgType.pgText()).unsafeEncode(row.modifieddate, sb);
    });

  public ProductinventoryRow toRow(
    java.util.function.Supplier<TypoShort> quantityDefault,
    java.util.function.Supplier<TypoUUID> rowguidDefault,
    java.util.function.Supplier<TypoLocalDateTime> modifieddateDefault
  ) {
    return new ProductinventoryRow(productid, locationid, shelf, bin, quantity.getOrElse(quantityDefault), rowguid.getOrElse(rowguidDefault), modifieddate.getOrElse(modifieddateDefault));
  };
}