/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.permission

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import frontpage.Text
import frontpage.customtypes.TypoUUID
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typo.dsl.Bijection

/** Type for the primary key of table `frontpage.permission` */
case class PermissionId(value: TypoUUID) extends scala.AnyVal

object PermissionId {
  given arrayColumn: Column[Array[PermissionId]] = Column.columnToArray(using column, implicitly)

  given arrayToStatement: ToStatement[Array[PermissionId]] = TypoUUID.arrayToStatement.contramap(_.map(_.value))

  given bijection: Bijection[PermissionId, TypoUUID] = Bijection.apply[PermissionId, TypoUUID](_.value)(PermissionId.apply)

  given column: Column[PermissionId] = TypoUUID.column.map(PermissionId.apply)

  given parameterMetadata: ParameterMetaData[PermissionId] = {
    new ParameterMetaData[PermissionId] {
      override def sqlType: String = TypoUUID.parameterMetadata.sqlType
      override def jdbcType: Int = TypoUUID.parameterMetadata.jdbcType
    }
  }

  given pgText: Text[PermissionId] = {
    new Text[PermissionId] {
      override def unsafeEncode(v: PermissionId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: PermissionId, sb: StringBuilder): Unit = TypoUUID.pgText.unsafeArrayEncode(v.value, sb)
    }
  }

  given reads: Reads[PermissionId] = TypoUUID.reads.map(PermissionId.apply)

  given toStatement: ToStatement[PermissionId] = TypoUUID.toStatement.contramap(_.value)

  given writes: Writes[PermissionId] = TypoUUID.writes.contramap(_.value)
}