/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage

import frontpage.frontpage.Email
import scala.util.Random

/** Methods to generate random data for domain types */
trait TestDomainInsert {
  /** Domain `frontpage.email`
   * Constraint: CHECK ((VALUE ~ '^[^@]+@[^@]+\.[^@]+$'::text))
   */
  def frontpageEmail(random: Random): Email
}