/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.creditcard

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoShort
import adventureworks.userdefined.CustomCreditcardId
import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.PgTypes
import typo.runtime.streamingInsert
import typo.runtime.FragmentInterpolator.interpolate

class CreditcardRepoImpl extends CreditcardRepo {
  def delete: DeleteBuilder[CreditcardFields, CreditcardRow] = DeleteBuilder.of("sales.creditcard", CreditcardFields.structure)

  def deleteById(creditcardid: /* user-picked */ CustomCreditcardId)(using c: Connection): java.lang.Boolean = interpolate"""delete from "sales"."creditcard" where "creditcardid" = ${/* user-picked */ CustomCreditcardId.pgType.encode(creditcardid)}""".update().runUnchecked(c) > 0

  def deleteByIds(creditcardids: Array[/* user-picked */ CustomCreditcardId])(using c: Connection): Integer = {
    interpolate"""delete
    from "sales"."creditcard"
    where "creditcardid" = ANY(${CustomCreditcardId.pgTypeArray.encode(creditcardids)})"""
      .update()
      .runUnchecked(c)
  }

  def insert(unsaved: CreditcardRow)(using c: Connection): CreditcardRow = {
  interpolate"""insert into "sales"."creditcard"("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate")
    values (${/* user-picked */ CustomCreditcardId.pgType.encode(unsaved.creditcardid)}::int4, ${PgTypes.text.encode(unsaved.cardtype)}, ${PgTypes.text.encode(unsaved.cardnumber)}, ${TypoShort.pgType.encode(unsaved.expmonth)}::int2, ${TypoShort.pgType.encode(unsaved.expyear)}::int2, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    returning "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    """
    .updateReturning(CreditcardRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insert(unsaved: CreditcardRowUnsaved)(using c: Connection): CreditcardRow = {
    val columns: java.util.List[Literal] = new ArrayList()
    val values: java.util.List[Fragment] = new ArrayList()
    columns.add(Fragment.lit(""""cardtype"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.text.encode(unsaved.cardtype)}"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""cardnumber"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.text.encode(unsaved.cardnumber)}"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""expmonth"""")): @scala.annotation.nowarn
    values.add(interpolate"${TypoShort.pgType.encode(unsaved.expmonth)}::int2"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""expyear"""")): @scala.annotation.nowarn
    values.add(interpolate"${TypoShort.pgType.encode(unsaved.expyear)}::int2"): @scala.annotation.nowarn
    unsaved.creditcardid.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""creditcardid"""")): @scala.annotation.nowarn;
        values.add(interpolate"${/* user-picked */ CustomCreditcardId.pgType.encode(value)}::int4"): @scala.annotation.nowarn;
      }
    );
    unsaved.modifieddate.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""modifieddate"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TypoLocalDateTime.pgType.encode(value)}::timestamp"): @scala.annotation.nowarn;
      }
    );
    val q: Fragment = {
      interpolate"""insert into "sales"."creditcard"(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
      """
    }
    q.updateReturning(CreditcardRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insertStreaming(
    unsaved: java.util.Iterator[CreditcardRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "sales"."creditcard"("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate") FROM STDIN""", batchSize, unsaved, c, CreditcardRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[CreditcardRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "sales"."creditcard"("cardtype", "cardnumber", "expmonth", "expyear", "creditcardid", "modifieddate") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved, c, CreditcardRowUnsaved.pgText)

  def select: SelectBuilder[CreditcardFields, CreditcardRow] = SelectBuilder.of("sales.creditcard", CreditcardFields.structure, CreditcardRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[CreditcardRow] = {
    interpolate"""select "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    from "sales"."creditcard"
    """.as(CreditcardRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectById(creditcardid: /* user-picked */ CustomCreditcardId)(using c: Connection): Optional[CreditcardRow] = {
    interpolate"""select "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    from "sales"."creditcard"
    where "creditcardid" = ${/* user-picked */ CustomCreditcardId.pgType.encode(creditcardid)}""".as(CreditcardRow.`_rowParser`.first()).runUnchecked(c)
  }

  def selectByIds(creditcardids: Array[/* user-picked */ CustomCreditcardId])(using c: Connection): java.util.List[CreditcardRow] = {
    interpolate"""select "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    from "sales"."creditcard"
    where "creditcardid" = ANY(${CustomCreditcardId.pgTypeArray.encode(creditcardids)})""".as(CreditcardRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectByIdsTracked(creditcardids: Array[/* user-picked */ CustomCreditcardId])(using c: Connection): java.util.Map[/* user-picked */ CustomCreditcardId, CreditcardRow] = {
    val ret: java.util.Map[/* user-picked */ CustomCreditcardId, CreditcardRow] = new HashMap()
    selectByIds(creditcardids)(using c).forEach(row => ret.put(row.creditcardid, row): @scala.annotation.nowarn)
    ret
  }

  def update: UpdateBuilder[CreditcardFields, CreditcardRow] = UpdateBuilder.of("sales.creditcard", CreditcardFields.structure, CreditcardRow.`_rowParser`.all())

  def update(row: CreditcardRow)(using c: Connection): java.lang.Boolean = {
    val creditcardid: /* user-picked */ CustomCreditcardId = row.creditcardid
    interpolate"""update "sales"."creditcard"
    set "cardtype" = ${PgTypes.text.encode(row.cardtype)},
    "cardnumber" = ${PgTypes.text.encode(row.cardnumber)},
    "expmonth" = ${TypoShort.pgType.encode(row.expmonth)}::int2,
    "expyear" = ${TypoShort.pgType.encode(row.expyear)}::int2,
    "modifieddate" = ${TypoLocalDateTime.pgType.encode(row.modifieddate)}::timestamp
    where "creditcardid" = ${/* user-picked */ CustomCreditcardId.pgType.encode(creditcardid)}""".update().runUnchecked(c) > 0
  }

  def upsert(unsaved: CreditcardRow)(using c: Connection): CreditcardRow = {
  interpolate"""insert into "sales"."creditcard"("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate")
    values (${/* user-picked */ CustomCreditcardId.pgType.encode(unsaved.creditcardid)}::int4, ${PgTypes.text.encode(unsaved.cardtype)}, ${PgTypes.text.encode(unsaved.cardnumber)}, ${TypoShort.pgType.encode(unsaved.expmonth)}::int2, ${TypoShort.pgType.encode(unsaved.expyear)}::int2, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    on conflict ("creditcardid")
    do update set
      "cardtype" = EXCLUDED."cardtype",
    "cardnumber" = EXCLUDED."cardnumber",
    "expmonth" = EXCLUDED."expmonth",
    "expyear" = EXCLUDED."expyear",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    """
    .updateReturning(CreditcardRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  def upsertBatch(unsaved: java.util.Iterator[CreditcardRow])(using c: Connection): java.util.List[CreditcardRow] = {
    interpolate"""insert into "sales"."creditcard"("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate")
    values (?::int4, ?, ?, ?::int2, ?::int2, ?::timestamp)
    on conflict ("creditcardid")
    do update set
      "cardtype" = EXCLUDED."cardtype",
    "cardnumber" = EXCLUDED."cardnumber",
    "expmonth" = EXCLUDED."expmonth",
    "expyear" = EXCLUDED."expyear",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate"::text
    """
      .updateManyReturning(CreditcardRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[CreditcardRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    interpolate"""create temporary table creditcard_TEMP (like "sales"."creditcard") on commit drop""".update().runUnchecked(c): @scala.annotation.nowarn
    streamingInsert.insertUnchecked(s"""copy creditcard_TEMP("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate") from stdin""", batchSize, unsaved, c, CreditcardRow.pgText): @scala.annotation.nowarn
    interpolate"""insert into "sales"."creditcard"("creditcardid", "cardtype", "cardnumber", "expmonth", "expyear", "modifieddate")
    select * from creditcard_TEMP
    on conflict ("creditcardid")
    do update set
      "cardtype" = EXCLUDED."cardtype",
    "cardnumber" = EXCLUDED."cardnumber",
    "expmonth" = EXCLUDED."expmonth",
    "expyear" = EXCLUDED."expyear",
    "modifieddate" = EXCLUDED."modifieddate"
    ;
    drop table creditcard_TEMP;""".update().runUnchecked(c)
  }
}