/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.pm

import java.sql.Connection
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.interpolate

class PmViewRepoImpl extends PmViewRepo {
  override def select: SelectBuilder[PmViewFields, PmViewRow] = SelectBuilder.of(""""pr"."pm"""", PmViewFields.structure, PmViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): java.util.List[PmViewRow] = {
    interpolate(Fragment.lit("""select "id", "productmodelid", "name", "catalogdescription", "instructions", "rowguid", "modifieddate"
    from "pr"."pm"
    """)).query(PmViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}