/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.bom

import java.sql.Connection
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.interpolate

class BomViewRepoImpl extends BomViewRepo {
  override def select: SelectBuilder[BomViewFields, BomViewRow] = SelectBuilder.of(""""pr"."bom"""", BomViewFields.structure, BomViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): java.util.List[BomViewRow] = {
    interpolate(Fragment.lit("""select "id", "billofmaterialsid", "productassemblyid", "componentid", "startdate", "enddate", "unitmeasurecode", "bomlevel", "perassemblyqty", "modifieddate"
    from "pr"."bom"
    """)).query(BomViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}