/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_.test_sak_soknadsalternativ;

import adventureworks.public_.test_utdanningstilbud.TestUtdanningstilbudId;

/** Type for the composite primary key of table `public.test_sak_soknadsalternativ` */
public record TestSakSoknadsalternativId(
  String organisasjonskodeSaksbehandler,
  String utdanningsmulighetKode
) {
  public TestSakSoknadsalternativId withOrganisasjonskodeSaksbehandler(String organisasjonskodeSaksbehandler) {
    return new TestSakSoknadsalternativId(organisasjonskodeSaksbehandler, utdanningsmulighetKode);
  };

  public TestSakSoknadsalternativId withUtdanningsmulighetKode(String utdanningsmulighetKode) {
    return new TestSakSoknadsalternativId(organisasjonskodeSaksbehandler, utdanningsmulighetKode);
  };

  static public TestSakSoknadsalternativId from(
    TestUtdanningstilbudId TestUtdanningstilbudId,
    String organisasjonskodeSaksbehandler
  ) {
    return new TestSakSoknadsalternativId(organisasjonskodeSaksbehandler, TestUtdanningstilbudId.utdanningsmulighetKode());
  };
}