/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customers

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.Db2Types
import dev.typr.foundations.kotlin.RowParser
import dev.typr.foundations.kotlin.RowParsers
import dev.typr.foundations.kotlin.nullable
import java.time.LocalDateTime
import testdb.customtypes.Defaulted

/** Table: CUSTOMERS
  * Customer master table containing all customer information
  * Primary key: CUSTOMER_ID
  */
data class CustomersRow(
  /** Unique identifier for the customer
    * Identity BY DEFAULT
    */
  @JsonProperty("CUSTOMER_ID") val customerId: CustomersId,
  /** Full name of the customer */
  @JsonProperty("NAME") val name: String,
  /** Email address used for contact and login */
  @JsonProperty("EMAIL") val email: String,
  /** Default: CURRENT TIMESTAMP */
  @JsonProperty("CREATED_AT") val createdAt: LocalDateTime?
) {
  fun id(): CustomersId = customerId

  fun toUnsavedRow(
    customerId: Defaulted<CustomersId>,
    createdAt: Defaulted<LocalDateTime?>
  ): CustomersRowUnsaved = CustomersRowUnsaved(name, email, customerId, createdAt)

  companion object {
    val _rowParser: RowParser<CustomersRow> = RowParsers.of(CustomersId.pgType, Db2Types.varchar, Db2Types.varchar, Db2Types.timestamp.nullable(), { t0, t1, t2, t3 -> CustomersRow(t0, t1, t2, t3) }, { row -> arrayOf<Any?>(row.customerId, row.name, row.email, row.createdAt) })
  }
}