/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.sr

import java.sql.Connection
import typo.scaladsl.Dialect
import typo.scaladsl.SelectBuilder
import typo.scaladsl.Fragment.sql

class SrViewRepoImpl extends SrViewRepo {
  override def select: SelectBuilder[SrViewFields, SrViewRow] = SelectBuilder.of(""""sa"."sr"""", SrViewFields.structure, SrViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): List[SrViewRow] = {
    sql"""select "id", "salesreasonid", "name", "reasontype", "modifieddate"
    from "sa"."sr"
    """.query(SrViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}