/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.departments

import java.math.BigDecimal
import kotlin.collections.List
import typo.dsl.FieldsExpr
import typo.dsl.Path
import typo.dsl.SqlExpr
import typo.dsl.SqlExpr.FieldLike
import typo.kotlindsl.RelationStructure
import typo.kotlindsl.SqlExpr.CompositeIn
import typo.kotlindsl.SqlExpr.CompositeIn.Part
import typo.kotlindsl.SqlExpr.Field
import typo.kotlindsl.SqlExpr.IdField
import typo.kotlindsl.SqlExpr.OptField
import typo.runtime.DuckDbTypes
import typo.runtime.RowParser

interface DepartmentsFields : FieldsExpr<DepartmentsRow> {
  abstract fun budget(): OptField<BigDecimal, DepartmentsRow>

  abstract override fun columns(): List<FieldLike<*, DepartmentsRow>>

  fun compositeIdIn(compositeIds: List<DepartmentsId>): SqlExpr<Boolean> = CompositeIn(listOf(Part<String, DepartmentsId, DepartmentsRow>(deptCode(), DepartmentsId::deptCode, DuckDbTypes.varchar), Part<String, DepartmentsId, DepartmentsRow>(deptRegion(), DepartmentsId::deptRegion, DuckDbTypes.varchar)), compositeIds)

  fun compositeIdIs(compositeId: DepartmentsId): SqlExpr<Boolean> = SqlExpr.all(deptCode().isEqual(compositeId.deptCode), deptRegion().isEqual(compositeId.deptRegion))

  abstract fun deptCode(): IdField<String, DepartmentsRow>

  abstract fun deptName(): Field<String, DepartmentsRow>

  abstract fun deptRegion(): IdField<String, DepartmentsRow>

  override fun rowParser(): RowParser<DepartmentsRow> = DepartmentsRow._rowParser.underlying

  companion object {
    data class Impl(val _path: List<Path>) : DepartmentsFields, RelationStructure<DepartmentsFields, DepartmentsRow> {
      override fun deptCode(): IdField<String, DepartmentsRow> = IdField<String, DepartmentsRow>(_path, "dept_code", DepartmentsRow::deptCode, null, null, { row, value -> row.copy(deptCode = value) }, DuckDbTypes.varchar)

      override fun deptRegion(): IdField<String, DepartmentsRow> = IdField<String, DepartmentsRow>(_path, "dept_region", DepartmentsRow::deptRegion, null, null, { row, value -> row.copy(deptRegion = value) }, DuckDbTypes.varchar)

      override fun deptName(): Field<String, DepartmentsRow> = Field<String, DepartmentsRow>(_path, "dept_name", DepartmentsRow::deptName, null, null, { row, value -> row.copy(deptName = value) }, DuckDbTypes.varchar)

      override fun budget(): OptField<BigDecimal, DepartmentsRow> = OptField<BigDecimal, DepartmentsRow>(_path, "budget", DepartmentsRow::budget, null, "DECIMAL(15,2)", { row, value -> row.copy(budget = value) }, DuckDbTypes.numeric)

      override fun _path(): List<Path> = _path

      override fun columns(): List<FieldLike<*, DepartmentsRow>> = listOf(this.deptCode().underlying, this.deptRegion().underlying, this.deptName().underlying, this.budget().underlying)

      override fun withPaths(_path: List<Path>): RelationStructure<DepartmentsFields, DepartmentsRow> = Impl(_path)
    }

    val structure: Impl = Impl(emptyList<typo.dsl.Path>())
  }
}