/**
 * File automatically generated by `typo` for its own test suite.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN
 */
package testdb.hardcoded.myschema.marital_status;



public sealed interface MaritalStatusFieldValue<T> {
  record id(MaritalStatusId value) implements MaritalStatusFieldValue<MaritalStatusId> {
    public id withValue(MaritalStatusId value) {
      return new id(value);
    };
    public String name() {
      return "id";
    };
  };
  String name();
  T value();
}