/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.SqlServerTypes
import dev.typr.foundations.Tuple.Tuple4
import dev.typr.foundations.scala.DbTypeOps
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import dev.typr.foundations.scala.ScalaDbTypes
import java.time.LocalDateTime
import testdb.customers.CustomersId
import testdb.customtypes.Defaulted

/** Table: orders
 * Primary key: order_id
 */
case class OrdersRow(
  /** IDENTITY(1, 1) */
  @JsonProperty("order_id") orderId: OrdersId,
  /** Points to [[testdb.customers.CustomersRow.customerId]] */
  @JsonProperty("customer_id") customerId: CustomersId,
  /** Default: (getdate()) */
  @JsonProperty("order_date") orderDate: Option[LocalDateTime],
  @JsonProperty("total_amount") totalAmount: BigDecimal
) extends Tuple4[OrdersId, CustomersId, Option[LocalDateTime], BigDecimal] {
  def id: OrdersId = orderId

  def toUnsavedRow(orderDate: Defaulted[Option[LocalDateTime]] = Defaulted.Provided(this.orderDate)): OrdersRowUnsaved = new OrdersRowUnsaved(customerId, totalAmount, orderDate)

  override def `_1`: OrdersId = orderId

  override def `_2`: CustomersId = customerId

  override def `_3`: Option[LocalDateTime] = orderDate

  override def `_4`: BigDecimal = totalAmount
}

object OrdersRow {
  val `_rowParser`: RowParser[OrdersRow] = RowParsers.of(OrdersId.sqlServerType, CustomersId.sqlServerType, SqlServerTypes.datetime2.nullable, ScalaDbTypes.SqlServerTypes.money)(OrdersRow.apply)(row => Array[Any](row.orderId, row.customerId, row.orderDate, row.totalAmount))
}