/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.nullability_test;

import static dev.typr.foundations.Fragment.interpolate;

import dev.typr.foundations.Db2Types;
import dev.typr.foundations.Fragment;
import dev.typr.foundations.dsl.DeleteBuilder;
import dev.typr.foundations.dsl.Dialect;
import dev.typr.foundations.dsl.SelectBuilder;
import dev.typr.foundations.dsl.UpdateBuilder;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

public class NullabilityTestRepoImpl implements NullabilityTestRepo {
  @Override
  public DeleteBuilder<NullabilityTestFields, NullabilityTestRow> delete() {
    return DeleteBuilder.of("\"NULLABILITY_TEST\"", NullabilityTestFields.structure, Dialect.DB2);
  }

  @Override
  public NullabilityTestRow insert(NullabilityTestRow unsaved, Connection c) {
    return interpolate(
            Fragment.lit(
                "SELECT \"ID\", \"REQUIRED_COL\", \"OPTIONAL_COL\", \"DEFAULTED_COL\" FROM FINAL"
                    + " TABLE (INSERT INTO \"NULLABILITY_TEST\"(\"ID\", \"REQUIRED_COL\","
                    + " \"OPTIONAL_COL\", \"DEFAULTED_COL\")\n"
                    + "VALUES ("),
            Fragment.encode(Db2Types.integer, unsaved.id()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.varchar, unsaved.requiredCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.varchar.opt(), unsaved.optionalCol()),
            Fragment.lit(", "),
            Fragment.encode(Db2Types.varchar.opt(), unsaved.defaultedCol()),
            Fragment.lit("))\n"))
        .updateReturning(NullabilityTestRow._rowParser.exactlyOne())
        .runUnchecked(c);
  }

  @Override
  public NullabilityTestRow insert(NullabilityTestRowUnsaved unsaved, Connection c) {
    ArrayList<Fragment> columns = new ArrayList<>();
    ;
    ArrayList<Fragment> values = new ArrayList<>();
    ;
    columns.add(Fragment.lit("\"ID\""));
    values.add(interpolate(Fragment.encode(Db2Types.integer, unsaved.id()), Fragment.lit("")));
    columns.add(Fragment.lit("\"REQUIRED_COL\""));
    values.add(
        interpolate(Fragment.encode(Db2Types.varchar, unsaved.requiredCol()), Fragment.lit("")));
    columns.add(Fragment.lit("\"OPTIONAL_COL\""));
    values.add(
        interpolate(
            Fragment.encode(Db2Types.varchar.opt(), unsaved.optionalCol()), Fragment.lit("")));
    unsaved
        .defaultedCol()
        .visit(
            () -> {},
            value -> {
              columns.add(Fragment.lit("\"DEFAULTED_COL\""));
              values.add(
                  interpolate(Fragment.encode(Db2Types.varchar.opt(), value), Fragment.lit("")));
            });
    ;
    Fragment q =
        interpolate(
            Fragment.lit(
                "SELECT \"ID\", \"REQUIRED_COL\", \"OPTIONAL_COL\", \"DEFAULTED_COL\" FROM FINAL"
                    + " TABLE (INSERT INTO \"NULLABILITY_TEST\"("),
            Fragment.comma(columns),
            Fragment.lit(")\nVALUES ("),
            Fragment.comma(values),
            Fragment.lit("))\n"));
    ;
    return q.updateReturning(NullabilityTestRow._rowParser.exactlyOne()).runUnchecked(c);
  }

  @Override
  public SelectBuilder<NullabilityTestFields, NullabilityTestRow> select() {
    return SelectBuilder.of(
        "\"NULLABILITY_TEST\"",
        NullabilityTestFields.structure,
        NullabilityTestRow._rowParser,
        Dialect.DB2);
  }

  @Override
  public List<NullabilityTestRow> selectAll(Connection c) {
    return interpolate(
            Fragment.lit(
                "select \"ID\", \"REQUIRED_COL\", \"OPTIONAL_COL\", \"DEFAULTED_COL\"\n"
                    + "from \"NULLABILITY_TEST\"\n"))
        .query(NullabilityTestRow._rowParser.all())
        .runUnchecked(c);
  }

  @Override
  public UpdateBuilder<NullabilityTestFields, NullabilityTestRow> update() {
    return UpdateBuilder.of(
        "\"NULLABILITY_TEST\"",
        NullabilityTestFields.structure,
        NullabilityTestRow._rowParser,
        Dialect.DB2);
  }
}
