/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.nullability_test;

import dev.typr.foundations.dsl.DeleteBuilder;
import dev.typr.foundations.dsl.SelectBuilder;
import dev.typr.foundations.dsl.UpdateBuilder;
import java.sql.Connection;
import java.util.List;

public interface NullabilityTestRepo {
  DeleteBuilder<NullabilityTestFields, NullabilityTestRow> delete();

  NullabilityTestRow insert(NullabilityTestRow unsaved, Connection c);

  NullabilityTestRow insert(NullabilityTestRowUnsaved unsaved, Connection c);

  SelectBuilder<NullabilityTestFields, NullabilityTestRow> select();

  List<NullabilityTestRow> selectAll(Connection c);

  UpdateBuilder<NullabilityTestFields, NullabilityTestRow> update();
}
