/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.hr.edh;

import jakarta.enterprise.context.ApplicationScoped;
import java.sql.Connection;
import java.util.List;
import typo.dsl.SelectBuilder;
import static typo.runtime.Fragment.interpolate;

@ApplicationScoped
public class EdhViewRepoImpl implements EdhViewRepo {
  public SelectBuilder<EdhViewFields, EdhViewRow> select() {
    return SelectBuilder.of("hr.edh", EdhViewFields.structure(), EdhViewRow._rowParser);
  };

  public List<EdhViewRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "businessentityid", "departmentid", "shiftid", "startdate"::text, "enddate"::text, "modifieddate"::text
       from "hr"."edh"
    """)).as(EdhViewRow._rowParser.all()).runUnchecked(c);
  };
}