/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_.users;

import adventureworks.customtypes.TypoUnknownCitext;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import typo.dsl.DeleteBuilder;
import typo.dsl.DeleteBuilder.DeleteBuilderMock;
import typo.dsl.DeleteParams;
import typo.dsl.SelectBuilder;
import typo.dsl.SelectBuilderMock;
import typo.dsl.SelectParams;
import typo.dsl.UpdateBuilder;
import typo.dsl.UpdateBuilder.UpdateBuilderMock;
import typo.dsl.UpdateParams;
import static typo.runtime.internal.stringInterpolator.str;

public record UsersRepoMock(
  java.util.function.Function<UsersRowUnsaved, UsersRow> toRow,
  HashMap<UsersId, UsersRow> map
) implements UsersRepo {
  public UsersRepoMock(java.util.function.Function<UsersRowUnsaved, UsersRow> toRow) {
    this(toRow, new HashMap<UsersId, UsersRow>());
  };

  public UsersRepoMock withToRow(java.util.function.Function<UsersRowUnsaved, UsersRow> toRow) {
    return new UsersRepoMock(toRow, map);
  };

  public UsersRepoMock withMap(HashMap<UsersId, UsersRow> map) {
    return new UsersRepoMock(toRow, map);
  };

  public DeleteBuilder<UsersFields, UsersRow> delete() {
    return new DeleteBuilderMock<>(UsersFields.structure(), () -> new ArrayList<>(map.values()), DeleteParams.empty(), row -> row.userId(), id -> map.remove(id));
  };

  public Boolean deleteById(
    UsersId userId,
    Connection c
  ) {
    return Optional.ofNullable(map.remove(userId)).isPresent();
  };

  public Integer deleteByIds(
    UsersId[] userIds,
    Connection c
  ) {
    var count = 0;
      for (var id : userIds) { if (Optional.ofNullable(map.remove(id)).isPresent()) {
        count = count + 1;
      } };
    return count;
  };

  public UsersRow insert(
    UsersRow unsaved,
    Connection c
  ) {
    if (map.containsKey(unsaved.userId())) {
        throw new RuntimeException(str("id $unsaved.userId() already exists"));
      };
      map.put(unsaved.userId(), unsaved);
    return unsaved;
  };

  public UsersRow insert(
    UsersRowUnsaved unsaved,
    Connection c
  ) {
    return insert(toRow.apply(unsaved), c);
  };

  public Long insertStreaming(
    Iterator<UsersRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.userId(), row);
        count = count + 1L;
      };
    return count;
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<UsersRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var unsavedRow = unsaved.next();
        var row = toRow.apply(unsavedRow);
        map.put(row.userId(), row);
        count = count + 1L;
      };
    return count;
  };

  public SelectBuilder<UsersFields, UsersRow> select() {
    return new SelectBuilderMock<>(UsersFields.structure(), () -> new ArrayList<>(map.values()), SelectParams.empty());
  };

  public List<UsersRow> selectAll(Connection c) {
    return new ArrayList<>(map.values());
  };

  public Optional<UsersRow> selectById(
    UsersId userId,
    Connection c
  ) {
    return Optional.ofNullable(map.get(userId));
  };

  public List<UsersRow> selectByIds(
    UsersId[] userIds,
    Connection c
  ) {
    var result = new ArrayList<UsersRow>();
      for (var id : userIds) { var opt = Optional.ofNullable(map.get(id));
      if (opt.isPresent()) result.add(opt.get()); };
    return result;
  };

  public Map<UsersId, UsersRow> selectByIdsTracked(
    UsersId[] userIds,
    Connection c
  ) {
    return selectByIds(userIds, c).stream().collect(Collectors.toMap((adventureworks.public_.users.UsersRow row) -> row.userId(), Function.identity()));
  };

  public Optional<UsersRow> selectByUniqueEmail(
    TypoUnknownCitext email,
    Connection c
  ) {
    return new ArrayList<>(map.values()).stream().filter(v -> email.equals(v.email())).findFirst();
  };

  public UpdateBuilder<UsersFields, UsersRow> update() {
    return new UpdateBuilderMock<>(UsersFields.structure(), () -> new ArrayList<>(map.values()), UpdateParams.empty(), row -> row);
  };

  public Boolean update(
    UsersRow row,
    Connection c
  ) {
    var shouldUpdate = Optional.ofNullable(map.get(row.userId())).filter(oldRow -> !oldRow.equals(row)).isPresent();
      if (shouldUpdate) {
        map.put(row.userId(), row);
      };
    return shouldUpdate;
  };

  public UsersRow upsert(
    UsersRow unsaved,
    Connection c
  ) {
    map.put(unsaved.userId(), unsaved);
    return unsaved;
  };

  public List<UsersRow> upsertBatch(
    Iterator<UsersRow> unsaved,
    Connection c
  ) {
    var result = new ArrayList<UsersRow>();
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.userId(), row);
        result.add(row);
      };
    return result;
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<UsersRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.userId(), row);
        count = count + 1;
      };
    return count;
  };
}