/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.vsalesperson

import adventureworks.person.businessentity.BusinessentityId
import adventureworks.public.Name
import adventureworks.public.Phone
import adventureworks.userdefined.FirstName
import java.util.Optional
import typo.dsl.Path
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.SqlExpr.OptField
import typo.dsl.Structure.Relation
import typo.runtime.PgTypes

trait VsalespersonViewFields {
  def businessentityid: Field[BusinessentityId, VsalespersonViewRow]

  def title: OptField[/* max 8 chars */ String, VsalespersonViewRow]

  def firstname: Field[/* user-picked */ FirstName, VsalespersonViewRow]

  def middlename: OptField[Name, VsalespersonViewRow]

  def lastname: Field[Name, VsalespersonViewRow]

  def suffix: OptField[/* max 10 chars */ String, VsalespersonViewRow]

  def jobtitle: Field[/* max 50 chars */ String, VsalespersonViewRow]

  def phonenumber: OptField[Phone, VsalespersonViewRow]

  def phonenumbertype: OptField[Name, VsalespersonViewRow]

  def emailaddress: OptField[/* max 50 chars */ String, VsalespersonViewRow]

  def emailpromotion: Field[Integer, VsalespersonViewRow]

  def addressline1: Field[/* max 60 chars */ String, VsalespersonViewRow]

  def addressline2: OptField[/* max 60 chars */ String, VsalespersonViewRow]

  def city: Field[/* max 30 chars */ String, VsalespersonViewRow]

  def stateprovincename: Field[Name, VsalespersonViewRow]

  def postalcode: Field[/* max 15 chars */ String, VsalespersonViewRow]

  def countryregionname: Field[Name, VsalespersonViewRow]

  def territoryname: OptField[Name, VsalespersonViewRow]

  def territorygroup: OptField[/* max 50 chars */ String, VsalespersonViewRow]

  def salesquota: OptField[java.math.BigDecimal, VsalespersonViewRow]

  def salesytd: Field[java.math.BigDecimal, VsalespersonViewRow]

  def saleslastyear: Field[java.math.BigDecimal, VsalespersonViewRow]
}

object VsalespersonViewFields {
  private final class Impl(path: java.util.List[Path]) extends Relation[VsalespersonViewFields, VsalespersonViewRow](path) {

    override lazy val fields: VsalespersonViewFields = {
      new VsalespersonViewFields {
        def businessentityid: Field[BusinessentityId, VsalespersonViewRow] = {
          new Field[BusinessentityId, VsalespersonViewRow](
            _path,
            "businessentityid",
            _.businessentityid,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(businessentityid = value),
            BusinessentityId.pgType
          )
        }
        def title: OptField[/* max 8 chars */ String, VsalespersonViewRow] = {
          new OptField[/* max 8 chars */ String, VsalespersonViewRow](
            _path,
            "title",
            _.title,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(title = value),
            PgTypes.text
          )
        }
        def firstname: Field[/* user-picked */ FirstName, VsalespersonViewRow] = {
          new Field[/* user-picked */ FirstName, VsalespersonViewRow](
            _path,
            "firstname",
            _.firstname,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(firstname = value),
            /* user-picked */ FirstName.pgType
          )
        }
        def middlename: OptField[Name, VsalespersonViewRow] = {
          new OptField[Name, VsalespersonViewRow](
            _path,
            "middlename",
            _.middlename,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(middlename = value),
            Name.pgType
          )
        }
        def lastname: Field[Name, VsalespersonViewRow] = {
          new Field[Name, VsalespersonViewRow](
            _path,
            "lastname",
            _.lastname,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(lastname = value),
            Name.pgType
          )
        }
        def suffix: OptField[/* max 10 chars */ String, VsalespersonViewRow] = {
          new OptField[/* max 10 chars */ String, VsalespersonViewRow](
            _path,
            "suffix",
            _.suffix,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(suffix = value),
            PgTypes.text
          )
        }
        def jobtitle: Field[/* max 50 chars */ String, VsalespersonViewRow] = {
          new Field[/* max 50 chars */ String, VsalespersonViewRow](
            _path,
            "jobtitle",
            _.jobtitle,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(jobtitle = value),
            PgTypes.text
          )
        }
        def phonenumber: OptField[Phone, VsalespersonViewRow] = {
          new OptField[Phone, VsalespersonViewRow](
            _path,
            "phonenumber",
            _.phonenumber,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(phonenumber = value),
            Phone.pgType
          )
        }
        def phonenumbertype: OptField[Name, VsalespersonViewRow] = {
          new OptField[Name, VsalespersonViewRow](
            _path,
            "phonenumbertype",
            _.phonenumbertype,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(phonenumbertype = value),
            Name.pgType
          )
        }
        def emailaddress: OptField[/* max 50 chars */ String, VsalespersonViewRow] = {
          new OptField[/* max 50 chars */ String, VsalespersonViewRow](
            _path,
            "emailaddress",
            _.emailaddress,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(emailaddress = value),
            PgTypes.text
          )
        }
        def emailpromotion: Field[Integer, VsalespersonViewRow] = {
          new Field[Integer, VsalespersonViewRow](
            _path,
            "emailpromotion",
            _.emailpromotion,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(emailpromotion = value),
            PgTypes.int4
          )
        }
        def addressline1: Field[/* max 60 chars */ String, VsalespersonViewRow] = {
          new Field[/* max 60 chars */ String, VsalespersonViewRow](
            _path,
            "addressline1",
            _.addressline1,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(addressline1 = value),
            PgTypes.text
          )
        }
        def addressline2: OptField[/* max 60 chars */ String, VsalespersonViewRow] = {
          new OptField[/* max 60 chars */ String, VsalespersonViewRow](
            _path,
            "addressline2",
            _.addressline2,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(addressline2 = value),
            PgTypes.text
          )
        }
        def city: Field[/* max 30 chars */ String, VsalespersonViewRow] = {
          new Field[/* max 30 chars */ String, VsalespersonViewRow](
            _path,
            "city",
            _.city,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(city = value),
            PgTypes.text
          )
        }
        def stateprovincename: Field[Name, VsalespersonViewRow] = {
          new Field[Name, VsalespersonViewRow](
            _path,
            "stateprovincename",
            _.stateprovincename,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(stateprovincename = value),
            Name.pgType
          )
        }
        def postalcode: Field[/* max 15 chars */ String, VsalespersonViewRow] = {
          new Field[/* max 15 chars */ String, VsalespersonViewRow](
            _path,
            "postalcode",
            _.postalcode,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(postalcode = value),
            PgTypes.text
          )
        }
        def countryregionname: Field[Name, VsalespersonViewRow] = {
          new Field[Name, VsalespersonViewRow](
            _path,
            "countryregionname",
            _.countryregionname,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(countryregionname = value),
            Name.pgType
          )
        }
        def territoryname: OptField[Name, VsalespersonViewRow] = {
          new OptField[Name, VsalespersonViewRow](
            _path,
            "territoryname",
            _.territoryname,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(territoryname = value),
            Name.pgType
          )
        }
        def territorygroup: OptField[/* max 50 chars */ String, VsalespersonViewRow] = {
          new OptField[/* max 50 chars */ String, VsalespersonViewRow](
            _path,
            "territorygroup",
            _.territorygroup,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(territorygroup = value),
            PgTypes.text
          )
        }
        def salesquota: OptField[java.math.BigDecimal, VsalespersonViewRow] = {
          new OptField[java.math.BigDecimal, VsalespersonViewRow](
            _path,
            "salesquota",
            _.salesquota,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(salesquota = value),
            PgTypes.numeric
          )
        }
        def salesytd: Field[java.math.BigDecimal, VsalespersonViewRow] = {
          new Field[java.math.BigDecimal, VsalespersonViewRow](
            _path,
            "salesytd",
            _.salesytd,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(salesytd = value),
            PgTypes.numeric
          )
        }
        def saleslastyear: Field[java.math.BigDecimal, VsalespersonViewRow] = {
          new Field[java.math.BigDecimal, VsalespersonViewRow](
            _path,
            "saleslastyear",
            _.saleslastyear,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(saleslastyear = value),
            PgTypes.numeric
          )
        }
      }
    }

    override lazy val columns: java.util.List[FieldLike[?, VsalespersonViewRow]] = java.util.List.of(this.fields.businessentityid, this.fields.title, this.fields.firstname, this.fields.middlename, this.fields.lastname, this.fields.suffix, this.fields.jobtitle, this.fields.phonenumber, this.fields.phonenumbertype, this.fields.emailaddress, this.fields.emailpromotion, this.fields.addressline1, this.fields.addressline2, this.fields.city, this.fields.stateprovincename, this.fields.postalcode, this.fields.countryregionname, this.fields.territoryname, this.fields.territorygroup, this.fields.salesquota, this.fields.salesytd, this.fields.saleslastyear)

    def copy(path: java.util.List[Path]): Impl = new Impl(path)
  }

  lazy val structure: Relation[VsalespersonViewFields, VsalespersonViewRow] = new Impl(java.util.List.of())
}