/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.location

import frontpage.Text
import frontpage.customtypes.Defaulted
import frontpage.customtypes.Defaulted.UseDefault
import frontpage.customtypes.TypoInet
import frontpage.customtypes.TypoJsonb
import frontpage.customtypes.TypoPoint
import frontpage.customtypes.TypoPolygon
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** This class corresponds to a row in table `frontpage.location` which has not been persisted yet */
case class LocationRowUnsaved(
  name: String,
  position: Option[TypoPoint] = None,
  area: Option[TypoPolygon] = None,
  ipRange: Option[TypoInet] = None,
  /** Default: gen_random_uuid() */
  id: Defaulted[LocationId] = new UseDefault(),
  /** Default: '{}'::jsonb */
  metadata: Defaulted[Option[TypoJsonb]] = new UseDefault()
) {
  def toRow(
    idDefault: => LocationId,
    metadataDefault: => Option[TypoJsonb]
  ): LocationRow = {
    new LocationRow(
      id = id.getOrElse(idDefault),
      name = name,
      position = position,
      area = area,
      ipRange = ipRange,
      metadata = metadata.getOrElse(metadataDefault)
    )
  }
}

object LocationRowUnsaved {
  given pgText: Text[LocationRowUnsaved] = {
    Text.instance[LocationRowUnsaved]{ (row, sb) =>
      Text.stringInstance.unsafeEncode(row.name, sb)
      sb.append(Text.DELIMETER)
      Text.option(using TypoPoint.pgText).unsafeEncode(row.position, sb)
      sb.append(Text.DELIMETER)
      Text.option(using TypoPolygon.pgText).unsafeEncode(row.area, sb)
      sb.append(Text.DELIMETER)
      Text.option(using TypoInet.pgText).unsafeEncode(row.ipRange, sb)
      sb.append(Text.DELIMETER)
      Defaulted.pgText(using LocationId.pgText).unsafeEncode(row.id, sb)
      sb.append(Text.DELIMETER)
      Defaulted.pgText(using Text.option(using TypoJsonb.pgText)).unsafeEncode(row.metadata, sb)
    }
  }

  given reads: Reads[LocationRowUnsaved] = {
    Reads[LocationRowUnsaved](json => JsResult.fromTry(
        Try(
          LocationRowUnsaved(
            name = json.\("name").as(Reads.StringReads),
            position = json.\("position").toOption.map(_.as(TypoPoint.reads)),
            area = json.\("area").toOption.map(_.as(TypoPolygon.reads)),
            ipRange = json.\("ip_range").toOption.map(_.as(TypoInet.reads)),
            id = json.\("id").as(Defaulted.reads(using LocationId.reads)),
            metadata = json.\("metadata").as(Defaulted.readsOpt(using TypoJsonb.reads))
          )
        )
      ),
    )
  }

  given writes: OWrites[LocationRowUnsaved] = {
    OWrites[LocationRowUnsaved](o =>
      new JsObject(ListMap[String, JsValue](
        "name" -> Writes.StringWrites.writes(o.name),
        "position" -> Writes.OptionWrites(using TypoPoint.writes).writes(o.position),
        "area" -> Writes.OptionWrites(using TypoPolygon.writes).writes(o.area),
        "ip_range" -> Writes.OptionWrites(using TypoInet.writes).writes(o.ipRange),
        "id" -> Defaulted.writes(using LocationId.writes).writes(o.id),
        "metadata" -> Defaulted.writes(using Writes.OptionWrites(using TypoJsonb.writes)).writes(o.metadata)
      ))
    )
  }
}