/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.cr

import java.sql.Connection
import typo.scaladsl.Dialect
import typo.scaladsl.SelectBuilder
import typo.scaladsl.Fragment.sql

class CrViewRepoImpl extends CrViewRepo {
  override def select: SelectBuilder[CrViewFields, CrViewRow] = SelectBuilder.of(""""pe"."cr"""", CrViewFields.structure, CrViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): List[CrViewRow] = {
    sql"""select "countryregioncode", "name", "modifieddate"
    from "pe"."cr"
    """.query(CrViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}