/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.employee;

import frontpage.frontpage.person.PersonFields;
import frontpage.frontpage.person.PersonId;
import frontpage.frontpage.person.PersonRow;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import typo.dsl.ForeignKey;
import typo.dsl.Path;
import typo.dsl.SqlExpr.Field;
import typo.dsl.SqlExpr.FieldLike;
import typo.dsl.SqlExpr.IdField;
import typo.dsl.SqlExpr.OptField;
import typo.dsl.Structure.Relation;
import typo.runtime.PgTypes;

public interface EmployeeFields {
  static final class Impl extends Relation<EmployeeFields, EmployeeRow> {
    Impl(List<Path> path) {
      super(path);
    }

    @Override
    public EmployeeFields fields() {
      return new EmployeeFields() {
               public IdField<EmployeeId, EmployeeRow> id() {
                 return new IdField<EmployeeId, EmployeeRow>(_path, "id", EmployeeRow::id, Optional.empty(), Optional.of("uuid"), (row, value) -> row.withId(value), EmployeeId.pgType);
               };
               public Field<PersonId, EmployeeRow> personId() {
                 return new Field<PersonId, EmployeeRow>(_path, "person_id", EmployeeRow::personId, Optional.empty(), Optional.of("uuid"), (row, value) -> row.withPersonId(value), PersonId.pgType);
               };
               public OptField<BigDecimal, EmployeeRow> salary() {
                 return new OptField<BigDecimal, EmployeeRow>(_path, "salary", EmployeeRow::salary, Optional.empty(), Optional.of("numeric"), (row, value) -> row.withSalary(value), PgTypes.numeric);
               };
             };
    };

    @Override
    public List<FieldLike<?, EmployeeRow>> columns() {
      return List.of(this.fields().id(), this.fields().personId(), this.fields().salary());
    };

    public Impl copy(List<Path> path) {
      return new Impl(path);
    };
  };

  static Relation<EmployeeFields, EmployeeRow> structure() {
    return new Impl(List.of());
  };

  IdField<EmployeeId, EmployeeRow> id();

  Field<PersonId, EmployeeRow> personId();

  OptField<BigDecimal, EmployeeRow> salary();

  default ForeignKey<PersonFields, PersonRow> fkPerson() {
    return ForeignKey.<PersonFields, PersonRow>of("frontpage.fk_person").withColumnPair(personId(), PersonFields::id);
  };
}