/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.transactionhistory

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.production.product.ProductId
import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.PgTypes
import typo.runtime.streamingInsert
import typo.runtime.FragmentInterpolator.interpolate

class TransactionhistoryRepoImpl extends TransactionhistoryRepo {
  def delete: DeleteBuilder[TransactionhistoryFields, TransactionhistoryRow] = DeleteBuilder.of("production.transactionhistory", TransactionhistoryFields.structure)

  def deleteById(transactionid: TransactionhistoryId)(using c: Connection): java.lang.Boolean = interpolate"""delete from "production"."transactionhistory" where "transactionid" = ${TransactionhistoryId.pgType.encode(transactionid)}""".update().runUnchecked(c) > 0

  def deleteByIds(transactionids: Array[TransactionhistoryId])(using c: Connection): Integer = {
    interpolate"""delete
    from "production"."transactionhistory"
    where "transactionid" = ANY(${TransactionhistoryId.pgTypeArray.encode(transactionids)})"""
      .update()
      .runUnchecked(c)
  }

  def insert(unsaved: TransactionhistoryRow)(using c: Connection): TransactionhistoryRow = {
  interpolate"""insert into "production"."transactionhistory"("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate")
    values (${TransactionhistoryId.pgType.encode(unsaved.transactionid)}::int4, ${ProductId.pgType.encode(unsaved.productid)}::int4, ${PgTypes.int4.encode(unsaved.referenceorderid)}::int4, ${PgTypes.int4.encode(unsaved.referenceorderlineid)}::int4, ${TypoLocalDateTime.pgType.encode(unsaved.transactiondate)}::timestamp, ${PgTypes.text.encode(unsaved.transactiontype)}::bpchar, ${PgTypes.int4.encode(unsaved.quantity)}::int4, ${PgTypes.numeric.encode(unsaved.actualcost)}::numeric, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    returning "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    """
    .updateReturning(TransactionhistoryRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insert(unsaved: TransactionhistoryRowUnsaved)(using c: Connection): TransactionhistoryRow = {
    val columns: java.util.List[Literal] = new ArrayList()
    val values: java.util.List[Fragment] = new ArrayList()
    columns.add(Fragment.lit(""""productid"""")): @scala.annotation.nowarn
    values.add(interpolate"${ProductId.pgType.encode(unsaved.productid)}::int4"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""referenceorderid"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.int4.encode(unsaved.referenceorderid)}::int4"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""transactiontype"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.text.encode(unsaved.transactiontype)}::bpchar"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""quantity"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.int4.encode(unsaved.quantity)}::int4"): @scala.annotation.nowarn
    columns.add(Fragment.lit(""""actualcost"""")): @scala.annotation.nowarn
    values.add(interpolate"${PgTypes.numeric.encode(unsaved.actualcost)}::numeric"): @scala.annotation.nowarn
    unsaved.transactionid.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""transactionid"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TransactionhistoryId.pgType.encode(value)}::int4"): @scala.annotation.nowarn;
      }
    );
    unsaved.referenceorderlineid.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""referenceorderlineid"""")): @scala.annotation.nowarn;
        values.add(interpolate"${PgTypes.int4.encode(value)}::int4"): @scala.annotation.nowarn;
      }
    );
    unsaved.transactiondate.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""transactiondate"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TypoLocalDateTime.pgType.encode(value)}::timestamp"): @scala.annotation.nowarn;
      }
    );
    unsaved.modifieddate.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""modifieddate"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TypoLocalDateTime.pgType.encode(value)}::timestamp"): @scala.annotation.nowarn;
      }
    );
    val q: Fragment = {
      interpolate"""insert into "production"."transactionhistory"(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
      """
    }
    q.updateReturning(TransactionhistoryRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insertStreaming(
    unsaved: java.util.Iterator[TransactionhistoryRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "production"."transactionhistory"("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate") FROM STDIN""", batchSize, unsaved, c, TransactionhistoryRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[TransactionhistoryRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "production"."transactionhistory"("productid", "referenceorderid", "transactiontype", "quantity", "actualcost", "transactionid", "referenceorderlineid", "transactiondate", "modifieddate") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved, c, TransactionhistoryRowUnsaved.pgText)

  def select: SelectBuilder[TransactionhistoryFields, TransactionhistoryRow] = SelectBuilder.of("production.transactionhistory", TransactionhistoryFields.structure, TransactionhistoryRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[TransactionhistoryRow] = {
    interpolate"""select "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    from "production"."transactionhistory"
    """.as(TransactionhistoryRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectById(transactionid: TransactionhistoryId)(using c: Connection): Optional[TransactionhistoryRow] = {
    interpolate"""select "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    from "production"."transactionhistory"
    where "transactionid" = ${TransactionhistoryId.pgType.encode(transactionid)}""".as(TransactionhistoryRow.`_rowParser`.first()).runUnchecked(c)
  }

  def selectByIds(transactionids: Array[TransactionhistoryId])(using c: Connection): java.util.List[TransactionhistoryRow] = {
    interpolate"""select "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    from "production"."transactionhistory"
    where "transactionid" = ANY(${TransactionhistoryId.pgTypeArray.encode(transactionids)})""".as(TransactionhistoryRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectByIdsTracked(transactionids: Array[TransactionhistoryId])(using c: Connection): java.util.Map[TransactionhistoryId, TransactionhistoryRow] = {
    val ret: java.util.Map[TransactionhistoryId, TransactionhistoryRow] = new HashMap()
    selectByIds(transactionids)(using c).forEach(row => ret.put(row.transactionid, row): @scala.annotation.nowarn)
    ret
  }

  def update: UpdateBuilder[TransactionhistoryFields, TransactionhistoryRow] = UpdateBuilder.of("production.transactionhistory", TransactionhistoryFields.structure, TransactionhistoryRow.`_rowParser`.all())

  def update(row: TransactionhistoryRow)(using c: Connection): java.lang.Boolean = {
    val transactionid: TransactionhistoryId = row.transactionid
    interpolate"""update "production"."transactionhistory"
    set "productid" = ${ProductId.pgType.encode(row.productid)}::int4,
    "referenceorderid" = ${PgTypes.int4.encode(row.referenceorderid)}::int4,
    "referenceorderlineid" = ${PgTypes.int4.encode(row.referenceorderlineid)}::int4,
    "transactiondate" = ${TypoLocalDateTime.pgType.encode(row.transactiondate)}::timestamp,
    "transactiontype" = ${PgTypes.text.encode(row.transactiontype)}::bpchar,
    "quantity" = ${PgTypes.int4.encode(row.quantity)}::int4,
    "actualcost" = ${PgTypes.numeric.encode(row.actualcost)}::numeric,
    "modifieddate" = ${TypoLocalDateTime.pgType.encode(row.modifieddate)}::timestamp
    where "transactionid" = ${TransactionhistoryId.pgType.encode(transactionid)}""".update().runUnchecked(c) > 0
  }

  def upsert(unsaved: TransactionhistoryRow)(using c: Connection): TransactionhistoryRow = {
  interpolate"""insert into "production"."transactionhistory"("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate")
    values (${TransactionhistoryId.pgType.encode(unsaved.transactionid)}::int4, ${ProductId.pgType.encode(unsaved.productid)}::int4, ${PgTypes.int4.encode(unsaved.referenceorderid)}::int4, ${PgTypes.int4.encode(unsaved.referenceorderlineid)}::int4, ${TypoLocalDateTime.pgType.encode(unsaved.transactiondate)}::timestamp, ${PgTypes.text.encode(unsaved.transactiontype)}::bpchar, ${PgTypes.int4.encode(unsaved.quantity)}::int4, ${PgTypes.numeric.encode(unsaved.actualcost)}::numeric, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    on conflict ("transactionid")
    do update set
      "productid" = EXCLUDED."productid",
    "referenceorderid" = EXCLUDED."referenceorderid",
    "referenceorderlineid" = EXCLUDED."referenceorderlineid",
    "transactiondate" = EXCLUDED."transactiondate",
    "transactiontype" = EXCLUDED."transactiontype",
    "quantity" = EXCLUDED."quantity",
    "actualcost" = EXCLUDED."actualcost",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    """
    .updateReturning(TransactionhistoryRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  def upsertBatch(unsaved: java.util.Iterator[TransactionhistoryRow])(using c: Connection): java.util.List[TransactionhistoryRow] = {
    interpolate"""insert into "production"."transactionhistory"("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate")
    values (?::int4, ?::int4, ?::int4, ?::int4, ?::timestamp, ?::bpchar, ?::int4, ?::numeric, ?::timestamp)
    on conflict ("transactionid")
    do update set
      "productid" = EXCLUDED."productid",
    "referenceorderid" = EXCLUDED."referenceorderid",
    "referenceorderlineid" = EXCLUDED."referenceorderlineid",
    "transactiondate" = EXCLUDED."transactiondate",
    "transactiontype" = EXCLUDED."transactiontype",
    "quantity" = EXCLUDED."quantity",
    "actualcost" = EXCLUDED."actualcost",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate"::text, "transactiontype", "quantity", "actualcost", "modifieddate"::text
    """
      .updateManyReturning(TransactionhistoryRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[TransactionhistoryRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    interpolate"""create temporary table transactionhistory_TEMP (like "production"."transactionhistory") on commit drop""".update().runUnchecked(c): @scala.annotation.nowarn
    streamingInsert.insertUnchecked(s"""copy transactionhistory_TEMP("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate") from stdin""", batchSize, unsaved, c, TransactionhistoryRow.pgText): @scala.annotation.nowarn
    interpolate"""insert into "production"."transactionhistory"("transactionid", "productid", "referenceorderid", "referenceorderlineid", "transactiondate", "transactiontype", "quantity", "actualcost", "modifieddate")
    select * from transactionhistory_TEMP
    on conflict ("transactionid")
    do update set
      "productid" = EXCLUDED."productid",
    "referenceorderid" = EXCLUDED."referenceorderid",
    "referenceorderlineid" = EXCLUDED."referenceorderlineid",
    "transactiondate" = EXCLUDED."transactiondate",
    "transactiontype" = EXCLUDED."transactiontype",
    "quantity" = EXCLUDED."quantity",
    "actualcost" = EXCLUDED."actualcost",
    "modifieddate" = EXCLUDED."modifieddate"
    ;
    drop table transactionhistory_TEMP;""".update().runUnchecked(c)
  }
}