/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.culture;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.Defaulted.UseDefault;
import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.public_.Name;
import typo.runtime.PgText;

/** This class corresponds to a row in table `production.culture` which has not been persisted yet */
public record CultureRowUnsaved(
  /** Primary key for Culture records. */
  CultureId cultureid,
  /** Culture description. */
  Name name,
  /** Default: now() */
  Defaulted<TypoLocalDateTime> modifieddate
) {
  public CultureRowUnsaved(
    /** Primary key for Culture records. */
    CultureId cultureid,
    /** Culture description. */
    Name name
  ) {
    this(cultureid, name, new UseDefault<>());
  };

  /** Primary key for Culture records. */
  public CultureRowUnsaved withCultureid(CultureId cultureid) {
    return new CultureRowUnsaved(cultureid, name, modifieddate);
  };

  /** Culture description. */
  public CultureRowUnsaved withName(Name name) {
    return new CultureRowUnsaved(cultureid, name, modifieddate);
  };

  /** Default: now() */
  public CultureRowUnsaved withModifieddate(Defaulted<TypoLocalDateTime> modifieddate) {
    return new CultureRowUnsaved(cultureid, name, modifieddate);
  };

  static public PgText<CultureRowUnsaved> pgText =
    PgText.instance((row, sb) -> {
      CultureId.pgType.pgText().unsafeEncode(row.cultureid, sb);
      sb.append(PgText.DELIMETER);
      Name.pgType.pgText().unsafeEncode(row.name, sb);
      sb.append(PgText.DELIMETER);
      Defaulted.pgText(TypoLocalDateTime.pgType.pgText()).unsafeEncode(row.modifieddate, sb);
    });

  public CultureRow toRow(java.util.function.Supplier<TypoLocalDateTime> modifieddateDefault) {
    return new CultureRow(cultureid, name, modifieddate.getOrElse(modifieddateDefault));
  };
}