/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.categories

import com.fasterxml.jackson.annotation.JsonProperty
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import typo.kotlindsl.KotlinDbTypes
import typo.kotlindsl.nullable
import typo.runtime.MariaText
import typo.runtime.MariaTypes

/** This class corresponds to a row in table `categories` which has not been persisted yet */
data class CategoriesRowUnsaved(
  /**  */
  val name: String,
  /**  */
  val slug: String,
  /** Default: NULL
    * Points to [testdb.categories.CategoriesRow.categoryId]
    */
  @JsonProperty("parent_id") val parentId: Defaulted<CategoriesId?> = UseDefault(),
  /** Default: NULL

    */
  val description: Defaulted<String?> = UseDefault(),
  /** Default: NULL

    */
  @JsonProperty("image_url") val imageUrl: Defaulted<String?> = UseDefault(),
  /** Default: 0

    */
  @JsonProperty("sort_order") val sortOrder: Defaulted<Short> = UseDefault(),
  /** Default: 1

    */
  @JsonProperty("is_visible") val isVisible: Defaulted<Boolean> = UseDefault(),
  /** Default: NULL

    */
  val metadata: Defaulted<String?> = UseDefault()
) {
  fun toRow(
    parentIdDefault: () -> CategoriesId?,
    descriptionDefault: () -> String?,
    imageUrlDefault: () -> String?,
    sortOrderDefault: () -> Short,
    isVisibleDefault: () -> Boolean,
    metadataDefault: () -> String?,
    categoryIdDefault: () -> CategoriesId
  ): CategoriesRow = CategoriesRow(categoryId = categoryIdDefault(), parentId = parentId.getOrElse(parentIdDefault), name = name, slug = slug, description = description.getOrElse(descriptionDefault), imageUrl = imageUrl.getOrElse(imageUrlDefault), sortOrder = sortOrder.getOrElse(sortOrderDefault), isVisible = isVisible.getOrElse(isVisibleDefault), metadata = metadata.getOrElse(metadataDefault))

  companion object {
    val mariaText: MariaText<CategoriesRowUnsaved> =
      MariaText.instance({ row, sb -> MariaTypes.varchar.mariaText().unsafeEncode(row.name, sb)
      sb.append(MariaText.DELIMETER)
      MariaTypes.varchar.mariaText().unsafeEncode(row.slug, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(CategoriesId.pgType.nullable().mariaText()).unsafeEncode(row.parentId, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(MariaTypes.mediumtext.nullable().mariaText()).unsafeEncode(row.description, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(MariaTypes.varchar.nullable().mariaText()).unsafeEncode(row.imageUrl, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(KotlinDbTypes.MariaTypes.smallint.mariaText()).unsafeEncode(row.sortOrder, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(KotlinDbTypes.MariaTypes.bool.mariaText()).unsafeEncode(row.isVisible, sb)
      sb.append(MariaText.DELIMETER)
      Defaulted.mariaText(MariaTypes.longtext.nullable().mariaText()).unsafeEncode(row.metadata, sb) })
  }
}