/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.vproductmodelinstructions

import java.sql.Connection
import typo.dsl.SelectBuilder
import anorm.SqlStringInterpolation

class VproductmodelinstructionsViewRepoImpl extends VproductmodelinstructionsViewRepo {
  def select: SelectBuilder[VproductmodelinstructionsViewFields, VproductmodelinstructionsViewRow] = SelectBuilder.of(""""production"."vproductmodelinstructions"""", VproductmodelinstructionsViewFields.structure, VproductmodelinstructionsViewRow.rowParser)

  def selectAll(using c: Connection): List[VproductmodelinstructionsViewRow] = {
    SQL"""select "productmodelid", "name", "instructions", "LocationID", "SetupHours", "MachineHours", "LaborHours", "LotSize", "Step", "rowguid", "modifieddate"::text
    from "production"."vproductmodelinstructions"
    """.as(VproductmodelinstructionsViewRow.rowParser(1).*)
  }
}