/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.vemployeedepartmenthistory

import java.sql.Connection
import typo.dsl.SelectBuilder
import typo.runtime.FragmentInterpolator.interpolate

class VemployeedepartmenthistoryViewRepoImpl extends VemployeedepartmenthistoryViewRepo {
  def select: SelectBuilder[VemployeedepartmenthistoryViewFields, VemployeedepartmenthistoryViewRow] = SelectBuilder.of("humanresources.vemployeedepartmenthistory", VemployeedepartmenthistoryViewFields.structure, VemployeedepartmenthistoryViewRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[VemployeedepartmenthistoryViewRow] = {
    interpolate"""select "businessentityid", "title", "firstname", "middlename", "lastname", "suffix", "shift", "department", "groupname", "startdate"::text, "enddate"::text
    from "humanresources"."vemployeedepartmenthistory"
    """.as(VemployeedepartmenthistoryViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}