/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.vjobcandidate

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.humanresources.jobcandidate.JobcandidateId
import adventureworks.person.businessentity.BusinessentityId
import java.util.Optional
import typo.runtime.PgTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers
import typo.runtime.RowParsers.Tuple16

/** View: humanresources.vjobcandidate */
case class VjobcandidateViewRow(
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.jobcandidateid]] */
  jobcandidateid: JobcandidateId,
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.businessentityid]] */
  businessentityid: Optional[BusinessentityId],
  namePrefix: /* nullability unknown */ Optional[/* max 30 chars */ String],
  nameFirst: /* nullability unknown */ Optional[/* max 30 chars */ String],
  nameMiddle: /* nullability unknown */ Optional[/* max 30 chars */ String],
  nameLast: /* nullability unknown */ Optional[/* max 30 chars */ String],
  nameSuffix: /* nullability unknown */ Optional[/* max 30 chars */ String],
  skills: /* nullability unknown */ Optional[String],
  addrType: /* nullability unknown */ Optional[/* max 30 chars */ String],
  addrLocCountryRegion: /* nullability unknown */ Optional[/* max 100 chars */ String],
  addrLocState: /* nullability unknown */ Optional[/* max 100 chars */ String],
  addrLocCity: /* nullability unknown */ Optional[/* max 100 chars */ String],
  addrPostalCode: /* nullability unknown */ Optional[/* max 20 chars */ String],
  eMail: /* nullability unknown */ Optional[String],
  webSite: /* nullability unknown */ Optional[String],
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.modifieddate]] */
  modifieddate: TypoLocalDateTime
)

object VjobcandidateViewRow {
  val `_rowParser`: RowParser[VjobcandidateViewRow] = {
    RowParsers.of(JobcandidateId.pgType, BusinessentityId.pgType.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), TypoLocalDateTime.pgType, VjobcandidateViewRow.apply, row => new Tuple16(
      row.jobcandidateid,
      row.businessentityid,
      row.namePrefix,
      row.nameFirst,
      row.nameMiddle,
      row.nameLast,
      row.nameSuffix,
      row.skills,
      row.addrType,
      row.addrLocCountryRegion,
      row.addrLocState,
      row.addrLocCity,
      row.addrPostalCode,
      row.eMail,
      row.webSite,
      row.modifieddate
    ))
  }
}