/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.vjobcandidate;

import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.humanresources.jobcandidate.JobcandidateId;
import adventureworks.person.businessentity.BusinessentityId;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;

/** View: humanresources.vjobcandidate */
public record VjobcandidateViewRow(
  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#jobcandidateid()} */
  JobcandidateId jobcandidateid,
  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#businessentityid()} */
  Optional<BusinessentityId> businessentityid,
  @JsonProperty("Name.Prefix") Optional</* max 30 chars */ String> namePrefix,
  @JsonProperty("Name.First") Optional</* max 30 chars */ String> nameFirst,
  @JsonProperty("Name.Middle") Optional</* max 30 chars */ String> nameMiddle,
  @JsonProperty("Name.Last") Optional</* max 30 chars */ String> nameLast,
  @JsonProperty("Name.Suffix") Optional</* max 30 chars */ String> nameSuffix,
  @JsonProperty("Skills") String skills,
  @JsonProperty("Addr.Type") Optional</* max 30 chars */ String> addrType,
  @JsonProperty("Addr.Loc.CountryRegion") Optional</* max 100 chars */ String> addrLocCountryRegion,
  @JsonProperty("Addr.Loc.State") Optional</* max 100 chars */ String> addrLocState,
  @JsonProperty("Addr.Loc.City") Optional</* max 100 chars */ String> addrLocCity,
  @JsonProperty("Addr.PostalCode") Optional</* max 20 chars */ String> addrPostalCode,
  @JsonProperty("EMail") String eMail,
  @JsonProperty("WebSite") String webSite,
  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#modifieddate()} */
  TypoLocalDateTime modifieddate
) {
  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#jobcandidateid()} */
  public VjobcandidateViewRow withJobcandidateid(JobcandidateId jobcandidateid) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#businessentityid()} */
  public VjobcandidateViewRow withBusinessentityid(Optional<BusinessentityId> businessentityid) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withNamePrefix(Optional</* max 30 chars */ String> namePrefix) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withNameFirst(Optional</* max 30 chars */ String> nameFirst) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withNameMiddle(Optional</* max 30 chars */ String> nameMiddle) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withNameLast(Optional</* max 30 chars */ String> nameLast) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withNameSuffix(Optional</* max 30 chars */ String> nameSuffix) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withSkills(String skills) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withAddrType(Optional</* max 30 chars */ String> addrType) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withAddrLocCountryRegion(Optional</* max 100 chars */ String> addrLocCountryRegion) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withAddrLocState(Optional</* max 100 chars */ String> addrLocState) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withAddrLocCity(Optional</* max 100 chars */ String> addrLocCity) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withAddrPostalCode(Optional</* max 20 chars */ String> addrPostalCode) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withEMail(String eMail) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  public VjobcandidateViewRow withWebSite(String webSite) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  /** Points to {@link adventureworks.humanresources.jobcandidate.JobcandidateRow#modifieddate()} */
  public VjobcandidateViewRow withModifieddate(TypoLocalDateTime modifieddate) {
    return new VjobcandidateViewRow(jobcandidateid, businessentityid, namePrefix, nameFirst, nameMiddle, nameLast, nameSuffix, skills, addrType, addrLocCountryRegion, addrLocState, addrLocCity, addrPostalCode, eMail, webSite, modifieddate);
  };

  static RowParser<VjobcandidateViewRow> _rowParser = RowParsers.of(JobcandidateId.pgType, BusinessentityId.pgType.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text, PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text.opt(), PgTypes.text, PgTypes.text, TypoLocalDateTime.pgType, VjobcandidateViewRow::new, row -> new Object[]{row.jobcandidateid(), row.businessentityid(), row.namePrefix(), row.nameFirst(), row.nameMiddle(), row.nameLast(), row.nameSuffix(), row.skills(), row.addrType(), row.addrLocCountryRegion(), row.addrLocState(), row.addrLocCity(), row.addrPostalCode(), row.eMail(), row.webSite(), row.modifieddate()});;
}