/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase

import adventureworks.Text
import java.sql.Types
import typr.dsl.Bijection
import typr.dsl.PGType
import zio.jdbc.JdbcDecoder
import zio.jdbc.JdbcEncoder
import zio.jdbc.SqlFragment.Setter
import zio.json.JsonDecoder
import zio.json.JsonEncoder

/** Domain `showcase.phone_number`
 * Constraint: CHECK (((VALUE)::text ~ '^\+?[0-9\s\-\(\)]{7,20}$'::text))
 */
case class PhoneNumber(value: String)

object PhoneNumber {
  implicit lazy val arrayJdbcDecoder: JdbcDecoder[Array[PhoneNumber]] = adventureworks.StringArrayDecoder.map(_.map(PhoneNumber.apply))

  implicit lazy val arrayJdbcEncoder: JdbcEncoder[Array[PhoneNumber]] = adventureworks.StringArrayEncoder.contramap(_.map(_.value))

  implicit lazy val arraySetter: Setter[Array[PhoneNumber]] = adventureworks.StringArraySetter.contramap(_.map(_.value))

  implicit lazy val bijection: Bijection[PhoneNumber, String] = Bijection.apply[PhoneNumber, String](_.value)(PhoneNumber.apply)

  implicit lazy val jdbcDecoder: JdbcDecoder[PhoneNumber] = JdbcDecoder.stringDecoder.map(PhoneNumber.apply)

  implicit lazy val jdbcEncoder: JdbcEncoder[PhoneNumber] = JdbcEncoder.stringEncoder.contramap(_.value)

  implicit lazy val jsonDecoder: JsonDecoder[PhoneNumber] = JsonDecoder.string.map(PhoneNumber.apply)

  implicit lazy val jsonEncoder: JsonEncoder[PhoneNumber] = JsonEncoder.string.contramap(_.value)

  implicit lazy val pgText: Text[PhoneNumber] = {
    new Text[PhoneNumber] {
      override def unsafeEncode(v: PhoneNumber, sb: StringBuilder): Unit = Text.stringInstance.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: PhoneNumber, sb: StringBuilder): Unit = Text.stringInstance.unsafeArrayEncode(v.value, sb)
    }
  }

  implicit lazy val pgType: PGType[PhoneNumber] = PGType.instance(""""showcase"."phone_number"""", Types.OTHER)

  implicit lazy val setter: Setter[PhoneNumber] = Setter.stringSetter.contramap(_.value)
}