/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.c

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.production.culture.CultureId
import adventureworks.public.Name
import java.util.Optional
import typo.dsl.Path
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.Structure.Relation

trait CViewFields {
  def id: Field[CultureId, CViewRow]

  def cultureid: Field[CultureId, CViewRow]

  def name: Field[Name, CViewRow]

  def modifieddate: Field[TypoLocalDateTime, CViewRow]
}

object CViewFields {
  private final class Impl(path: java.util.List[Path]) extends Relation[CViewFields, CViewRow](path) {

    override lazy val fields: CViewFields = {
      new CViewFields {
        def id: Field[CultureId, CViewRow] = {
          new Field[CultureId, CViewRow](
            _path,
            "id",
            _.id,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(id = value),
            CultureId.pgType
          )
        }
        def cultureid: Field[CultureId, CViewRow] = {
          new Field[CultureId, CViewRow](
            _path,
            "cultureid",
            _.cultureid,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(cultureid = value),
            CultureId.pgType
          )
        }
        def name: Field[Name, CViewRow] = {
          new Field[Name, CViewRow](
            _path,
            "name",
            _.name,
            Optional.empty(),
            Optional.empty(),
            (row, value) => row.copy(name = value),
            Name.pgType
          )
        }
        def modifieddate: Field[TypoLocalDateTime, CViewRow] = {
          new Field[TypoLocalDateTime, CViewRow](
            _path,
            "modifieddate",
            _.modifieddate,
            Optional.of("text"),
            Optional.empty(),
            (row, value) => row.copy(modifieddate = value),
            TypoLocalDateTime.pgType
          )
        }
      }
    }

    override lazy val columns: java.util.List[FieldLike[?, CViewRow]] = java.util.List.of(this.fields.id, this.fields.cultureid, this.fields.name, this.fields.modifieddate)

    def copy(path: java.util.List[Path]): Impl = new Impl(path)
  }

  lazy val structure: Relation[CViewFields, CViewRow] = new Impl(java.util.List.of())
}