/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase

import adventureworks.Text
import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import java.sql.Types
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typr.dsl.Bijection

/** Domain `showcase.percentage`
 * Constraint: CHECK (((VALUE >= (0)::numeric) AND (VALUE <= (100)::numeric)))
 */
case class Percentage(value: BigDecimal)

object Percentage {
  implicit lazy val arrayColumn: Column[Array[Percentage]] = Column.columnToArray(column, implicitly)

  implicit lazy val arrayToStatement: ToStatement[Array[Percentage]] = adventureworks.BigDecimalArrayToStatement.contramap(_.map(_.value))

  implicit lazy val bijection: Bijection[Percentage, BigDecimal] = Bijection.apply[Percentage, BigDecimal](_.value)(Percentage.apply)

  implicit lazy val column: Column[Percentage] = Column.columnToScalaBigDecimal.map(Percentage.apply)

  implicit lazy val parameterMetadata: ParameterMetaData[Percentage] = {
    new ParameterMetaData[Percentage] {
      override def sqlType: String = """"showcase"."percentage""""
      override def jdbcType: Int = Types.OTHER
    }
  }

  implicit lazy val pgText: Text[Percentage] = {
    new Text[Percentage] {
      override def unsafeEncode(v: Percentage, sb: StringBuilder): Unit = Text.bigDecimalInstance.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: Percentage, sb: StringBuilder): Unit = Text.bigDecimalInstance.unsafeArrayEncode(v.value, sb)
    }
  }

  implicit lazy val reads: Reads[Percentage] = Reads.bigDecReads.map(Percentage.apply)

  implicit lazy val toStatement: ToStatement[Percentage] = ToStatement.scalaBigDecimalToStatement.contramap(_.value)

  implicit lazy val writes: Writes[Percentage] = Writes.BigDecimalWrites.contramap(_.value)
}