/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase

import adventureworks.Text
import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import java.sql.Types
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import typr.dsl.Bijection

/** Domain `showcase.postal_code`
 * Constraint: CHECK (((VALUE)::text ~ '^[A-Z0-9\-\s]{3,20}$'::text))
 */
case class PostalCode(value: String)

object PostalCode {
  implicit lazy val arrayColumn: Column[Array[PostalCode]] = Column.columnToArray(column, implicitly)

  implicit lazy val arrayToStatement: ToStatement[Array[PostalCode]] = ToStatement.arrayToParameter(ParameterMetaData.StringParameterMetaData).contramap(_.map(_.value))

  implicit lazy val bijection: Bijection[PostalCode, String] = Bijection.apply[PostalCode, String](_.value)(PostalCode.apply)

  implicit lazy val column: Column[PostalCode] = Column.columnToString.map(PostalCode.apply)

  implicit lazy val parameterMetadata: ParameterMetaData[PostalCode] = {
    new ParameterMetaData[PostalCode] {
      override def sqlType: String = """"showcase"."postal_code""""
      override def jdbcType: Int = Types.OTHER
    }
  }

  implicit lazy val pgText: Text[PostalCode] = {
    new Text[PostalCode] {
      override def unsafeEncode(v: PostalCode, sb: StringBuilder): Unit = Text.stringInstance.unsafeEncode(v.value, sb)
      override def unsafeArrayEncode(v: PostalCode, sb: StringBuilder): Unit = Text.stringInstance.unsafeArrayEncode(v.value, sb)
    }
  }

  implicit lazy val reads: Reads[PostalCode] = Reads.StringReads.map(PostalCode.apply)

  implicit lazy val toStatement: ToStatement[PostalCode] = ToStatement.stringToStatement.contramap(_.value)

  implicit lazy val writes: Writes[PostalCode] = Writes.StringWrites.contramap(_.value)
}