/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.update_person

import adventureworks.customtypes.TypoLocalDateTime
import java.sql.Connection
import java.util.Optional

trait UpdatePersonSqlRepo {
  def apply(
    suffix: String,
    cutoff: Optional[TypoLocalDateTime]
  )(using c: Connection): Integer
}