/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.showcase

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.foundations.PgType
import dev.typr.foundations.scala.Bijection
import dev.typr.foundations.scala.ScalaDbTypes

/** Domain `showcase.percentage`
 * Constraint: CHECK (((VALUE >= (0)::numeric) AND (VALUE <= (100)::numeric)))
 */
case class Percentage(@JsonValue value: BigDecimal)

object Percentage {
  given bijection: Bijection[Percentage, BigDecimal] = Bijection.apply[Percentage, BigDecimal](_.value)(Percentage.apply)

  given pgType: PgType[Percentage] = ScalaDbTypes.PgTypes.numeric.bimap(Percentage.apply, _.value).renamed(""""showcase"."percentage"""")

  given pgTypeArray: PgType[Array[Percentage]] = ScalaDbTypes.PgTypes.numericArray.bimap(xs => xs.map(Percentage.apply), xs => xs.map(_.value)).renamed(""""showcase"."percentage"[]""")
}