/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.order;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import typo.dsl.DeleteBuilder;
import typo.dsl.DeleteBuilder.DeleteBuilderMock;
import typo.dsl.DeleteParams;
import typo.dsl.SelectBuilder;
import typo.dsl.SelectBuilderMock;
import typo.dsl.SelectParams;
import typo.dsl.UpdateBuilder;
import typo.dsl.UpdateBuilder.UpdateBuilderMock;
import typo.dsl.UpdateParams;
import static typo.runtime.internal.stringInterpolator.str;

public record OrderRepoMock(
  java.util.function.Function<OrderRowUnsaved, OrderRow> toRow,
  HashMap<OrderId, OrderRow> map
) implements OrderRepo {
  public OrderRepoMock(java.util.function.Function<OrderRowUnsaved, OrderRow> toRow) {
    this(toRow, new HashMap<OrderId, OrderRow>());
  };

  public OrderRepoMock withToRow(java.util.function.Function<OrderRowUnsaved, OrderRow> toRow) {
    return new OrderRepoMock(toRow, map);
  };

  public OrderRepoMock withMap(HashMap<OrderId, OrderRow> map) {
    return new OrderRepoMock(toRow, map);
  };

  public DeleteBuilder<OrderFields, OrderRow> delete() {
    return new DeleteBuilderMock<>(OrderFields.structure(), () -> new ArrayList<>(map.values()), DeleteParams.empty(), row -> row.id(), id -> map.remove(id));
  };

  public Boolean deleteById(
    OrderId id,
    Connection c
  ) {
    return Optional.ofNullable(map.remove(id)).isPresent();
  };

  public Integer deleteByIds(
    OrderId[] ids,
    Connection c
  ) {
    var count = 0;
      for (var id : ids) { if (Optional.ofNullable(map.remove(id)).isPresent()) {
        count = count + 1;
      } };
    return count;
  };

  public OrderRow insert(
    OrderRow unsaved,
    Connection c
  ) {
    if (map.containsKey(unsaved.id())) {
        throw new RuntimeException(str("id $unsaved.id() already exists"));
      };
      map.put(unsaved.id(), unsaved);
    return unsaved;
  };

  public OrderRow insert(
    OrderRowUnsaved unsaved,
    Connection c
  ) {
    return insert(toRow.apply(unsaved), c);
  };

  public Long insertStreaming(
    Iterator<OrderRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        count = count + 1L;
      };
    return count;
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<OrderRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0L;
      while (unsaved.hasNext()) {
        var unsavedRow = unsaved.next();
        var row = toRow.apply(unsavedRow);
        map.put(row.id(), row);
        count = count + 1L;
      };
    return count;
  };

  public SelectBuilder<OrderFields, OrderRow> select() {
    return new SelectBuilderMock<>(OrderFields.structure(), () -> new ArrayList<>(map.values()), SelectParams.empty());
  };

  public List<OrderRow> selectAll(Connection c) {
    return new ArrayList<>(map.values());
  };

  public Optional<OrderRow> selectById(
    OrderId id,
    Connection c
  ) {
    return Optional.ofNullable(map.get(id));
  };

  public List<OrderRow> selectByIds(
    OrderId[] ids,
    Connection c
  ) {
    var result = new ArrayList<OrderRow>();
      for (var id : ids) { var opt = Optional.ofNullable(map.get(id));
      if (opt.isPresent()) result.add(opt.get()); };
    return result;
  };

  public Map<OrderId, OrderRow> selectByIdsTracked(
    OrderId[] ids,
    Connection c
  ) {
    return selectByIds(ids, c).stream().collect(Collectors.toMap((frontpage.frontpage.order.OrderRow row) -> row.id(), Function.identity()));
  };

  public UpdateBuilder<OrderFields, OrderRow> update() {
    return new UpdateBuilderMock<>(OrderFields.structure(), () -> new ArrayList<>(map.values()), UpdateParams.empty(), row -> row);
  };

  public Boolean update(
    OrderRow row,
    Connection c
  ) {
    var shouldUpdate = Optional.ofNullable(map.get(row.id())).filter(oldRow -> !oldRow.equals(row)).isPresent();
      if (shouldUpdate) {
        map.put(row.id(), row);
      };
    return shouldUpdate;
  };

  public OrderRow upsert(
    OrderRow unsaved,
    Connection c
  ) {
    map.put(unsaved.id(), unsaved);
    return unsaved;
  };

  public List<OrderRow> upsertBatch(
    Iterator<OrderRow> unsaved,
    Connection c
  ) {
    var result = new ArrayList<OrderRow>();
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        result.add(row);
      };
    return result;
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<OrderRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    var count = 0;
      while (unsaved.hasNext()) {
        var row = unsaved.next();
        map.put(row.id(), row);
        count = count + 1;
      };
    return count;
  };
}