/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.order;

import frontpage.customtypes.TypoLocalDateTime;
import frontpage.frontpage.OrderStatus;
import frontpage.frontpage.product.ProductFields;
import frontpage.frontpage.product.ProductId;
import frontpage.frontpage.product.ProductRow;
import frontpage.frontpage.user.UserFields;
import frontpage.frontpage.user.UserId;
import frontpage.frontpage.user.UserRow;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import typo.dsl.ForeignKey;
import typo.dsl.Path;
import typo.dsl.SqlExpr.Field;
import typo.dsl.SqlExpr.FieldLike;
import typo.dsl.SqlExpr.IdField;
import typo.dsl.SqlExpr.OptField;
import typo.dsl.Structure.Relation;
import typo.runtime.PgTypes;

public interface OrderFields {
  static final class Impl extends Relation<OrderFields, OrderRow> {
    Impl(List<Path> path) {
      super(path);
    }

    @Override
    public OrderFields fields() {
      return new OrderFields() {
               public IdField<OrderId, OrderRow> id() {
                 return new IdField<OrderId, OrderRow>(_path, "id", OrderRow::id, Optional.empty(), Optional.of("uuid"), (row, value) -> row.withId(value), OrderId.pgType);
               };
               public OptField<UserId, OrderRow> userId() {
                 return new OptField<UserId, OrderRow>(_path, "user_id", OrderRow::userId, Optional.empty(), Optional.of("uuid"), (row, value) -> row.withUserId(value), UserId.pgType);
               };
               public OptField<ProductId, OrderRow> productId() {
                 return new OptField<ProductId, OrderRow>(_path, "product_id", OrderRow::productId, Optional.empty(), Optional.of("uuid"), (row, value) -> row.withProductId(value), ProductId.pgType);
               };
               public OptField<OrderStatus, OrderRow> status() {
                 return new OptField<OrderStatus, OrderRow>(_path, "status", OrderRow::status, Optional.empty(), Optional.of("frontpage.order_status"), (row, value) -> row.withStatus(value), OrderStatus.pgType);
               };
               public Field<BigDecimal, OrderRow> total() {
                 return new Field<BigDecimal, OrderRow>(_path, "total", OrderRow::total, Optional.empty(), Optional.of("numeric"), (row, value) -> row.withTotal(value), PgTypes.numeric);
               };
               public OptField<TypoLocalDateTime, OrderRow> createdAt() {
                 return new OptField<TypoLocalDateTime, OrderRow>(_path, "created_at", OrderRow::createdAt, Optional.of("text"), Optional.of("timestamp"), (row, value) -> row.withCreatedAt(value), TypoLocalDateTime.pgType);
               };
               public OptField<TypoLocalDateTime, OrderRow> shippedAt() {
                 return new OptField<TypoLocalDateTime, OrderRow>(_path, "shipped_at", OrderRow::shippedAt, Optional.of("text"), Optional.of("timestamp"), (row, value) -> row.withShippedAt(value), TypoLocalDateTime.pgType);
               };
             };
    };

    @Override
    public List<FieldLike<?, OrderRow>> columns() {
      return List.of(this.fields().id(), this.fields().userId(), this.fields().productId(), this.fields().status(), this.fields().total(), this.fields().createdAt(), this.fields().shippedAt());
    };

    public Impl copy(List<Path> path) {
      return new Impl(path);
    };
  };

  static Relation<OrderFields, OrderRow> structure() {
    return new Impl(List.of());
  };

  IdField<OrderId, OrderRow> id();

  OptField<UserId, OrderRow> userId();

  OptField<ProductId, OrderRow> productId();

  OptField<OrderStatus, OrderRow> status();

  Field<BigDecimal, OrderRow> total();

  OptField<TypoLocalDateTime, OrderRow> createdAt();

  OptField<TypoLocalDateTime, OrderRow> shippedAt();

  default ForeignKey<ProductFields, ProductRow> fkProduct() {
    return ForeignKey.<ProductFields, ProductRow>of("frontpage.order_product_id_fkey").withColumnPair(productId(), ProductFields::id);
  };

  default ForeignKey<UserFields, UserRow> fkUser() {
    return ForeignKey.<UserFields, UserRow>of("frontpage.order_user_id_fkey").withColumnPair(userId(), UserFields::id);
  };
}