/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.role;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.PgTypes;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public class RoleRepoImpl implements RoleRepo {
  public DeleteBuilder<RoleFields, RoleRow> delete() {
    return DeleteBuilder.of("frontpage.role", RoleFields.structure());
  };

  public Boolean deleteById(
    RoleId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "frontpage"."role" where "id" = 
      """),
      RoleId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  public Integer deleteByIds(
    RoleId[] ids,
    Connection c
  ) {
    return interpolate(
               typo.runtime.Fragment.lit("""
                  delete
                  from "frontpage"."role"
                  where "id" = ANY("""),
               RoleId.pgTypeArray.encode(ids),
               typo.runtime.Fragment.lit(")")
             )
      .update()
      .runUnchecked(c);
  };

  public RoleRow insert(
    RoleRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."role"("id", "name")
         values ("""),
      RoleId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         returning "id", "name"
      """)
    )
      .updateReturning(RoleRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public RoleRow insert(
    RoleRowUnsaved unsaved,
    Connection c
  ) {
    List<Literal> columns = new ArrayList<>();;
      List<Fragment> values = new ArrayList<>();;
      columns.add(Fragment.lit("\"name\""));
      values.add(interpolate(
        PgTypes.text.encode(unsaved.name()),
        typo.runtime.Fragment.lit("""
        """)
      ));
      unsaved.id().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"id\""));
          values.add(interpolate(
            RoleId.pgType.encode(value),
            typo.runtime.Fragment.lit("::uuid")
          ));
        }
      );;
      Fragment q = interpolate(
        typo.runtime.Fragment.lit("""
        insert into "frontpage"."role"(
        """),
        Fragment.comma(columns),
        typo.runtime.Fragment.lit("""
           )
           values ("""),
        Fragment.comma(values),
        typo.runtime.Fragment.lit("""
           )
           returning "id", "name"
        """)
      );;
    return q.updateReturning(RoleRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public Long insertStreaming(
    Iterator<RoleRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."role"("id", "name") FROM STDIN
    """), batchSize, unsaved, c, RoleRow.pgText);
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<RoleRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."role"("name", "id") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')
    """), batchSize, unsaved, c, RoleRowUnsaved.pgText);
  };

  public SelectBuilder<RoleFields, RoleRow> select() {
    return SelectBuilder.of("frontpage.role", RoleFields.structure(), RoleRow._rowParser);
  };

  public List<RoleRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "name"
       from "frontpage"."role"
    """)).as(RoleRow._rowParser.all()).runUnchecked(c);
  };

  public Optional<RoleRow> selectById(
    RoleId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name"
         from "frontpage"."role"
         where "id" = """),
      RoleId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).as(RoleRow._rowParser.first()).runUnchecked(c);
  };

  public List<RoleRow> selectByIds(
    RoleId[] ids,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name"
         from "frontpage"."role"
         where "id" = ANY("""),
      RoleId.pgTypeArray.encode(ids),
      typo.runtime.Fragment.lit(")")
    ).as(RoleRow._rowParser.all()).runUnchecked(c);
  };

  public Map<RoleId, RoleRow> selectByIdsTracked(
    RoleId[] ids,
    Connection c
  ) {
    Map<RoleId, RoleRow> ret = new HashMap<>();;
      selectByIds(ids, c).forEach(row -> ret.put(row.id(), row));
    return ret;
  };

  public Optional<RoleRow> selectByUniqueName(
    String name,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name"
         from "frontpage"."role"
         where "name" = """),
      PgTypes.text.encode(name),
      typo.runtime.Fragment.lit("""


      """)
    ).as(RoleRow._rowParser.first()).runUnchecked(c);
  };

  public UpdateBuilder<RoleFields, RoleRow> update() {
    return UpdateBuilder.of("frontpage.role", RoleFields.structure(), RoleRow._rowParser.all());
  };

  public Boolean update(
    RoleRow row,
    Connection c
  ) {
    RoleId id = row.id();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "frontpage"."role"
                set "name" = """),
             PgTypes.text.encode(row.name()),
             typo.runtime.Fragment.lit("""
   
                where "id" = """),
             RoleId.pgType.encode(id),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };

  public RoleRow upsert(
    RoleRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."role"("id", "name")
         values ("""),
      RoleId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         on conflict ("id")
         do update set
           "name" = EXCLUDED."name"
         returning "id", "name"
      """)
    )
      .updateReturning(RoleRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  public List<RoleRow> upsertBatch(
    Iterator<RoleRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "frontpage"."role"("id", "name")
                values (?::uuid, ?)
                on conflict ("id")
                do update set
                  "name" = EXCLUDED."name"
                returning "id", "name"
             """))
      .updateManyReturning(RoleRow._rowParser, unsaved)
      .runUnchecked(c);
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<RoleRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table role_TEMP (like "frontpage"."role") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy role_TEMP("id", "name") from stdin
      """), batchSize, unsaved, c, RoleRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "frontpage"."role"("id", "name")
              select * from role_TEMP
              on conflict ("id")
              do update set
                "name" = EXCLUDED."name"
              ;
              drop table role_TEMP;""")).update().runUnchecked(c);
  };
}