/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.product_category

import anorm.ToParameterValue
import frontpage.frontpage.category.CategoryFields
import frontpage.frontpage.category.CategoryId
import frontpage.frontpage.category.CategoryRow
import frontpage.frontpage.product.ProductFields
import frontpage.frontpage.product.ProductId
import frontpage.frontpage.product.ProductRow
import typo.dsl.ForeignKey
import typo.dsl.Path
import typo.dsl.SqlExpr
import typo.dsl.SqlExpr.CompositeIn
import typo.dsl.SqlExpr.CompositeIn.TuplePart
import typo.dsl.SqlExpr.Const.As.as
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.SqlExpr.IdField
import typo.dsl.Structure.Relation

trait ProductCategoryFields {
  def productId: IdField[ProductId, ProductCategoryRow]
  def categoryId: IdField[CategoryId, ProductCategoryRow]
  def fkCategory: ForeignKey[CategoryFields, CategoryRow] =
    ForeignKey[CategoryFields, CategoryRow]("frontpage.product_category_category_id_fkey", Nil)
      .withColumnPair(categoryId, _.id)
  def fkProduct: ForeignKey[ProductFields, ProductRow] =
    ForeignKey[ProductFields, ProductRow]("frontpage.product_category_product_id_fkey", Nil)
      .withColumnPair(productId, _.id)
  def compositeIdIs(compositeId: ProductCategoryId): SqlExpr[Boolean] =
    productId.isEqual(compositeId.productId).and(categoryId.isEqual(compositeId.categoryId))
  def compositeIdIn(compositeIds: Array[ProductCategoryId]): SqlExpr[Boolean] =
    new CompositeIn(compositeIds)(TuplePart[ProductCategoryId](productId)(_.productId)(using as[Array[ProductId]](using ToParameterValue(null, ProductId.arrayToStatement), frontpage.arrayParameterMetaData(using ProductId.parameterMetadata)), implicitly), TuplePart[ProductCategoryId](categoryId)(_.categoryId)(using as[Array[CategoryId]](using ToParameterValue(null, CategoryId.arrayToStatement), frontpage.arrayParameterMetaData(using CategoryId.parameterMetadata)), implicitly))

}

object ProductCategoryFields {
  lazy val structure: Relation[ProductCategoryFields, ProductCategoryRow] =
    new Impl(List())

  private final class Impl(val _path: List[Path])
    extends Relation[ProductCategoryFields, ProductCategoryRow] {

    override lazy val fields: ProductCategoryFields = new ProductCategoryFields {
      override def productId = IdField[ProductId, ProductCategoryRow](_path, "product_id", None, Some("uuid"), x => x.productId, (row, value) => row.copy(productId = value))
      override def categoryId = IdField[CategoryId, ProductCategoryRow](_path, "category_id", None, Some("uuid"), x => x.categoryId, (row, value) => row.copy(categoryId = value))
    }

    override lazy val columns: List[FieldLike[?, ProductCategoryRow]] =
      List[FieldLike[?, ProductCategoryRow]](fields.productId, fields.categoryId)

    override def copy(path: List[Path]): Impl =
      new Impl(path)
  }
}
