/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.distinct_type_test

import dev.typr.foundations.scala.DeleteBuilder
import dev.typr.foundations.scala.DeleteBuilderMock
import dev.typr.foundations.scala.DeleteParams
import dev.typr.foundations.scala.SelectBuilder
import dev.typr.foundations.scala.SelectBuilderMock
import dev.typr.foundations.scala.SelectParams
import dev.typr.foundations.scala.UpdateBuilder
import dev.typr.foundations.scala.UpdateBuilderMock
import dev.typr.foundations.scala.UpdateParams
import java.lang.RuntimeException
import java.sql.Connection

case class DistinctTypeTestRepoMock(
  toRow: DistinctTypeTestRowUnsaved => DistinctTypeTestRow,
  map: scala.collection.mutable.Map[DistinctTypeTestId, DistinctTypeTestRow] = scala.collection.mutable.Map.empty[DistinctTypeTestId, DistinctTypeTestRow]
) extends DistinctTypeTestRepo {
  override def delete: DeleteBuilder[DistinctTypeTestFields, DistinctTypeTestRow] = DeleteBuilderMock(DistinctTypeTestFields.structure, () => map.values.toList, DeleteParams.empty(), row => row.id, id => map.remove(id): @scala.annotation.nowarn)

  override def deleteById(id: DistinctTypeTestId)(using c: Connection): Boolean = map.remove(id).isDefined

  override def deleteByIds(ids: Array[DistinctTypeTestId])(using c: Connection): Int = {
    var count = 0
    ids.foreach { id => if (map.remove(id).isDefined) {
      count = count + 1
    } }
    return count
  }

  override def insert(unsaved: DistinctTypeTestRow)(using c: Connection): DistinctTypeTestRow = {
    if (map.contains(unsaved.id)) {
      throw new RuntimeException(s"id ${unsaved.id} already exists")
    }
    map.put(unsaved.id, unsaved): @scala.annotation.nowarn
    return unsaved
  }

  override def insert(unsaved: DistinctTypeTestRowUnsaved)(using c: Connection): DistinctTypeTestRow = insert(toRow(unsaved))(using c)

  override def select: SelectBuilder[DistinctTypeTestFields, DistinctTypeTestRow] = SelectBuilderMock(DistinctTypeTestFields.structure, () => map.values.toList, SelectParams.empty())

  override def selectAll(using c: Connection): List[DistinctTypeTestRow] = map.values.toList

  override def selectById(id: DistinctTypeTestId)(using c: Connection): Option[DistinctTypeTestRow] = map.get(id)

  override def selectByIds(ids: Array[DistinctTypeTestId])(using c: Connection): List[DistinctTypeTestRow] = ids.flatMap(map.get(_)).toList

  override def selectByIdsTracked(ids: Array[DistinctTypeTestId])(using c: Connection): Map[DistinctTypeTestId, DistinctTypeTestRow] = selectByIds(ids)(using c).map(x => (((row: DistinctTypeTestRow) => row.id).apply(x), x)).toMap

  override def update: UpdateBuilder[DistinctTypeTestFields, DistinctTypeTestRow] = UpdateBuilderMock(DistinctTypeTestFields.structure, () => map.values.toList, UpdateParams.empty(), row => row)

  override def update(row: DistinctTypeTestRow)(using c: Connection): Boolean = {
    val shouldUpdate = map.get(row.id).filter(oldRow => (oldRow != row)).isDefined
    if (shouldUpdate) {
      map.put(row.id, row): @scala.annotation.nowarn
    }
    return shouldUpdate
  }

  override def upsert(unsaved: DistinctTypeTestRow)(using c: Connection): Unit = map.put(unsaved.id, unsaved): @scala.annotation.nowarn

  override def upsertBatch(unsaved: Iterator[DistinctTypeTestRow])(using c: Connection): Unit = {
    unsaved.foreach { row =>
      map.put(row.id, row): @scala.annotation.nowarn
    }
  }
}