/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.distinct_type_test

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.scala.DbTypeOps
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import testdb.EmailAddress
import testdb.MoneyAmount

/** Table: DISTINCT_TYPE_TEST
 * Primary key: ID
 */
case class DistinctTypeTestRow(
  /** Identity ALWAYS */
  @JsonProperty("ID") id: DistinctTypeTestId,
  @JsonProperty("EMAIL") email: EmailAddress,
  @JsonProperty("BALANCE") balance: Option[MoneyAmount]
) {
  def toUnsavedRow: DistinctTypeTestRowUnsaved = new DistinctTypeTestRowUnsaved(email, balance)
}

object DistinctTypeTestRow {
  val `_rowParser`: RowParser[DistinctTypeTestRow] = RowParsers.of(DistinctTypeTestId.pgType, EmailAddress.pgType, MoneyAmount.pgType.nullable)(DistinctTypeTestRow.apply)(row => Array[Any](row.id, row.email, row.balance))
}