/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.order_items

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.Db2Types
import dev.typr.foundations.kotlin.KotlinDbTypes
import dev.typr.foundations.kotlin.RowParser
import dev.typr.foundations.kotlin.RowParsers
import java.math.BigDecimal
import testdb.orders.OrdersId

/** Table: ORDER_ITEMS
  * Composite primary key: ORDER_ID, ITEM_NUMBER
  */
data class OrderItemsRow(
  /** Points to [testdb.orders.OrdersRow.orderId] */
  @JsonProperty("ORDER_ID") val orderId: OrdersId,
  @JsonProperty("ITEM_NUMBER") val itemNumber: Int,
  @JsonProperty("PRODUCT_NAME") val productName: String,
  @JsonProperty("QUANTITY") val quantity: Int,
  @JsonProperty("UNIT_PRICE") val unitPrice: BigDecimal
) {
  fun compositeId(): OrderItemsId = OrderItemsId(orderId, itemNumber)

  fun id(): OrderItemsId = this.compositeId()

  companion object {
    val _rowParser: RowParser<OrderItemsRow> = RowParsers.of(OrdersId.pgType, KotlinDbTypes.Db2Types.integer, Db2Types.varchar, KotlinDbTypes.Db2Types.integer, KotlinDbTypes.Db2Types.decimal, { t0, t1, t2, t3, t4 -> OrderItemsRow(t0, t1, t2, t3, t4) }, { row -> arrayOf<Any?>(row.orderId, row.itemNumber, row.productName, row.quantity, row.unitPrice) })

    fun apply(
      compositeId: OrderItemsId,
      productName: String,
      quantity: Int,
      unitPrice: BigDecimal
    ): OrderItemsRow = OrderItemsRow(compositeId.orderId, compositeId.itemNumber, productName, quantity, unitPrice)
  }
}