/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.only_pk_columns

import typo.runtime.PgText
import typo.runtime.PgTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers
import typo.runtime.RowParsers.Tuple2

/** Table: public.only_pk_columns
 * Composite primary key: key_column_1, key_column_2
 */
case class OnlyPkColumnsRow(
  keyColumn1: String,
  keyColumn2: Integer
) {
  def compositeId: OnlyPkColumnsId = new OnlyPkColumnsId(keyColumn1, keyColumn2)

  def id: OnlyPkColumnsId = this.compositeId
}

object OnlyPkColumnsRow {
  val `_rowParser`: RowParser[OnlyPkColumnsRow] = RowParsers.of(PgTypes.text, PgTypes.int4, OnlyPkColumnsRow.apply, row => new Tuple2(row.keyColumn1, row.keyColumn2))

  def apply(compositeId: OnlyPkColumnsId): OnlyPkColumnsRow = new OnlyPkColumnsRow(compositeId.keyColumn1, compositeId.keyColumn2)

  given pgText: PgText[OnlyPkColumnsRow] = PgText.from(`_rowParser`)
}