/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.a

import java.sql.Connection
import typo.scaladsl.Dialect
import typo.scaladsl.SelectBuilder
import typo.scaladsl.Fragment.sql

class AViewRepoImpl extends AViewRepo {
  override def select: SelectBuilder[AViewFields, AViewRow] = SelectBuilder.of(""""pe"."a"""", AViewFields.structure, AViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): List[AViewRow] = {
    sql"""select "id", "addressid", "addressline1", "addressline2", "city", "stateprovinceid", "postalcode", "spatiallocation", "rowguid", "modifieddate"
    from "pe"."a"
    """.query(AViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}