/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.vsalesperson

import java.sql.Connection
import typo.scaladsl.Dialect
import typo.scaladsl.SelectBuilder
import typo.scaladsl.Fragment.sql

class VsalespersonViewRepoImpl extends VsalespersonViewRepo {
  override def select: SelectBuilder[VsalespersonViewFields, VsalespersonViewRow] = SelectBuilder.of(""""sales"."vsalesperson"""", VsalespersonViewFields.structure, VsalespersonViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): List[VsalespersonViewRow] = {
    sql"""select "businessentityid", "title", "firstname", "middlename", "lastname", "suffix", "jobtitle", "phonenumber", "phonenumbertype", "emailaddress", "emailpromotion", "addressline1", "addressline2", "city", "stateprovincename", "postalcode", "countryregionname", "territoryname", "territorygroup", "salesquota", "salesytd", "saleslastyear"
    from "sales"."vsalesperson"
    """.query(VsalespersonViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}