/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.currency

import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import java.util.function.Function
import java.util.stream.Collectors
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class CurrencyRepoMock(
  toRow: CurrencyRowUnsaved => CurrencyRow,
  map: HashMap[CurrencyId, CurrencyRow] = new HashMap[CurrencyId, CurrencyRow]()
) extends CurrencyRepo {
  def delete: DeleteBuilder[CurrencyFields, CurrencyRow] = {
    new DeleteBuilderMock(
      CurrencyFields.structure,
      () => new ArrayList(map.values()),
      DeleteParams.empty(),
      row => row.currencycode,
      id => map.remove(id): @scala.annotation.nowarn
    )
  }

  def deleteById(currencycode: CurrencyId)(using c: Connection): java.lang.Boolean = Optional.ofNullable(map.remove(currencycode)).isPresent()

  def deleteByIds(currencycodes: Array[CurrencyId])(using c: Connection): Integer = {
    var count = 0
    currencycodes.foreach { id => if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1
    } }
    count
  }

  def insert(unsaved: CurrencyRow)(using c: Connection): CurrencyRow = {
    if (map.containsKey(unsaved.currencycode)) {
      throw new RuntimeException(s"id $unsaved.currencycode already exists")
    }
    map.put(unsaved.currencycode, unsaved): @scala.annotation.nowarn
    unsaved
  }

  def insert(unsaved: CurrencyRowUnsaved)(using c: Connection): CurrencyRow = insert(toRow(unsaved))(using c)

  def insertStreaming(
    unsaved: java.util.Iterator[CurrencyRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.currencycode, row): @scala.annotation.nowarn
      count = count + 1L
    }
    count
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[CurrencyRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = {
    var count = 0L
    while (unsaved.hasNext()) {
      val unsavedRow = unsaved.next()
      val row = toRow(unsavedRow)
      map.put(row.currencycode, row): @scala.annotation.nowarn
      count = count + 1L
    }
    count
  }

  def select: SelectBuilder[CurrencyFields, CurrencyRow] = new SelectBuilderMock(CurrencyFields.structure, () => new ArrayList(map.values()), SelectParams.empty())

  def selectAll(using c: Connection): java.util.List[CurrencyRow] = new ArrayList(map.values())

  def selectById(currencycode: CurrencyId)(using c: Connection): Optional[CurrencyRow] = Optional.ofNullable(map.get(currencycode))

  def selectByIds(currencycodes: Array[CurrencyId])(using c: Connection): java.util.List[CurrencyRow] = {
    val result = new ArrayList[CurrencyRow]()
    currencycodes.foreach { id => val opt = Optional.ofNullable(map.get(id))
    if (opt.isPresent()) result.add(opt.get()): @scala.annotation.nowarn }
    result
  }

  def selectByIdsTracked(currencycodes: Array[CurrencyId])(using c: Connection): java.util.Map[CurrencyId, CurrencyRow] = selectByIds(currencycodes)(using c).stream().collect(Collectors.toMap((row: adventureworks.sales.currency.CurrencyRow) => row.currencycode, Function.identity()))

  def update: UpdateBuilder[CurrencyFields, CurrencyRow] = {
    new UpdateBuilderMock(
      CurrencyFields.structure,
      () => new ArrayList(map.values()),
      UpdateParams.empty(),
      row => row
    )
  }

  def update(row: CurrencyRow)(using c: Connection): java.lang.Boolean = {
    val shouldUpdate = Optional.ofNullable(map.get(row.currencycode)).filter(oldRow => !oldRow.equals(row)).isPresent()
    if (shouldUpdate) {
      map.put(row.currencycode, row): @scala.annotation.nowarn
    }
    shouldUpdate
  }

  def upsert(unsaved: CurrencyRow)(using c: Connection): CurrencyRow = {
    map.put(unsaved.currencycode, unsaved): @scala.annotation.nowarn
    unsaved
  }

  def upsertBatch(unsaved: java.util.Iterator[CurrencyRow])(using c: Connection): java.util.List[CurrencyRow] = {
    val result = new ArrayList[CurrencyRow]()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.currencycode, row): @scala.annotation.nowarn
      result.add(row): @scala.annotation.nowarn
    }
    result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[CurrencyRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.currencycode, row): @scala.annotation.nowarn
      count = count + 1
    }
    count
  }
}