/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.user_permission;

import com.fasterxml.jackson.annotation.JsonProperty;
import frontpage.customtypes.Defaulted;
import frontpage.customtypes.TypoLocalDateTime;
import frontpage.frontpage.permission.PermissionId;
import frontpage.frontpage.user.UserId;
import java.util.Optional;
import typo.runtime.PgText;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;
import typo.runtime.RowParsers.Tuple3;

/** Table: frontpage.user_permission
  * Composite primary key: user_id, permission_id
  */
public record UserPermissionRow(
  /** Points to {@link frontpage.frontpage.user.UserRow#id()} */
  @JsonProperty("user_id") UserId userId,
  /** Points to {@link frontpage.frontpage.permission.PermissionRow#id()} */
  @JsonProperty("permission_id") PermissionId permissionId,
  /** Default: now() */
  @JsonProperty("granted_at") Optional<TypoLocalDateTime> grantedAt
) {
  /** Points to {@link frontpage.frontpage.user.UserRow#id()} */
  public UserPermissionRow withUserId(UserId userId) {
    return new UserPermissionRow(userId, permissionId, grantedAt);
  };

  /** Points to {@link frontpage.frontpage.permission.PermissionRow#id()} */
  public UserPermissionRow withPermissionId(PermissionId permissionId) {
    return new UserPermissionRow(userId, permissionId, grantedAt);
  };

  /** Default: now() */
  public UserPermissionRow withGrantedAt(Optional<TypoLocalDateTime> grantedAt) {
    return new UserPermissionRow(userId, permissionId, grantedAt);
  };

  static RowParser<UserPermissionRow> _rowParser = RowParsers.of(UserId.pgType, PermissionId.pgType, TypoLocalDateTime.pgType.opt(), UserPermissionRow::new, row -> new Tuple3<>(row.userId(), row.permissionId(), row.grantedAt()));;

  static public UserPermissionRow apply(
    UserPermissionId compositeId,
    Optional<TypoLocalDateTime> grantedAt
  ) {
    return new UserPermissionRow(compositeId.userId(), compositeId.permissionId(), grantedAt);
  };

  static public PgText<UserPermissionRow> pgText =
    PgText.from(_rowParser);

  public UserPermissionId compositeId() {
    return new UserPermissionId(userId, permissionId);
  };

  public UserPermissionId id() {
    return this.compositeId();
  };

  public UserPermissionRowUnsaved toUnsavedRow(Defaulted<Optional<TypoLocalDateTime>> grantedAt) {
    return new UserPermissionRowUnsaved(userId, permissionId, grantedAt);
  };
}