/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.scrapreason

import adventureworks.public.Name
import java.time.LocalDateTime
import java.util.Optional
import typo.dsl.FieldsExpr0
import typo.dsl.Path
import typo.dsl.RelationStructure
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.SqlExpr.IdField
import typo.runtime.PgTypes
import typo.runtime.RowParser

trait ScrapreasonFields extends FieldsExpr0[ScrapreasonRow] {
  def scrapreasonid: IdField[ScrapreasonId, ScrapreasonRow]

  def name: Field[Name, ScrapreasonRow]

  def modifieddate: Field[LocalDateTime, ScrapreasonRow]

  override def columns: java.util.List[FieldLike[?, ScrapreasonRow]]

  override def rowParser: RowParser[ScrapreasonRow] = ScrapreasonRow._rowParser
}

object ScrapreasonFields {
  case class Impl(val `_path`: java.util.List[Path]) extends ScrapreasonFields with RelationStructure[ScrapreasonFields, ScrapreasonRow] {

    override def scrapreasonid: IdField[ScrapreasonId, ScrapreasonRow] = {
      new IdField[ScrapreasonId, ScrapreasonRow](
        _path,
        "scrapreasonid",
        _.scrapreasonid,
        Optional.empty(),
        Optional.of("int4"),
        (row, value) => row.copy(scrapreasonid = value),
        ScrapreasonId.pgType
      )
    }

    override def name: Field[Name, ScrapreasonRow] = {
      new Field[Name, ScrapreasonRow](
        _path,
        "name",
        _.name,
        Optional.empty(),
        Optional.of("varchar"),
        (row, value) => row.copy(name = value),
        Name.pgType
      )
    }

    override def modifieddate: Field[LocalDateTime, ScrapreasonRow] = {
      new Field[LocalDateTime, ScrapreasonRow](
        _path,
        "modifieddate",
        _.modifieddate,
        Optional.empty(),
        Optional.of("timestamp"),
        (row, value) => row.copy(modifieddate = value),
        PgTypes.timestamp
      )
    }

    override def columns: java.util.List[FieldLike[?, ScrapreasonRow]] = java.util.List.of(this.scrapreasonid, this.name, this.modifieddate)

    override def withPaths(`_path`: java.util.List[Path]): RelationStructure[ScrapreasonFields, ScrapreasonRow] = new Impl(`_path`)
  }

  def structure: Impl = new Impl(java.util.Collections.emptyList())
}