/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package oracledb.contacts

import dev.typr.foundations.scala.DeleteBuilder
import dev.typr.foundations.scala.DeleteBuilderMock
import dev.typr.foundations.scala.DeleteParams
import dev.typr.foundations.scala.SelectBuilder
import dev.typr.foundations.scala.SelectBuilderMock
import dev.typr.foundations.scala.SelectParams
import dev.typr.foundations.scala.UpdateBuilder
import dev.typr.foundations.scala.UpdateBuilderMock
import dev.typr.foundations.scala.UpdateParams
import java.lang.RuntimeException
import java.sql.Connection

case class ContactsRepoMock(
  toRow: ContactsRowUnsaved => ContactsRow,
  map: scala.collection.mutable.Map[ContactsId, ContactsRow] = scala.collection.mutable.Map.empty[ContactsId, ContactsRow]
) extends ContactsRepo {
  override def delete: DeleteBuilder[ContactsFields, ContactsRow] = DeleteBuilderMock(ContactsFields.structure, () => map.values.toList, DeleteParams.empty(), row => row.contactId, id => map.remove(id): @scala.annotation.nowarn)

  override def deleteById(contactId: ContactsId)(using c: Connection): Boolean = map.remove(contactId).isDefined

  override def deleteByIds(contactIds: Array[ContactsId])(using c: Connection): Int = {
    var count = 0
    contactIds.foreach { id => if (map.remove(id).isDefined) {
      count = count + 1
    } }
    return count
  }

  override def insert(unsaved: ContactsRow)(using c: Connection): ContactsId = {
    if (map.contains(unsaved.contactId)) {
      throw new RuntimeException(s"id ${unsaved.contactId} already exists")
    }
    map.put(unsaved.contactId, unsaved): @scala.annotation.nowarn
    return unsaved.contactId
  }

  override def insert(unsaved: ContactsRowUnsaved)(using c: Connection): ContactsId = insert(toRow(unsaved))(using c)

  override def select: SelectBuilder[ContactsFields, ContactsRow] = SelectBuilderMock(ContactsFields.structure, () => map.values.toList, SelectParams.empty())

  override def selectAll(using c: Connection): List[ContactsRow] = map.values.toList

  override def selectById(contactId: ContactsId)(using c: Connection): Option[ContactsRow] = map.get(contactId)

  override def selectByIds(contactIds: Array[ContactsId])(using c: Connection): List[ContactsRow] = contactIds.flatMap(map.get(_)).toList

  override def selectByIdsTracked(contactIds: Array[ContactsId])(using c: Connection): Map[ContactsId, ContactsRow] = selectByIds(contactIds)(using c).map(x => (((row: ContactsRow) => row.contactId).apply(x), x)).toMap

  override def update: UpdateBuilder[ContactsFields, ContactsRow] = UpdateBuilderMock(ContactsFields.structure, () => map.values.toList, UpdateParams.empty(), row => row)

  override def update(row: ContactsRow)(using c: Connection): Boolean = {
    val shouldUpdate = map.get(row.contactId).filter(oldRow => (oldRow != row)).isDefined
    if (shouldUpdate) {
      map.put(row.contactId, row): @scala.annotation.nowarn
    }
    return shouldUpdate
  }

  override def upsert(unsaved: ContactsRow)(using c: Connection): Unit = map.put(unsaved.contactId, unsaved): @scala.annotation.nowarn

  override def upsertBatch(unsaved: Iterator[ContactsRow])(using c: Connection): Unit = {
    unsaved.foreach { row =>
      map.put(row.contactId, row): @scala.annotation.nowarn
    }
  }
}