/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package oracledb.customer_search

import com.fasterxml.jackson.annotation.JsonProperty
import dev.typr.foundations.OracleTypes
import dev.typr.foundations.Tuple.Tuple5
import dev.typr.foundations.scala.DbTypeOps
import dev.typr.foundations.scala.RowParser
import dev.typr.foundations.scala.RowParsers
import java.time.LocalDateTime
import oracledb.AddressT
import oracledb.MoneyT
import oracledb.customers.CustomersId

/** SQL file: customer_search.sql */
case class CustomerSearchSqlRow(
  /** Points to [[oracledb.customers.CustomersRow.customerId]] */
  @JsonProperty("CUSTOMER_ID") customerId: CustomersId,
  /** Points to [[oracledb.customers.CustomersRow.name]] */
  @JsonProperty("NAME") name: String,
  /** Points to [[oracledb.customers.CustomersRow.billingAddress]] */
  @JsonProperty("BILLING_ADDRESS") billingAddress: AddressT,
  /** Points to [[oracledb.customers.CustomersRow.creditLimit]] */
  @JsonProperty("CREDIT_LIMIT") creditLimit: Option[MoneyT],
  /** Points to [[oracledb.customers.CustomersRow.createdAt]] */
  @JsonProperty("CREATED_AT") createdAt: LocalDateTime
) extends Tuple5[CustomersId, String, AddressT, Option[MoneyT], LocalDateTime] {
  override def `_1`: CustomersId = customerId

  override def `_2`: String = name

  override def `_3`: AddressT = billingAddress

  override def `_4`: Option[MoneyT] = creditLimit

  override def `_5`: LocalDateTime = createdAt
}

object CustomerSearchSqlRow {
  val `_rowParser`: RowParser[CustomerSearchSqlRow] = RowParsers.of(CustomersId.oracleType, OracleTypes.varchar2, AddressT.oracleType, MoneyT.oracleType.nullable, OracleTypes.timestamp)(CustomerSearchSqlRow.apply)(row => Array[Any](row.customerId, row.name, row.billingAddress, row.creditLimit, row.createdAt))
}