/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.soh

import java.sql.Connection
import typo.scaladsl.SelectBuilder

trait SohViewRepo {
  def select: SelectBuilder[SohViewFields, SohViewRow]

  def selectAll(using c: Connection): List[SohViewRow]
}