/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pu.poh

import java.sql.Connection
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.interpolate

class PohViewRepoImpl extends PohViewRepo {
  override def select: SelectBuilder[PohViewFields, PohViewRow] = SelectBuilder.of(""""pu"."poh"""", PohViewFields.structure, PohViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): java.util.List[PohViewRow] = {
    interpolate(Fragment.lit("""select "id", "purchaseorderid", "revisionnumber", "status", "employeeid", "vendorid", "shipmethodid", "orderdate", "shipdate", "subtotal", "taxamt", "freight", "modifieddate"
    from "pu"."poh"
    """)).query(PohViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}