plugins {
    kotlin("jvm") version "2.0.20"
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xnested-type-aliases")
    }
}

sourceSets {
    main {
        kotlin {
            srcDirs(
                "src/kotlin",
                // Generated by bleep: bleep sourcegen
                "../.bleep/generated-sources/foundations-jdbc-dsl-kotlin/scripts.GeneratedRowParsers",
                "../.bleep/generated-sources/foundations-jdbc-dsl-kotlin/scripts.GeneratedTuples"
            )
        }
    }
}

dependencies {
    api(project(":foundations-jdbc-dsl"))
}
