/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.order

import anorm.Column
import anorm.RowParser
import anorm.Success
import frontpage.Text
import frontpage.customtypes.Defaulted
import frontpage.customtypes.TypoLocalDateTime
import frontpage.frontpage.OrderStatus
import frontpage.frontpage.product.ProductId
import frontpage.frontpage.user.UserId
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** Table: frontpage.order
 * Primary key: id
 */
case class OrderRow(
  /** Default: gen_random_uuid() */
  id: OrderId,
  /** Points to [[frontpage.frontpage.user.UserRow.id]] */
  userId: Option[UserId],
  /** Points to [[frontpage.frontpage.product.ProductRow.id]] */
  productId: Option[ProductId],
  /** Default: 'pending'::frontpage.order_status */
  status: Option[OrderStatus],
  total: BigDecimal,
  /** Default: now() */
  createdAt: Option[TypoLocalDateTime],
  shippedAt: Option[TypoLocalDateTime]
) {
  def toUnsavedRow(
    id: Defaulted[OrderId],
    status: Defaulted[Option[OrderStatus]] = Defaulted.Provided(this.status),
    createdAt: Defaulted[Option[TypoLocalDateTime]] = Defaulted.Provided(this.createdAt)
  ): OrderRowUnsaved = {
    new OrderRowUnsaved(
      userId,
      productId,
      total,
      shippedAt,
      id,
      status,
      createdAt
    )
  }
}

object OrderRow {
  given pgText: Text[OrderRow] = {
    Text.instance[OrderRow]{ (row, sb) =>
      OrderId.pgText.unsafeEncode(row.id, sb)
      sb.append(Text.DELIMETER)
      Text.option(using UserId.pgText).unsafeEncode(row.userId, sb)
      sb.append(Text.DELIMETER)
      Text.option(using ProductId.pgText).unsafeEncode(row.productId, sb)
      sb.append(Text.DELIMETER)
      Text.option(using OrderStatus.pgText).unsafeEncode(row.status, sb)
      sb.append(Text.DELIMETER)
      Text.bigDecimalInstance.unsafeEncode(row.total, sb)
      sb.append(Text.DELIMETER)
      Text.option(using TypoLocalDateTime.pgText).unsafeEncode(row.createdAt, sb)
      sb.append(Text.DELIMETER)
      Text.option(using TypoLocalDateTime.pgText).unsafeEncode(row.shippedAt, sb)
    }
  }

  given reads: Reads[OrderRow] = {
    Reads[OrderRow](json => JsResult.fromTry(
        Try(
          OrderRow(
            id = json.\("id").as(OrderId.reads),
            userId = json.\("user_id").toOption.map(_.as(UserId.reads)),
            productId = json.\("product_id").toOption.map(_.as(ProductId.reads)),
            status = json.\("status").toOption.map(_.as(OrderStatus.reads)),
            total = json.\("total").as(Reads.bigDecReads),
            createdAt = json.\("created_at").toOption.map(_.as(TypoLocalDateTime.reads)),
            shippedAt = json.\("shipped_at").toOption.map(_.as(TypoLocalDateTime.reads))
          )
        )
      ),
    )
  }

  def rowParser(idx: Int): RowParser[OrderRow] = {
    RowParser[OrderRow] { row =>
      Success(
        OrderRow(
          id = row(idx + 0)(using OrderId.column),
          userId = row(idx + 1)(using Column.columnToOption(using UserId.column)),
          productId = row(idx + 2)(using Column.columnToOption(using ProductId.column)),
          status = row(idx + 3)(using Column.columnToOption(using OrderStatus.column)),
          total = row(idx + 4)(using Column.columnToScalaBigDecimal),
          createdAt = row(idx + 5)(using Column.columnToOption(using TypoLocalDateTime.column)),
          shippedAt = row(idx + 6)(using Column.columnToOption(using TypoLocalDateTime.column))
        )
      )
    }
  }

  given writes: OWrites[OrderRow] = {
    OWrites[OrderRow](o =>
      new JsObject(ListMap[String, JsValue](
        "id" -> OrderId.writes.writes(o.id),
        "user_id" -> Writes.OptionWrites(using UserId.writes).writes(o.userId),
        "product_id" -> Writes.OptionWrites(using ProductId.writes).writes(o.productId),
        "status" -> Writes.OptionWrites(using OrderStatus.writes).writes(o.status),
        "total" -> Writes.BigDecimalWrites.writes(o.total),
        "created_at" -> Writes.OptionWrites(using TypoLocalDateTime.writes).writes(o.createdAt),
        "shipped_at" -> Writes.OptionWrites(using TypoLocalDateTime.writes).writes(o.shippedAt)
      ))
    )
  }
}