/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.order

import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class OrderRepoMock(
  toRow: OrderRowUnsaved => OrderRow,
  map: scala.collection.mutable.Map[OrderId, OrderRow] = scala.collection.mutable.Map.empty[OrderId, OrderRow]
) extends OrderRepo {
  def delete: DeleteBuilder[OrderFields, OrderRow] = DeleteBuilderMock(DeleteParams.empty, OrderFields.structure, map)

  def deleteById(id: OrderId)(using c: Connection): Boolean = map.remove(id).isDefined

  def deleteByIds(ids: Array[OrderId])(using c: Connection): Int = ids.map(id => map.remove(id)).count(_.isDefined)

  def insert(unsaved: OrderRow)(using c: Connection): OrderRow = {
    val _ = if (map.contains(unsaved.id))
      sys.error(s"id ${unsaved.id} already exists")
    else
      map.put(unsaved.id, unsaved)
  
    unsaved
  }

  def insert(unsaved: OrderRowUnsaved)(using c: Connection): OrderRow = insert(toRow(unsaved))

  def insertStreaming(
    unsaved: Iterator[OrderRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { row =>
      map += (row.id -> row)
    }
    unsaved.size.toLong
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[OrderRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = {
    unsaved.foreach { unsavedRow =>
      val row = toRow(unsavedRow)
      map += (row.id -> row)
    }
    unsaved.size.toLong
  }

  def select: SelectBuilder[OrderFields, OrderRow] = SelectBuilderMock(OrderFields.structure, () => map.values.toList, SelectParams.empty)

  def selectAll(using c: Connection): List[OrderRow] = map.values.toList

  def selectById(id: OrderId)(using c: Connection): Option[OrderRow] = map.get(id)

  def selectByIds(ids: Array[OrderId])(using c: Connection): List[OrderRow] = ids.flatMap(map.get).toList

  def selectByIdsTracked(ids: Array[OrderId])(using c: Connection): Map[OrderId, OrderRow] = {
    val byId = selectByIds(ids).view.map(x => (x.id, x)).toMap
    ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def update: UpdateBuilder[OrderFields, OrderRow] = UpdateBuilderMock(UpdateParams.empty, OrderFields.structure, map)

  def update(row: OrderRow)(using c: Connection): Option[OrderRow] = {
    map.get(row.id).map { _ =>
      map.put(row.id, row): @nowarn
      row
    }
  }

  def upsert(unsaved: OrderRow)(using c: Connection): OrderRow = {
    map.put(unsaved.id, unsaved): @nowarn
    unsaved
  }

  def upsertBatch(unsaved: Iterable[OrderRow])(using c: Connection): List[OrderRow] = {
    unsaved.map { row =>
      map += (row.id -> row)
      row
    }.toList
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[OrderRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    unsaved.foreach { row =>
      map += (row.id -> row)
    }
    unsaved.size
  }
}