/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.order

import anorm.BatchSql
import anorm.NamedParameter
import anorm.ParameterValue
import anorm.RowParser
import anorm.SQL
import anorm.SimpleSql
import anorm.ToStatement
import frontpage.customtypes.Defaulted
import frontpage.customtypes.TypoLocalDateTime
import frontpage.frontpage.OrderStatus
import frontpage.frontpage.product.ProductId
import frontpage.frontpage.user.UserId
import frontpage.streamingInsert
import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import anorm.SqlStringInterpolation

class OrderRepoImpl extends OrderRepo {
  def delete: DeleteBuilder[OrderFields, OrderRow] = DeleteBuilder.of(""""frontpage"."order"""", OrderFields.structure, OrderRow.rowParser(1).*)

  def deleteById(id: OrderId)(using c: Connection): Boolean = SQL"""delete from "frontpage"."order" where "id" = ${ParameterValue(id, null, OrderId.toStatement)}""".executeUpdate() > 0

  def deleteByIds(ids: Array[OrderId])(using c: Connection): Int = {
    SQL"""delete
    from "frontpage"."order"
    where "id" = ANY(${ParameterValue(ids, null, OrderId.arrayToStatement)})
    """.executeUpdate()
  }

  def insert(unsaved: OrderRow)(using c: Connection): OrderRow = {
  SQL"""insert into "frontpage"."order"("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at")
    values (${ParameterValue(unsaved.id, null, OrderId.toStatement)}::uuid, ${ParameterValue(unsaved.userId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid, ${ParameterValue(unsaved.productId, null, ToStatement.optionToStatement(using ProductId.toStatement, ProductId.parameterMetadata))}::uuid, ${ParameterValue(unsaved.status, null, ToStatement.optionToStatement(using OrderStatus.toStatement, OrderStatus.parameterMetadata))}::frontpage.order_status, ${ParameterValue(unsaved.total, null, ToStatement.scalaBigDecimalToStatement)}::numeric, ${ParameterValue(unsaved.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp, ${ParameterValue(unsaved.shippedAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp)
    returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    """
    .executeInsert(OrderRow.rowParser(1).single)
  }

  def insert(unsaved: OrderRowUnsaved)(using c: Connection): OrderRow = {
    val namedParameters = List(
      Some((NamedParameter("user_id", ParameterValue(unsaved.userId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))), "::uuid")),
      Some((NamedParameter("product_id", ParameterValue(unsaved.productId, null, ToStatement.optionToStatement(using ProductId.toStatement, ProductId.parameterMetadata))), "::uuid")),
      Some((NamedParameter("total", ParameterValue(unsaved.total, null, ToStatement.scalaBigDecimalToStatement)), "::numeric")),
      Some((NamedParameter("shipped_at", ParameterValue(unsaved.shippedAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))), "::timestamp")),
      unsaved.id match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("id", ParameterValue(value, null, OrderId.toStatement)), "::uuid"))
      },
      unsaved.status match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("status", ParameterValue(value, null, ToStatement.optionToStatement(using OrderStatus.toStatement, OrderStatus.parameterMetadata))), "::frontpage.order_status"))
      },
      unsaved.createdAt match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("created_at", ParameterValue(value, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))), "::timestamp"))
      }
    ).flatten
    val quote = '"'.toString
    if (namedParameters.isEmpty) {
      SQL"""insert into "frontpage"."order" default values
      returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
      """
        .executeInsert(OrderRow.rowParser(1).single)
    } else {
      val q = s"""insert into "frontpage"."order"(${namedParameters.map{case (x, _) => quote + x.name + quote}.mkString(", ")})
              values (${namedParameters.map{ case (np, cast) => s"{${np.name}}$cast"}.mkString(", ")})
              returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
              """
      SimpleSql(SQL(q), namedParameters.map { case (np, _) => np.tupled }.toMap, RowParser.successful)
        .executeInsert(OrderRow.rowParser(1).single)
    }
  }

  def insertStreaming(
    unsaved: Iterator[OrderRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."order"("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at") FROM STDIN""", batchSize, unsaved)(using OrderRow.pgText, c)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[OrderRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."order"("user_id", "product_id", "total", "shipped_at", "id", "status", "created_at") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved)(using OrderRowUnsaved.pgText, c)

  def select: SelectBuilder[OrderFields, OrderRow] = SelectBuilder.of(""""frontpage"."order"""", OrderFields.structure, OrderRow.rowParser)

  def selectAll(using c: Connection): List[OrderRow] = {
    SQL"""select "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    from "frontpage"."order"
    """.as(OrderRow.rowParser(1).*)
  }

  def selectById(id: OrderId)(using c: Connection): Option[OrderRow] = {
    SQL"""select "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    from "frontpage"."order"
    where "id" = ${ParameterValue(id, null, OrderId.toStatement)}
    """.as(OrderRow.rowParser(1).singleOpt)
  }

  def selectByIds(ids: Array[OrderId])(using c: Connection): List[OrderRow] = {
    SQL"""select "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    from "frontpage"."order"
    where "id" = ANY(${ParameterValue(ids, null, OrderId.arrayToStatement)})
    """.as(OrderRow.rowParser(1).*)
  }

  def selectByIdsTracked(ids: Array[OrderId])(using c: Connection): Map[OrderId, OrderRow] = {
    val byId = selectByIds(ids).view.map(x => (x.id, x)).toMap
    ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def update: UpdateBuilder[OrderFields, OrderRow] = UpdateBuilder.of(""""frontpage"."order"""", OrderFields.structure, OrderRow.rowParser(1).*)

  def update(row: OrderRow)(using c: Connection): Option[OrderRow] = {
    val id = row.id
    SQL"""update "frontpage"."order"
    set "user_id" = ${ParameterValue(row.userId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid,
    "product_id" = ${ParameterValue(row.productId, null, ToStatement.optionToStatement(using ProductId.toStatement, ProductId.parameterMetadata))}::uuid,
    "status" = ${ParameterValue(row.status, null, ToStatement.optionToStatement(using OrderStatus.toStatement, OrderStatus.parameterMetadata))}::frontpage.order_status,
    "total" = ${ParameterValue(row.total, null, ToStatement.scalaBigDecimalToStatement)}::numeric,
    "created_at" = ${ParameterValue(row.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp,
    "shipped_at" = ${ParameterValue(row.shippedAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp
    where "id" = ${ParameterValue(id, null, OrderId.toStatement)}
    returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    """.executeInsert(OrderRow.rowParser(1).singleOpt)
  }

  def upsert(unsaved: OrderRow)(using c: Connection): OrderRow = {
  SQL"""insert into "frontpage"."order"("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at")
    values (
      ${ParameterValue(unsaved.id, null, OrderId.toStatement)}::uuid,
    ${ParameterValue(unsaved.userId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))}::uuid,
    ${ParameterValue(unsaved.productId, null, ToStatement.optionToStatement(using ProductId.toStatement, ProductId.parameterMetadata))}::uuid,
    ${ParameterValue(unsaved.status, null, ToStatement.optionToStatement(using OrderStatus.toStatement, OrderStatus.parameterMetadata))}::frontpage.order_status,
    ${ParameterValue(unsaved.total, null, ToStatement.scalaBigDecimalToStatement)}::numeric,
    ${ParameterValue(unsaved.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp,
    ${ParameterValue(unsaved.shippedAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))}::timestamp
    )
    on conflict ("id")
    do update set
      "user_id" = EXCLUDED."user_id",
    "product_id" = EXCLUDED."product_id",
    "status" = EXCLUDED."status",
    "total" = EXCLUDED."total",
    "created_at" = EXCLUDED."created_at",
    "shipped_at" = EXCLUDED."shipped_at"
    returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
    """
    .executeInsert(OrderRow.rowParser(1).single)
  }

  def upsertBatch(unsaved: Iterable[OrderRow])(using c: Connection): List[OrderRow] = {
    def toNamedParameter(row: OrderRow): List[NamedParameter] = List(
      NamedParameter("id", ParameterValue(row.id, null, OrderId.toStatement)),
      NamedParameter("user_id", ParameterValue(row.userId, null, ToStatement.optionToStatement(using UserId.toStatement, UserId.parameterMetadata))),
      NamedParameter("product_id", ParameterValue(row.productId, null, ToStatement.optionToStatement(using ProductId.toStatement, ProductId.parameterMetadata))),
      NamedParameter("status", ParameterValue(row.status, null, ToStatement.optionToStatement(using OrderStatus.toStatement, OrderStatus.parameterMetadata))),
      NamedParameter("total", ParameterValue(row.total, null, ToStatement.scalaBigDecimalToStatement)),
      NamedParameter("created_at", ParameterValue(row.createdAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata))),
      NamedParameter("shipped_at", ParameterValue(row.shippedAt, null, ToStatement.optionToStatement(using TypoLocalDateTime.toStatement, TypoLocalDateTime.parameterMetadata)))
    )
    unsaved.toList match {
      case Nil => Nil
      case head :: rest =>
        new anorm.frontpage.ExecuteReturningSyntax.Ops(
          BatchSql(
            s"""insert into "frontpage"."order"("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at")
            values ({id}::uuid, {user_id}::uuid, {product_id}::uuid, {status}::frontpage.order_status, {total}::numeric, {created_at}::timestamp, {shipped_at}::timestamp)
            on conflict ("id")
            do update set
              "user_id" = EXCLUDED."user_id",
            "product_id" = EXCLUDED."product_id",
            "status" = EXCLUDED."status",
            "total" = EXCLUDED."total",
            "created_at" = EXCLUDED."created_at",
            "shipped_at" = EXCLUDED."shipped_at"
            returning "id", "user_id", "product_id", "status", "total", "created_at"::text, "shipped_at"::text
            """,
            toNamedParameter(head),
            rest.map(toNamedParameter)*
          )
        ).executeReturning(OrderRow.rowParser(1).*)
    }
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[OrderRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    SQL"""create temporary table order_TEMP (like "frontpage"."order") on commit drop""".execute(): @nowarn
    streamingInsert(s"""copy order_TEMP("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at") from stdin""", batchSize, unsaved)(using OrderRow.pgText, c): @nowarn
    SQL"""insert into "frontpage"."order"("id", "user_id", "product_id", "status", "total", "created_at", "shipped_at")
    select * from order_TEMP
    on conflict ("id")
    do update set
      "user_id" = EXCLUDED."user_id",
    "product_id" = EXCLUDED."product_id",
    "status" = EXCLUDED."status",
    "total" = EXCLUDED."total",
    "created_at" = EXCLUDED."created_at",
    "shipped_at" = EXCLUDED."shipped_at"
    ;
    drop table order_TEMP;""".executeUpdate()
  }
}