/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.ct

import java.sql.Connection
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.interpolate

class CtViewRepoImpl extends CtViewRepo {
  override def select: SelectBuilder[CtViewFields, CtViewRow] = SelectBuilder.of(""""pe"."ct"""", CtViewFields.structure, CtViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): java.util.List[CtViewRow] = {
    interpolate(Fragment.lit("""select "id", "contacttypeid", "name", "modifieddate"
    from "pe"."ct"
    """)).query(CtViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}