/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.stateprovince

import com.fasterxml.jackson.annotation.JsonValue
import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.scaladsl.Bijection
import typo.scaladsl.ScalaDbTypes

/** Type for the primary key of table `person.stateprovince` */
case class StateprovinceId(@JsonValue value: Int) extends scala.AnyVal

object StateprovinceId {
  given bijection: Bijection[StateprovinceId, Int] = Bijection.apply[StateprovinceId, Int](_.value)(StateprovinceId.apply)

  given pgType: PgType[StateprovinceId] = ScalaDbTypes.PgTypes.int4.bimap(StateprovinceId.apply, _.value)

  given pgTypeArray: PgType[Array[StateprovinceId]] = PgTypes.int4ArrayUnboxed.bimap(xs => xs.map(StateprovinceId.apply), xs => xs.map(_.value))
}