/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.db2test_unique

import dev.typr.foundations.kotlin.DeleteBuilder
import dev.typr.foundations.kotlin.SelectBuilder
import dev.typr.foundations.kotlin.UpdateBuilder
import java.sql.Connection
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map

interface Db2testUniqueRepo {
  abstract fun delete(): DeleteBuilder<Db2testUniqueFields, Db2testUniqueRow>

  abstract fun deleteById(
    id: Db2testUniqueId,
    c: Connection
  ): Boolean

  abstract fun deleteByIds(
    ids: Array<Db2testUniqueId>,
    c: Connection
  ): Int

  abstract fun insert(
    unsaved: Db2testUniqueRow,
    c: Connection
  ): Db2testUniqueRow

  abstract fun insert(
    unsaved: Db2testUniqueRowUnsaved,
    c: Connection
  ): Db2testUniqueRow

  abstract fun select(): SelectBuilder<Db2testUniqueFields, Db2testUniqueRow>

  abstract fun selectAll(c: Connection): List<Db2testUniqueRow>

  abstract fun selectById(
    id: Db2testUniqueId,
    c: Connection
  ): Db2testUniqueRow?

  abstract fun selectByIds(
    ids: Array<Db2testUniqueId>,
    c: Connection
  ): List<Db2testUniqueRow>

  abstract fun selectByIdsTracked(
    ids: Array<Db2testUniqueId>,
    c: Connection
  ): Map<Db2testUniqueId, Db2testUniqueRow>

  abstract fun selectByUniqueCodeAndCategory(
    code: String,
    category: String,
    c: Connection
  ): Db2testUniqueRow?

  abstract fun selectByUniqueEmail(
    email: String,
    c: Connection
  ): Db2testUniqueRow?

  abstract fun update(): UpdateBuilder<Db2testUniqueFields, Db2testUniqueRow>

  abstract fun update(
    row: Db2testUniqueRow,
    c: Connection
  ): Boolean

  abstract fun upsert(
    unsaved: Db2testUniqueRow,
    c: Connection
  )

  abstract fun upsertBatch(
    unsaved: Iterator<Db2testUniqueRow>,
    c: Connection
  )
}