/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.pc

import java.sql.Connection
import typo.scaladsl.Dialect
import typo.scaladsl.SelectBuilder
import typo.scaladsl.Fragment.sql

class PcViewRepoImpl extends PcViewRepo {
  override def select: SelectBuilder[PcViewFields, PcViewRow] = SelectBuilder.of(""""pr"."pc"""", PcViewFields.structure, PcViewRow.`_rowParser`, Dialect.POSTGRESQL)

  override def selectAll(using c: Connection): List[PcViewRow] = {
    sql"""select "id", "productcategoryid", "name", "rowguid", "modifieddate"
    from "pr"."pc"
    """.query(PcViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}