/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.vsalespersonsalesbyfiscalyears

import java.math.BigDecimal
import kotlin.collections.List
import typo.dsl.Path
import typo.dsl.SqlExpr.FieldLike
import typo.kotlindsl.FieldsExpr
import typo.kotlindsl.KotlinDbTypes
import typo.kotlindsl.RelationStructure
import typo.kotlindsl.SqlExpr.Field
import typo.runtime.PgTypes
import typo.runtime.RowParser

interface VsalespersonsalesbyfiscalyearsViewFields : FieldsExpr<VsalespersonsalesbyfiscalyearsViewRow> {
  abstract fun _2012(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>

  abstract fun _2013(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>

  abstract fun _2014(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>

  abstract override fun columns(): List<FieldLike<*, VsalespersonsalesbyfiscalyearsViewRow>>

  abstract fun fullName(): Field<String, VsalespersonsalesbyfiscalyearsViewRow>

  abstract fun jobTitle(): Field<String, VsalespersonsalesbyfiscalyearsViewRow>

  override fun rowParser(): RowParser<VsalespersonsalesbyfiscalyearsViewRow> = VsalespersonsalesbyfiscalyearsViewRow._rowParser.underlying

  abstract fun salesPersonID(): Field<Int, VsalespersonsalesbyfiscalyearsViewRow>

  abstract fun salesTerritory(): Field<String, VsalespersonsalesbyfiscalyearsViewRow>

  companion object {
    data class Impl(val _path: List<Path>) : VsalespersonsalesbyfiscalyearsViewFields, RelationStructure<VsalespersonsalesbyfiscalyearsViewFields, VsalespersonsalesbyfiscalyearsViewRow> {
      override fun salesPersonID(): Field<Int, VsalespersonsalesbyfiscalyearsViewRow> = Field<Int, VsalespersonsalesbyfiscalyearsViewRow>(_path, "SalesPersonID", VsalespersonsalesbyfiscalyearsViewRow::salesPersonID, null, null, { row, value -> row.copy(salesPersonID = value) }, KotlinDbTypes.PgTypes.int4)

      override fun fullName(): Field<String, VsalespersonsalesbyfiscalyearsViewRow> = Field<String, VsalespersonsalesbyfiscalyearsViewRow>(_path, "FullName", VsalespersonsalesbyfiscalyearsViewRow::fullName, null, null, { row, value -> row.copy(fullName = value) }, PgTypes.text)

      override fun jobTitle(): Field<String, VsalespersonsalesbyfiscalyearsViewRow> = Field<String, VsalespersonsalesbyfiscalyearsViewRow>(_path, "JobTitle", VsalespersonsalesbyfiscalyearsViewRow::jobTitle, null, null, { row, value -> row.copy(jobTitle = value) }, PgTypes.text)

      override fun salesTerritory(): Field<String, VsalespersonsalesbyfiscalyearsViewRow> = Field<String, VsalespersonsalesbyfiscalyearsViewRow>(_path, "SalesTerritory", VsalespersonsalesbyfiscalyearsViewRow::salesTerritory, null, null, { row, value -> row.copy(salesTerritory = value) }, PgTypes.text)

      override fun _2012(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow> = Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>(_path, "2012", VsalespersonsalesbyfiscalyearsViewRow::_2012, null, null, { row, value -> row.copy(_2012 = value) }, PgTypes.numeric)

      override fun _2013(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow> = Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>(_path, "2013", VsalespersonsalesbyfiscalyearsViewRow::_2013, null, null, { row, value -> row.copy(_2013 = value) }, PgTypes.numeric)

      override fun _2014(): Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow> = Field<BigDecimal, VsalespersonsalesbyfiscalyearsViewRow>(_path, "2014", VsalespersonsalesbyfiscalyearsViewRow::_2014, null, null, { row, value -> row.copy(_2014 = value) }, PgTypes.numeric)

      override fun _path(): List<Path> = _path

      override fun columns(): List<FieldLike<*, VsalespersonsalesbyfiscalyearsViewRow>> = listOf(this.salesPersonID().underlying, this.fullName().underlying, this.jobTitle().underlying, this.salesTerritory().underlying, this._2012().underlying, this._2013().underlying, this._2014().underlying)

      override fun withPaths(_path: List<Path>): RelationStructure<VsalespersonsalesbyfiscalyearsViewFields, VsalespersonsalesbyfiscalyearsViewRow> = Impl(_path)
    }

    val structure: Impl = Impl(emptyList<typo.dsl.Path>())
  }
}