/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.identity_test

import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.PgTypes
import typo.runtime.streamingInsert
import typo.runtime.FragmentInterpolator.interpolate

class IdentityTestRepoImpl extends IdentityTestRepo {
  def delete: DeleteBuilder[IdentityTestFields, IdentityTestRow] = DeleteBuilder.of("public.identity-test", IdentityTestFields.structure)

  def deleteById(name: IdentityTestId)(using c: Connection): java.lang.Boolean = interpolate"""delete from "public"."identity-test" where "name" = ${IdentityTestId.pgType.encode(name)}""".update().runUnchecked(c) > 0

  def deleteByIds(names: Array[IdentityTestId])(using c: Connection): Integer = {
    interpolate"""delete
    from "public"."identity-test"
    where "name" = ANY(${IdentityTestId.pgTypeArray.encode(names)})"""
      .update()
      .runUnchecked(c)
  }

  def insert(unsaved: IdentityTestRow)(using c: Connection): IdentityTestRow = {
  interpolate"""insert into "public"."identity-test"("default_generated", "name")
    values (${PgTypes.int4.encode(unsaved.defaultGenerated)}::int4, ${IdentityTestId.pgType.encode(unsaved.name)})
    returning "always_generated", "default_generated", "name"
    """
    .updateReturning(IdentityTestRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insert(unsaved: IdentityTestRowUnsaved)(using c: Connection): IdentityTestRow = {
    val columns: java.util.List[Literal] = new ArrayList()
    val values: java.util.List[Fragment] = new ArrayList()
    columns.add(Fragment.lit(""""name"""")): @scala.annotation.nowarn
    values.add(interpolate"${IdentityTestId.pgType.encode(unsaved.name)}"): @scala.annotation.nowarn
    unsaved.defaultGenerated.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""default_generated"""")): @scala.annotation.nowarn;
        values.add(interpolate"${PgTypes.int4.encode(value)}::int4"): @scala.annotation.nowarn;
      }
    );
    val q: Fragment = {
      interpolate"""insert into "public"."identity-test"(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning "always_generated", "default_generated", "name"
      """
    }
    q.updateReturning(IdentityTestRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insertStreaming(
    unsaved: java.util.Iterator[IdentityTestRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "public"."identity-test"("default_generated", "name") FROM STDIN""", batchSize, unsaved, c, IdentityTestRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[IdentityTestRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "public"."identity-test"("name", "default_generated") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved, c, IdentityTestRowUnsaved.pgText)

  def select: SelectBuilder[IdentityTestFields, IdentityTestRow] = SelectBuilder.of("public.identity-test", IdentityTestFields.structure, IdentityTestRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[IdentityTestRow] = {
    interpolate"""select "always_generated", "default_generated", "name"
    from "public"."identity-test"
    """.as(IdentityTestRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectById(name: IdentityTestId)(using c: Connection): Optional[IdentityTestRow] = {
    interpolate"""select "always_generated", "default_generated", "name"
    from "public"."identity-test"
    where "name" = ${IdentityTestId.pgType.encode(name)}""".as(IdentityTestRow.`_rowParser`.first()).runUnchecked(c)
  }

  def selectByIds(names: Array[IdentityTestId])(using c: Connection): java.util.List[IdentityTestRow] = {
    interpolate"""select "always_generated", "default_generated", "name"
    from "public"."identity-test"
    where "name" = ANY(${IdentityTestId.pgTypeArray.encode(names)})""".as(IdentityTestRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectByIdsTracked(names: Array[IdentityTestId])(using c: Connection): java.util.Map[IdentityTestId, IdentityTestRow] = {
    val ret: java.util.Map[IdentityTestId, IdentityTestRow] = new HashMap()
    selectByIds(names)(using c).forEach(row => ret.put(row.name, row): @scala.annotation.nowarn)
    ret
  }

  def update: UpdateBuilder[IdentityTestFields, IdentityTestRow] = UpdateBuilder.of("public.identity-test", IdentityTestFields.structure, IdentityTestRow.`_rowParser`.all())

  def update(row: IdentityTestRow)(using c: Connection): java.lang.Boolean = {
    val name: IdentityTestId = row.name
    interpolate"""update "public"."identity-test"
    set "default_generated" = ${PgTypes.int4.encode(row.defaultGenerated)}::int4
    where "name" = ${IdentityTestId.pgType.encode(name)}""".update().runUnchecked(c) > 0
  }

  def upsert(unsaved: IdentityTestRow)(using c: Connection): IdentityTestRow = {
  interpolate"""insert into "public"."identity-test"("default_generated", "name")
    values (${PgTypes.int4.encode(unsaved.defaultGenerated)}::int4, ${IdentityTestId.pgType.encode(unsaved.name)})
    on conflict ("name")
    do update set
      "default_generated" = EXCLUDED."default_generated"
    returning "always_generated", "default_generated", "name"
    """
    .updateReturning(IdentityTestRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  def upsertBatch(unsaved: java.util.Iterator[IdentityTestRow])(using c: Connection): java.util.List[IdentityTestRow] = {
    interpolate"""insert into "public"."identity-test"("default_generated", "name")
    values (?::int4, ?)
    on conflict ("name")
    do update set
      "default_generated" = EXCLUDED."default_generated"
    returning "always_generated", "default_generated", "name"
    """
      .updateManyReturning(IdentityTestRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[IdentityTestRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    interpolate"""create temporary table identity-test_TEMP (like "public"."identity-test") on commit drop""".update().runUnchecked(c): @scala.annotation.nowarn
    streamingInsert.insertUnchecked(s"""copy identity-test_TEMP("default_generated", "name") from stdin""", batchSize, unsaved, c, IdentityTestRow.pgText): @scala.annotation.nowarn
    interpolate"""insert into "public"."identity-test"("default_generated", "name")
    select * from identity-test_TEMP
    on conflict ("name")
    do update set
      "default_generated" = EXCLUDED."default_generated"
    ;
    drop table identity-test_TEMP;""".update().runUnchecked(c)
  }
}