/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.company

import anorm.Column
import anorm.RowParser
import anorm.Success
import frontpage.Text
import frontpage.customtypes.Defaulted
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** Table: frontpage.company
 * Primary key: id
 */
case class CompanyRow(
  /** Default: gen_random_uuid() */
  id: CompanyId,
  name: String
) {
  def toUnsavedRow(id: Defaulted[CompanyId]): CompanyRowUnsaved = new CompanyRowUnsaved(name, id)
}

object CompanyRow {
  given pgText: Text[CompanyRow] = {
    Text.instance[CompanyRow]{ (row, sb) =>
      CompanyId.pgText.unsafeEncode(row.id, sb)
      sb.append(Text.DELIMETER)
      Text.stringInstance.unsafeEncode(row.name, sb)
    }
  }

  given reads: Reads[CompanyRow] = {
    Reads[CompanyRow](json => JsResult.fromTry(
        Try(
          CompanyRow(
            id = json.\("id").as(CompanyId.reads),
            name = json.\("name").as(Reads.StringReads)
          )
        )
      ),
    )
  }

  def rowParser(idx: Int): RowParser[CompanyRow] = {
    RowParser[CompanyRow] { row =>
      Success(
        CompanyRow(
          id = row(idx + 0)(using CompanyId.column),
          name = row(idx + 1)(using Column.columnToString)
        )
      )
    }
  }

  given writes: OWrites[CompanyRow] = {
    OWrites[CompanyRow](o =>
      new JsObject(ListMap[String, JsValue](
        "id" -> CompanyId.writes.writes(o.id),
        "name" -> Writes.StringWrites.writes(o.name)
      ))
    )
  }
}