/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.company

import anorm.BatchSql
import anorm.NamedParameter
import anorm.ParameterValue
import anorm.RowParser
import anorm.SQL
import anorm.SimpleSql
import anorm.ToStatement
import frontpage.customtypes.Defaulted
import frontpage.streamingInsert
import java.sql.Connection
import scala.annotation.nowarn
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import anorm.SqlStringInterpolation

class CompanyRepoImpl extends CompanyRepo {
  def delete: DeleteBuilder[CompanyFields, CompanyRow] = DeleteBuilder.of(""""frontpage"."company"""", CompanyFields.structure, CompanyRow.rowParser(1).*)

  def deleteById(id: CompanyId)(using c: Connection): Boolean = SQL"""delete from "frontpage"."company" where "id" = ${ParameterValue(id, null, CompanyId.toStatement)}""".executeUpdate() > 0

  def deleteByIds(ids: Array[CompanyId])(using c: Connection): Int = {
    SQL"""delete
    from "frontpage"."company"
    where "id" = ANY(${ParameterValue(ids, null, CompanyId.arrayToStatement)})
    """.executeUpdate()
  }

  def insert(unsaved: CompanyRow)(using c: Connection): CompanyRow = {
  SQL"""insert into "frontpage"."company"("id", "name")
    values (${ParameterValue(unsaved.id, null, CompanyId.toStatement)}::uuid, ${ParameterValue(unsaved.name, null, ToStatement.stringToStatement)})
    returning "id", "name"
    """
    .executeInsert(CompanyRow.rowParser(1).single)
  }

  def insert(unsaved: CompanyRowUnsaved)(using c: Connection): CompanyRow = {
    val namedParameters = List(
      Some((NamedParameter("name", ParameterValue(unsaved.name, null, ToStatement.stringToStatement)), "")),
      unsaved.id match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((NamedParameter("id", ParameterValue(value, null, CompanyId.toStatement)), "::uuid"))
      }
    ).flatten
    val quote = '"'.toString
    if (namedParameters.isEmpty) {
      SQL"""insert into "frontpage"."company" default values
      returning "id", "name"
      """
        .executeInsert(CompanyRow.rowParser(1).single)
    } else {
      val q = s"""insert into "frontpage"."company"(${namedParameters.map{case (x, _) => quote + x.name + quote}.mkString(", ")})
              values (${namedParameters.map{ case (np, cast) => s"{${np.name}}$cast"}.mkString(", ")})
              returning "id", "name"
              """
      SimpleSql(SQL(q), namedParameters.map { case (np, _) => np.tupled }.toMap, RowParser.successful)
        .executeInsert(CompanyRow.rowParser(1).single)
    }
  }

  def insertStreaming(
    unsaved: Iterator[CompanyRow],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."company"("id", "name") FROM STDIN""", batchSize, unsaved)(using CompanyRow.pgText, c)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: Iterator[CompanyRowUnsaved],
    batchSize: Int = 10000
  )(using c: Connection): Long = streamingInsert(s"""COPY "frontpage"."company"("name", "id") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved)(using CompanyRowUnsaved.pgText, c)

  def select: SelectBuilder[CompanyFields, CompanyRow] = SelectBuilder.of(""""frontpage"."company"""", CompanyFields.structure, CompanyRow.rowParser)

  def selectAll(using c: Connection): List[CompanyRow] = {
    SQL"""select "id", "name"
    from "frontpage"."company"
    """.as(CompanyRow.rowParser(1).*)
  }

  def selectById(id: CompanyId)(using c: Connection): Option[CompanyRow] = {
    SQL"""select "id", "name"
    from "frontpage"."company"
    where "id" = ${ParameterValue(id, null, CompanyId.toStatement)}
    """.as(CompanyRow.rowParser(1).singleOpt)
  }

  def selectByIds(ids: Array[CompanyId])(using c: Connection): List[CompanyRow] = {
    SQL"""select "id", "name"
    from "frontpage"."company"
    where "id" = ANY(${ParameterValue(ids, null, CompanyId.arrayToStatement)})
    """.as(CompanyRow.rowParser(1).*)
  }

  def selectByIdsTracked(ids: Array[CompanyId])(using c: Connection): Map[CompanyId, CompanyRow] = {
    val byId = selectByIds(ids).view.map(x => (x.id, x)).toMap
    ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
  }

  def update: UpdateBuilder[CompanyFields, CompanyRow] = UpdateBuilder.of(""""frontpage"."company"""", CompanyFields.structure, CompanyRow.rowParser(1).*)

  def update(row: CompanyRow)(using c: Connection): Option[CompanyRow] = {
    val id = row.id
    SQL"""update "frontpage"."company"
    set "name" = ${ParameterValue(row.name, null, ToStatement.stringToStatement)}
    where "id" = ${ParameterValue(id, null, CompanyId.toStatement)}
    returning "id", "name"
    """.executeInsert(CompanyRow.rowParser(1).singleOpt)
  }

  def upsert(unsaved: CompanyRow)(using c: Connection): CompanyRow = {
  SQL"""insert into "frontpage"."company"("id", "name")
    values (
      ${ParameterValue(unsaved.id, null, CompanyId.toStatement)}::uuid,
    ${ParameterValue(unsaved.name, null, ToStatement.stringToStatement)}
    )
    on conflict ("id")
    do update set
      "name" = EXCLUDED."name"
    returning "id", "name"
    """
    .executeInsert(CompanyRow.rowParser(1).single)
  }

  def upsertBatch(unsaved: Iterable[CompanyRow])(using c: Connection): List[CompanyRow] = {
    def toNamedParameter(row: CompanyRow): List[NamedParameter] = List(
      NamedParameter("id", ParameterValue(row.id, null, CompanyId.toStatement)),
      NamedParameter("name", ParameterValue(row.name, null, ToStatement.stringToStatement))
    )
    unsaved.toList match {
      case Nil => Nil
      case head :: rest =>
        new anorm.frontpage.ExecuteReturningSyntax.Ops(
          BatchSql(
            s"""insert into "frontpage"."company"("id", "name")
            values ({id}::uuid, {name})
            on conflict ("id")
            do update set
              "name" = EXCLUDED."name"
            returning "id", "name"
            """,
            toNamedParameter(head),
            rest.map(toNamedParameter)*
          )
        ).executeReturning(CompanyRow.rowParser(1).*)
    }
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[CompanyRow],
    batchSize: Int = 10000
  )(using c: Connection): Int = {
    SQL"""create temporary table company_TEMP (like "frontpage"."company") on commit drop""".execute(): @nowarn
    streamingInsert(s"""copy company_TEMP("id", "name") from stdin""", batchSize, unsaved)(using CompanyRow.pgText, c): @nowarn
    SQL"""insert into "frontpage"."company"("id", "name")
    select * from company_TEMP
    on conflict ("id")
    do update set
      "name" = EXCLUDED."name"
    ;
    drop table company_TEMP;""".executeUpdate()
  }
}