/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.illustration

import java.time.LocalDateTime
import java.util.Optional
import typo.data.Xml
import typo.dsl.FieldsExpr
import typo.dsl.Path
import typo.dsl.RelationStructure
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.SqlExpr.IdField
import typo.dsl.SqlExpr.OptField
import typo.runtime.PgTypes
import typo.runtime.RowParser

trait IllustrationFields extends FieldsExpr[IllustrationRow] {
  def illustrationid: IdField[IllustrationId, IllustrationRow]

  def diagram: OptField[Xml, IllustrationRow]

  def modifieddate: Field[LocalDateTime, IllustrationRow]

  override def columns: java.util.List[FieldLike[?, IllustrationRow]]

  override def rowParser: RowParser[IllustrationRow] = IllustrationRow._rowParser
}

object IllustrationFields {
  case class Impl(val `_path`: java.util.List[Path]) extends IllustrationFields with RelationStructure[IllustrationFields, IllustrationRow] {

    override def illustrationid: IdField[IllustrationId, IllustrationRow] = {
      new IdField[IllustrationId, IllustrationRow](
        _path,
        "illustrationid",
        _.illustrationid,
        Optional.empty(),
        Optional.of("int4"),
        (row, value) => row.copy(illustrationid = value),
        IllustrationId.pgType
      )
    }

    override def diagram: OptField[Xml, IllustrationRow] = {
      new OptField[Xml, IllustrationRow](
        _path,
        "diagram",
        _.diagram,
        Optional.empty(),
        Optional.of("xml"),
        (row, value) => row.copy(diagram = value),
        PgTypes.xml
      )
    }

    override def modifieddate: Field[LocalDateTime, IllustrationRow] = {
      new Field[LocalDateTime, IllustrationRow](
        _path,
        "modifieddate",
        _.modifieddate,
        Optional.empty(),
        Optional.of("timestamp"),
        (row, value) => row.copy(modifieddate = value),
        PgTypes.timestamp
      )
    }

    override def columns: java.util.List[FieldLike[?, IllustrationRow]] = java.util.List.of(this.illustrationid, this.diagram, this.modifieddate)

    override def withPaths(`_path`: java.util.List[Path]): RelationStructure[IllustrationFields, IllustrationRow] = new Impl(`_path`)
  }

  def structure: Impl = new Impl(java.util.Collections.emptyList())
}