/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.product;

import frontpage.customtypes.TypoJsonb;
import frontpage.customtypes.TypoLocalDateTime;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.PgTypes;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public class ProductRepoImpl implements ProductRepo {
  public DeleteBuilder<ProductFields, ProductRow> delete() {
    return DeleteBuilder.of("frontpage.product", ProductFields.structure());
  };

  public Boolean deleteById(
    ProductId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "frontpage"."product" where "id" = 
      """),
      ProductId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  public Integer deleteByIds(
    ProductId[] ids,
    Connection c
  ) {
    return interpolate(
               typo.runtime.Fragment.lit("""
                  delete
                  from "frontpage"."product"
                  where "id" = ANY("""),
               ProductId.pgTypeArray.encode(ids),
               typo.runtime.Fragment.lit(")")
             )
      .update()
      .runUnchecked(c);
  };

  public ProductRow insert(
    ProductRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."product"("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes")
         values ("""),
      ProductId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.numeric.encode(unsaved.price()),
      typo.runtime.Fragment.lit("::numeric, "),
      PgTypes.bool.opt().encode(unsaved.inStock()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.int4.opt().encode(unsaved.quantity()),
      typo.runtime.Fragment.lit("::int4, "),
      TypoLocalDateTime.pgType.opt().encode(unsaved.lastRestocked()),
      typo.runtime.Fragment.lit("::timestamp, "),
      TypoLocalDateTime.pgType.opt().encode(unsaved.lastModified()),
      typo.runtime.Fragment.lit("::timestamp, "),
      PgTypes.textArray.opt().encode(unsaved.tags()),
      typo.runtime.Fragment.lit("::text[], "),
      PgTypes.int4Array.opt().encode(unsaved.categories()),
      typo.runtime.Fragment.lit("::int4[], "),
      PgTypes.numericArray.opt().encode(unsaved.prices()),
      typo.runtime.Fragment.lit("::numeric[], "),
      TypoJsonb.pgTypeArray.opt().encode(unsaved.attributes()),
      typo.runtime.Fragment.lit("""
         ::jsonb[])
         returning "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
      """)
    )
      .updateReturning(ProductRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public ProductRow insert(
    ProductRowUnsaved unsaved,
    Connection c
  ) {
    List<Literal> columns = new ArrayList<>();;
      List<Fragment> values = new ArrayList<>();;
      columns.add(Fragment.lit("\"name\""));
      values.add(interpolate(
        PgTypes.text.encode(unsaved.name()),
        typo.runtime.Fragment.lit("""
        """)
      ));
      columns.add(Fragment.lit("\"price\""));
      values.add(interpolate(
        PgTypes.numeric.encode(unsaved.price()),
        typo.runtime.Fragment.lit("::numeric")
      ));
      columns.add(Fragment.lit("\"last_restocked\""));
      values.add(interpolate(
        TypoLocalDateTime.pgType.opt().encode(unsaved.lastRestocked()),
        typo.runtime.Fragment.lit("::timestamp")
      ));
      unsaved.id().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"id\""));
          values.add(interpolate(
            ProductId.pgType.encode(value),
            typo.runtime.Fragment.lit("::uuid")
          ));
        }
      );;
      unsaved.inStock().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"in_stock\""));
          values.add(interpolate(
            PgTypes.bool.opt().encode(value),
            typo.runtime.Fragment.lit("""
            """)
          ));
        }
      );;
      unsaved.quantity().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"quantity\""));
          values.add(interpolate(
            PgTypes.int4.opt().encode(value),
            typo.runtime.Fragment.lit("::int4")
          ));
        }
      );;
      unsaved.lastModified().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"last_modified\""));
          values.add(interpolate(
            TypoLocalDateTime.pgType.opt().encode(value),
            typo.runtime.Fragment.lit("::timestamp")
          ));
        }
      );;
      unsaved.tags().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"tags\""));
          values.add(interpolate(
            PgTypes.textArray.opt().encode(value),
            typo.runtime.Fragment.lit("::text[]")
          ));
        }
      );;
      unsaved.categories().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"categories\""));
          values.add(interpolate(
            PgTypes.int4Array.opt().encode(value),
            typo.runtime.Fragment.lit("::int4[]")
          ));
        }
      );;
      unsaved.prices().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"prices\""));
          values.add(interpolate(
            PgTypes.numericArray.opt().encode(value),
            typo.runtime.Fragment.lit("::numeric[]")
          ));
        }
      );;
      unsaved.attributes().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"attributes\""));
          values.add(interpolate(
            TypoJsonb.pgTypeArray.opt().encode(value),
            typo.runtime.Fragment.lit("::jsonb[]")
          ));
        }
      );;
      Fragment q = interpolate(
        typo.runtime.Fragment.lit("""
        insert into "frontpage"."product"(
        """),
        Fragment.comma(columns),
        typo.runtime.Fragment.lit("""
           )
           values ("""),
        Fragment.comma(values),
        typo.runtime.Fragment.lit("""
           )
           returning "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
        """)
      );;
    return q.updateReturning(ProductRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public Long insertStreaming(
    Iterator<ProductRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."product"("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes") FROM STDIN
    """), batchSize, unsaved, c, ProductRow.pgText);
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<ProductRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "frontpage"."product"("name", "price", "last_restocked", "id", "in_stock", "quantity", "last_modified", "tags", "categories", "prices", "attributes") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')
    """), batchSize, unsaved, c, ProductRowUnsaved.pgText);
  };

  public SelectBuilder<ProductFields, ProductRow> select() {
    return SelectBuilder.of("frontpage.product", ProductFields.structure(), ProductRow._rowParser);
  };

  public List<ProductRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
       from "frontpage"."product"
    """)).as(ProductRow._rowParser.all()).runUnchecked(c);
  };

  public Optional<ProductRow> selectById(
    ProductId id,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
         from "frontpage"."product"
         where "id" = """),
      ProductId.pgType.encode(id),
      typo.runtime.Fragment.lit("")
    ).as(ProductRow._rowParser.first()).runUnchecked(c);
  };

  public List<ProductRow> selectByIds(
    ProductId[] ids,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
         from "frontpage"."product"
         where "id" = ANY("""),
      ProductId.pgTypeArray.encode(ids),
      typo.runtime.Fragment.lit(")")
    ).as(ProductRow._rowParser.all()).runUnchecked(c);
  };

  public Map<ProductId, ProductRow> selectByIdsTracked(
    ProductId[] ids,
    Connection c
  ) {
    Map<ProductId, ProductRow> ret = new HashMap<>();;
      selectByIds(ids, c).forEach(row -> ret.put(row.id(), row));
    return ret;
  };

  public UpdateBuilder<ProductFields, ProductRow> update() {
    return UpdateBuilder.of("frontpage.product", ProductFields.structure(), ProductRow._rowParser.all());
  };

  public Boolean update(
    ProductRow row,
    Connection c
  ) {
    ProductId id = row.id();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "frontpage"."product"
                set "name" = """),
             PgTypes.text.encode(row.name()),
             typo.runtime.Fragment.lit("""
                ,
                "price" = """),
             PgTypes.numeric.encode(row.price()),
             typo.runtime.Fragment.lit("""
                ::numeric,
                "in_stock" = """),
             PgTypes.bool.opt().encode(row.inStock()),
             typo.runtime.Fragment.lit("""
                ,
                "quantity" = """),
             PgTypes.int4.opt().encode(row.quantity()),
             typo.runtime.Fragment.lit("""
                ::int4,
                "last_restocked" = """),
             TypoLocalDateTime.pgType.opt().encode(row.lastRestocked()),
             typo.runtime.Fragment.lit("""
                ::timestamp,
                "last_modified" = """),
             TypoLocalDateTime.pgType.opt().encode(row.lastModified()),
             typo.runtime.Fragment.lit("""
                ::timestamp,
                "tags" = """),
             PgTypes.textArray.opt().encode(row.tags()),
             typo.runtime.Fragment.lit("""
                ::text[],
                "categories" = """),
             PgTypes.int4Array.opt().encode(row.categories()),
             typo.runtime.Fragment.lit("""
                ::int4[],
                "prices" = """),
             PgTypes.numericArray.opt().encode(row.prices()),
             typo.runtime.Fragment.lit("""
                ::numeric[],
                "attributes" = """),
             TypoJsonb.pgTypeArray.opt().encode(row.attributes()),
             typo.runtime.Fragment.lit("""
                ::jsonb[]
                where "id" = """),
             ProductId.pgType.encode(id),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };

  public ProductRow upsert(
    ProductRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "frontpage"."product"("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes")
         values ("""),
      ProductId.pgType.encode(unsaved.id()),
      typo.runtime.Fragment.lit("::uuid, "),
      PgTypes.text.encode(unsaved.name()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.numeric.encode(unsaved.price()),
      typo.runtime.Fragment.lit("::numeric, "),
      PgTypes.bool.opt().encode(unsaved.inStock()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.int4.opt().encode(unsaved.quantity()),
      typo.runtime.Fragment.lit("::int4, "),
      TypoLocalDateTime.pgType.opt().encode(unsaved.lastRestocked()),
      typo.runtime.Fragment.lit("::timestamp, "),
      TypoLocalDateTime.pgType.opt().encode(unsaved.lastModified()),
      typo.runtime.Fragment.lit("::timestamp, "),
      PgTypes.textArray.opt().encode(unsaved.tags()),
      typo.runtime.Fragment.lit("::text[], "),
      PgTypes.int4Array.opt().encode(unsaved.categories()),
      typo.runtime.Fragment.lit("::int4[], "),
      PgTypes.numericArray.opt().encode(unsaved.prices()),
      typo.runtime.Fragment.lit("::numeric[], "),
      TypoJsonb.pgTypeArray.opt().encode(unsaved.attributes()),
      typo.runtime.Fragment.lit("""
         ::jsonb[])
         on conflict ("id")
         do update set
           "name" = EXCLUDED."name",
         "price" = EXCLUDED."price",
         "in_stock" = EXCLUDED."in_stock",
         "quantity" = EXCLUDED."quantity",
         "last_restocked" = EXCLUDED."last_restocked",
         "last_modified" = EXCLUDED."last_modified",
         "tags" = EXCLUDED."tags",
         "categories" = EXCLUDED."categories",
         "prices" = EXCLUDED."prices",
         "attributes" = EXCLUDED."attributes"
         returning "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
      """)
    )
      .updateReturning(ProductRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  public List<ProductRow> upsertBatch(
    Iterator<ProductRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "frontpage"."product"("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes")
                values (?::uuid, ?, ?::numeric, ?, ?::int4, ?::timestamp, ?::timestamp, ?::text[], ?::int4[], ?::numeric[], ?::jsonb[])
                on conflict ("id")
                do update set
                  "name" = EXCLUDED."name",
                "price" = EXCLUDED."price",
                "in_stock" = EXCLUDED."in_stock",
                "quantity" = EXCLUDED."quantity",
                "last_restocked" = EXCLUDED."last_restocked",
                "last_modified" = EXCLUDED."last_modified",
                "tags" = EXCLUDED."tags",
                "categories" = EXCLUDED."categories",
                "prices" = EXCLUDED."prices",
                "attributes" = EXCLUDED."attributes"
                returning "id", "name", "price", "in_stock", "quantity", "last_restocked"::text, "last_modified"::text, "tags", "categories", "prices", "attributes"
             """))
      .updateManyReturning(ProductRow._rowParser, unsaved)
      .runUnchecked(c);
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<ProductRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table product_TEMP (like "frontpage"."product") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy product_TEMP("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes") from stdin
      """), batchSize, unsaved, c, ProductRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "frontpage"."product"("id", "name", "price", "in_stock", "quantity", "last_restocked", "last_modified", "tags", "categories", "prices", "attributes")
              select * from product_TEMP
              on conflict ("id")
              do update set
                "name" = EXCLUDED."name",
              "price" = EXCLUDED."price",
              "in_stock" = EXCLUDED."in_stock",
              "quantity" = EXCLUDED."quantity",
              "last_restocked" = EXCLUDED."last_restocked",
              "last_modified" = EXCLUDED."last_modified",
              "tags" = EXCLUDED."tags",
              "categories" = EXCLUDED."categories",
              "prices" = EXCLUDED."prices",
              "attributes" = EXCLUDED."attributes"
              ;
              drop table product_TEMP;""")).update().runUnchecked(c);
  };
}