/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customers

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault

/** This class corresponds to a row in table `CUSTOMERS` which has not been persisted yet */
case class CustomersRowUnsaved(
  /** Full name of the customer */
  @JsonProperty("NAME") name: String,
  /** Email address used for contact and login */
  @JsonProperty("EMAIL") email: String,
  /** Identity BY DEFAULT
   * Unique identifier for the customer
   */
  @JsonProperty("CUSTOMER_ID") customerId: Defaulted[CustomersId] = new UseDefault(),
  /** Default: CURRENT TIMESTAMP */
  @JsonProperty("CREATED_AT") createdAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
) {
  def toRow(
    customerIdDefault: => CustomersId,
    createdAtDefault: => Option[LocalDateTime]
  ): CustomersRow = {
    new CustomersRow(
      customerId = customerId.getOrElse(customerIdDefault),
      name = name,
      email = email,
      createdAt = createdAt.getOrElse(createdAtDefault)
    )
  }
}