/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.payments

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import testdb.orders.OrdersId
import testdb.payment_methods.PaymentMethodsId
import typo.data.maria.Inet6
import typo.runtime.MariaText
import typo.runtime.MariaTypes
import typo.scaladsl.MariaTypeOps
import typo.scaladsl.ScalaDbTypes

/** This class corresponds to a row in table `payments` which has not been persisted yet */
case class PaymentsRowUnsaved(
  /** 
   * Points to [[testdb.orders.OrdersRow.orderId]]
   */
  @JsonProperty("order_id") orderId: OrdersId,
  /** 
   * Points to [[testdb.payment_methods.PaymentMethodsRow.methodId]]
   */
  @JsonProperty("method_id") methodId: PaymentMethodsId,
  /**  */
  amount: BigDecimal,
  /** Default: NULL

   */
  @JsonProperty("transaction_id") transactionId: Defaulted[Option[String]] = new UseDefault(),
  /** Default: 'USD'

   */
  @JsonProperty("currency_code") currencyCode: Defaulted[String] = new UseDefault(),
  /** Default: 'pending'

   */
  status: Defaulted[String] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("processor_response") processorResponse: Defaulted[Option[String]] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("error_message") errorMessage: Defaulted[Option[String]] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("ip_address") ipAddress: Defaulted[Option[Inet6]] = new UseDefault(),
  /** Default: current_timestamp(6)

   */
  @JsonProperty("created_at") createdAt: Defaulted[LocalDateTime] = new UseDefault(),
  /** Default: NULL

   */
  @JsonProperty("processed_at") processedAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
) {
  def toRow(
    transactionIdDefault: => Option[String],
    currencyCodeDefault: => String,
    statusDefault: => String,
    processorResponseDefault: => Option[String],
    errorMessageDefault: => Option[String],
    ipAddressDefault: => Option[Inet6],
    createdAtDefault: => LocalDateTime,
    processedAtDefault: => Option[LocalDateTime],
    paymentIdDefault: => PaymentsId
  ): PaymentsRow = {
    new PaymentsRow(
      paymentId = paymentIdDefault,
      orderId = orderId,
      methodId = methodId,
      transactionId = transactionId.getOrElse(transactionIdDefault),
      amount = amount,
      currencyCode = currencyCode.getOrElse(currencyCodeDefault),
      status = status.getOrElse(statusDefault),
      processorResponse = processorResponse.getOrElse(processorResponseDefault),
      errorMessage = errorMessage.getOrElse(errorMessageDefault),
      ipAddress = ipAddress.getOrElse(ipAddressDefault),
      createdAt = createdAt.getOrElse(createdAtDefault),
      processedAt = processedAt.getOrElse(processedAtDefault)
    )
  }
}

object PaymentsRowUnsaved {
  given mariaText: MariaText[PaymentsRowUnsaved] = MariaText.instance((row, sb) => { OrdersId.pgType.mariaText.unsafeEncode(row.orderId, sb); sb.append(MariaText.DELIMETER); PaymentMethodsId.pgType.mariaText.unsafeEncode(row.methodId, sb); sb.append(MariaText.DELIMETER); ScalaDbTypes.MariaTypes.numeric.mariaText.unsafeEncode(row.amount, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.varchar.nullable.mariaText).unsafeEncode(row.transactionId, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.char_.mariaText).unsafeEncode(row.currencyCode, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.text.mariaText).unsafeEncode(row.status, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.longtext.nullable.mariaText).unsafeEncode(row.processorResponse, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.varchar.nullable.mariaText).unsafeEncode(row.errorMessage, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.inet6.nullable.mariaText).unsafeEncode(row.ipAddress, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.datetime.mariaText).unsafeEncode(row.createdAt, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.datetime.nullable.mariaText).unsafeEncode(row.processedAt, sb) })
}