/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_order_summary

import dev.typr.foundations.scala.Dialect
import dev.typr.foundations.scala.SelectBuilder
import java.sql.Connection
import dev.typr.foundations.scala.Fragment.sql

class CustomerOrderSummaryViewRepoImpl extends CustomerOrderSummaryViewRepo {
  override def select: SelectBuilder[CustomerOrderSummaryViewFields, CustomerOrderSummaryViewRow] = SelectBuilder.of(""""CUSTOMER_ORDER_SUMMARY"""", CustomerOrderSummaryViewFields.structure, CustomerOrderSummaryViewRow.`_rowParser`, Dialect.DB2)

  override def selectAll(using c: Connection): List[CustomerOrderSummaryViewRow] = {
    sql"""select "CUSTOMER_ID", "NAME", "ORDER_COUNT", "TOTAL_SPENT"
    from "CUSTOMER_ORDER_SUMMARY"
    """.query(CustomerOrderSummaryViewRow.`_rowParser`.all()).runUnchecked(c)
  }
}