/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.customtypes

import typo.dsl.Bijection
import typo.runtime.PgRead
import typo.runtime.PgText
import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.runtime.PgWrite

/** Money and cash types in PostgreSQL */
case class TypoMoney(value: java.math.BigDecimal)

object TypoMoney {
  given bijection: Bijection[TypoMoney, java.math.BigDecimal] = Bijection.apply[TypoMoney, java.math.BigDecimal](_.value)(TypoMoney.apply)

  given pgText: PgText[TypoMoney] = PgText.textBigDecimal.contramap(v => v.value)

  given pgType: PgType[TypoMoney] = PgTypes.numeric.bimap(v => new TypoMoney(v), v => v.value).renamed("money")

  given pgTypeArray: PgType[Array[TypoMoney]] = TypoMoney.pgType.array(PgRead.massageJdbcArrayTo(classOf[Array[java.math.BigDecimal]]).map(xs => xs.map(v => new TypoMoney(v))), PgWrite.passObjectToJdbc[java.math.BigDecimal]().array(TypoMoney.pgType.typename().as[java.math.BigDecimal]()).contramap(xs => xs.map((v: TypoMoney) => v.value)))
}