/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.person;

import com.fasterxml.jackson.annotation.JsonProperty;
import frontpage.customtypes.Defaulted;
import frontpage.customtypes.TypoLocalDateTime;
import frontpage.frontpage.address.AddressId;
import java.util.Optional;
import typo.runtime.PgText;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;
import typo.runtime.RowParsers.Tuple4;

/** Table: frontpage.person
  * Primary key: id
  */
public record PersonRow(
  /** Default: gen_random_uuid() */
  PersonId id,
  String name,
  /** Points to {@link frontpage.frontpage.address.AddressRow#id()} */
  @JsonProperty("address_id") Optional<AddressId> addressId,
  /** Default: now() */
  @JsonProperty("created_at") Optional<TypoLocalDateTime> createdAt
) {
  /** Default: gen_random_uuid() */
  public PersonRow withId(PersonId id) {
    return new PersonRow(id, name, addressId, createdAt);
  };

  public PersonRow withName(String name) {
    return new PersonRow(id, name, addressId, createdAt);
  };

  /** Points to {@link frontpage.frontpage.address.AddressRow#id()} */
  public PersonRow withAddressId(Optional<AddressId> addressId) {
    return new PersonRow(id, name, addressId, createdAt);
  };

  /** Default: now() */
  public PersonRow withCreatedAt(Optional<TypoLocalDateTime> createdAt) {
    return new PersonRow(id, name, addressId, createdAt);
  };

  static RowParser<PersonRow> _rowParser = RowParsers.of(PersonId.pgType, PgTypes.text, AddressId.pgType.opt(), TypoLocalDateTime.pgType.opt(), PersonRow::new, row -> new Tuple4<>(row.id(), row.name(), row.addressId(), row.createdAt()));;

  static public PgText<PersonRow> pgText =
    PgText.from(_rowParser);

  public PersonRowUnsaved toUnsavedRow(
    Defaulted<PersonId> id,
    Defaulted<Optional<TypoLocalDateTime>> createdAt
  ) {
    return new PersonRowUnsaved(name, addressId, id, createdAt);
  };
}