/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.jobcandidate

import com.fasterxml.jackson.annotation.JsonValue
import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.scaladsl.Bijection
import typo.scaladsl.ScalaDbTypes

/** Type for the primary key of table `humanresources.jobcandidate` */
case class JobcandidateId(@JsonValue value: Int) extends scala.AnyVal

object JobcandidateId {
  given bijection: Bijection[JobcandidateId, Int] = Bijection.apply[JobcandidateId, Int](_.value)(JobcandidateId.apply)

  given pgType: PgType[JobcandidateId] = ScalaDbTypes.PgTypes.int4.bimap(JobcandidateId.apply, _.value)

  given pgTypeArray: PgType[Array[JobcandidateId]] = PgTypes.int4ArrayUnboxed.bimap(xs => xs.map(JobcandidateId.apply), xs => xs.map(_.value))
}