/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package frontpage.frontpage.user;

import com.fasterxml.jackson.annotation.JsonProperty;
import frontpage.customtypes.Defaulted;
import frontpage.customtypes.TypoLocalDateTime;
import frontpage.frontpage.Email;
import frontpage.frontpage.UserRole;
import frontpage.frontpage.UserStatus;
import frontpage.frontpage.department.DepartmentId;
import java.util.Optional;
import typo.runtime.PgText;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;
import typo.runtime.RowParsers.Tuple9;

/** Table: frontpage.user
  * Primary key: id
  */
public record UserRow(
  /** Default: gen_random_uuid() */
  UserId id,
  Email email,
  String name,
  /** Default: now() */
  @JsonProperty("created_at") Optional<TypoLocalDateTime> createdAt,
  /** Points to {@link frontpage.frontpage.department.DepartmentRow#id()} */
  @JsonProperty("department_id") Optional<DepartmentId> departmentId,
  /** Default: 'active'::frontpage.user_status */
  Optional<UserStatus> status,
  /** Default: false */
  Optional<Boolean> verified,
  /** Points to {@link frontpage.frontpage.user.UserRow#id()} */
  @JsonProperty("manager_id") Optional<UserId> managerId,
  /** Default: 'employee'::frontpage.user_role */
  Optional<UserRole> role
) {
  /** Default: gen_random_uuid() */
  public UserRow withId(UserId id) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  public UserRow withEmail(Email email) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  public UserRow withName(String name) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Default: now() */
  public UserRow withCreatedAt(Optional<TypoLocalDateTime> createdAt) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Points to {@link frontpage.frontpage.department.DepartmentRow#id()} */
  public UserRow withDepartmentId(Optional<DepartmentId> departmentId) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Default: 'active'::frontpage.user_status */
  public UserRow withStatus(Optional<UserStatus> status) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Default: false */
  public UserRow withVerified(Optional<Boolean> verified) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Points to {@link frontpage.frontpage.user.UserRow#id()} */
  public UserRow withManagerId(Optional<UserId> managerId) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  /** Default: 'employee'::frontpage.user_role */
  public UserRow withRole(Optional<UserRole> role) {
    return new UserRow(id, email, name, createdAt, departmentId, status, verified, managerId, role);
  };

  static RowParser<UserRow> _rowParser = RowParsers.of(UserId.pgType, Email.pgType, PgTypes.text, TypoLocalDateTime.pgType.opt(), DepartmentId.pgType.opt(), UserStatus.pgType.opt(), PgTypes.bool.opt(), UserId.pgType.opt(), UserRole.pgType.opt(), UserRow::new, row -> new Tuple9<>(row.id(), row.email(), row.name(), row.createdAt(), row.departmentId(), row.status(), row.verified(), row.managerId(), row.role()));;

  static public PgText<UserRow> pgText =
    PgText.from(_rowParser);

  public UserRowUnsaved toUnsavedRow(
    Defaulted<UserId> id,
    Defaulted<Optional<TypoLocalDateTime>> createdAt,
    Defaulted<Optional<UserStatus>> status,
    Defaulted<Optional<Boolean>> verified,
    Defaulted<Optional<UserRole>> role
  ) {
    return new UserRowUnsaved(email, name, departmentId, managerId, id, createdAt, status, verified, role);
  };
}