/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package oracledb.product_by_sku

import dev.typr.foundations.Fragment
import dev.typr.foundations.OracleTypes
import java.sql.Connection
import dev.typr.foundations.Fragment.interpolate

class ProductBySkuSqlRepoImpl extends ProductBySkuSqlRepo {
  override def apply(sku: String)(using c: Connection): java.util.List[ProductBySkuSqlRow] = {
    interpolate(Fragment.lit("""-- Find product by SKU
    SELECT
        p.product_id,
        p.sku,
        p.name,
        p.price,
        p.tags
    FROM products p
    WHERE p.sku = """), Fragment.encode(OracleTypes.varchar2, sku), Fragment.lit("""
    """)).query(ProductBySkuSqlRow.`_rowParser`.all()).runUnchecked(c)
  }
}