/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.test_sak_soknadsalternativ

import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import java.util.function.Function
import java.util.stream.Collectors
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class TestSakSoknadsalternativRepoMock(map: HashMap[TestSakSoknadsalternativId, TestSakSoknadsalternativRow] = new HashMap[TestSakSoknadsalternativId, TestSakSoknadsalternativRow]()) extends TestSakSoknadsalternativRepo {
  def delete: DeleteBuilder[TestSakSoknadsalternativFields, TestSakSoknadsalternativRow] = {
    new DeleteBuilderMock(
      TestSakSoknadsalternativFields.structure,
      () => new ArrayList(map.values()),
      DeleteParams.empty(),
      row => row.compositeId,
      id => map.remove(id): @scala.annotation.nowarn
    )
  }

  def deleteById(compositeId: TestSakSoknadsalternativId)(using c: Connection): java.lang.Boolean = Optional.ofNullable(map.remove(compositeId)).isPresent()

  def deleteByIds(compositeIds: Array[TestSakSoknadsalternativId])(using c: Connection): Integer = {
    var count = 0
    compositeIds.foreach { id => if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1
    } }
    count
  }

  def insert(unsaved: TestSakSoknadsalternativRow)(using c: Connection): TestSakSoknadsalternativRow = {
    if (map.containsKey(unsaved.compositeId)) {
      throw new RuntimeException(s"id $unsaved.compositeId already exists")
    }
    map.put(unsaved.compositeId, unsaved): @scala.annotation.nowarn
    unsaved
  }

  def insertStreaming(
    unsaved: java.util.Iterator[TestSakSoknadsalternativRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      count = count + 1L
    }
    count
  }

  def select: SelectBuilder[TestSakSoknadsalternativFields, TestSakSoknadsalternativRow] = new SelectBuilderMock(TestSakSoknadsalternativFields.structure, () => new ArrayList(map.values()), SelectParams.empty())

  def selectAll(using c: Connection): java.util.List[TestSakSoknadsalternativRow] = new ArrayList(map.values())

  def selectById(compositeId: TestSakSoknadsalternativId)(using c: Connection): Optional[TestSakSoknadsalternativRow] = Optional.ofNullable(map.get(compositeId))

  def selectByIds(compositeIds: Array[TestSakSoknadsalternativId])(using c: Connection): java.util.List[TestSakSoknadsalternativRow] = {
    val result = new ArrayList[TestSakSoknadsalternativRow]()
    compositeIds.foreach { id => val opt = Optional.ofNullable(map.get(id))
    if (opt.isPresent()) result.add(opt.get()): @scala.annotation.nowarn }
    result
  }

  def selectByIdsTracked(compositeIds: Array[TestSakSoknadsalternativId])(using c: Connection): java.util.Map[TestSakSoknadsalternativId, TestSakSoknadsalternativRow] = selectByIds(compositeIds)(using c).stream().collect(Collectors.toMap((row: adventureworks.public.test_sak_soknadsalternativ.TestSakSoknadsalternativRow) => row.compositeId, Function.identity()))

  def update: UpdateBuilder[TestSakSoknadsalternativFields, TestSakSoknadsalternativRow] = {
    new UpdateBuilderMock(
      TestSakSoknadsalternativFields.structure,
      () => new ArrayList(map.values()),
      UpdateParams.empty(),
      row => row
    )
  }

  def update(row: TestSakSoknadsalternativRow)(using c: Connection): java.lang.Boolean = {
    val shouldUpdate = Optional.ofNullable(map.get(row.compositeId)).filter(oldRow => !oldRow.equals(row)).isPresent()
    if (shouldUpdate) {
      map.put(row.compositeId, row): @scala.annotation.nowarn
    }
    shouldUpdate
  }

  def upsert(unsaved: TestSakSoknadsalternativRow)(using c: Connection): TestSakSoknadsalternativRow = {
    map.put(unsaved.compositeId, unsaved): @scala.annotation.nowarn
    unsaved
  }

  def upsertBatch(unsaved: java.util.Iterator[TestSakSoknadsalternativRow])(using c: Connection): java.util.List[TestSakSoknadsalternativRow] = {
    val result = new ArrayList[TestSakSoknadsalternativRow]()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      result.add(row): @scala.annotation.nowarn
    }
    result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[TestSakSoknadsalternativRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      count = count + 1
    }
    count
  }
}