/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.addresstype

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoUUID
import adventureworks.public.Name
import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.streamingInsert
import typo.runtime.FragmentInterpolator.interpolate

class AddresstypeRepoImpl extends AddresstypeRepo {
  def delete: DeleteBuilder[AddresstypeFields, AddresstypeRow] = DeleteBuilder.of("person.addresstype", AddresstypeFields.structure)

  def deleteById(addresstypeid: AddresstypeId)(using c: Connection): java.lang.Boolean = interpolate"""delete from "person"."addresstype" where "addresstypeid" = ${AddresstypeId.pgType.encode(addresstypeid)}""".update().runUnchecked(c) > 0

  def deleteByIds(addresstypeids: Array[AddresstypeId])(using c: Connection): Integer = {
    interpolate"""delete
    from "person"."addresstype"
    where "addresstypeid" = ANY(${AddresstypeId.pgTypeArray.encode(addresstypeids)})"""
      .update()
      .runUnchecked(c)
  }

  def insert(unsaved: AddresstypeRow)(using c: Connection): AddresstypeRow = {
  interpolate"""insert into "person"."addresstype"("addresstypeid", "name", "rowguid", "modifieddate")
    values (${AddresstypeId.pgType.encode(unsaved.addresstypeid)}::int4, ${Name.pgType.encode(unsaved.name)}::varchar, ${TypoUUID.pgType.encode(unsaved.rowguid)}::uuid, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    returning "addresstypeid", "name", "rowguid", "modifieddate"::text
    """
    .updateReturning(AddresstypeRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insert(unsaved: AddresstypeRowUnsaved)(using c: Connection): AddresstypeRow = {
    val columns: java.util.List[Literal] = new ArrayList()
    val values: java.util.List[Fragment] = new ArrayList()
    columns.add(Fragment.lit(""""name"""")): @scala.annotation.nowarn
    values.add(interpolate"${Name.pgType.encode(unsaved.name)}::varchar"): @scala.annotation.nowarn
    unsaved.addresstypeid.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""addresstypeid"""")): @scala.annotation.nowarn;
        values.add(interpolate"${AddresstypeId.pgType.encode(value)}::int4"): @scala.annotation.nowarn;
      }
    );
    unsaved.rowguid.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""rowguid"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TypoUUID.pgType.encode(value)}::uuid"): @scala.annotation.nowarn;
      }
    );
    unsaved.modifieddate.visit(
      (),
      value => {
        columns.add(Fragment.lit(""""modifieddate"""")): @scala.annotation.nowarn;
        values.add(interpolate"${TypoLocalDateTime.pgType.encode(value)}::timestamp"): @scala.annotation.nowarn;
      }
    );
    val q: Fragment = {
      interpolate"""insert into "person"."addresstype"(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning "addresstypeid", "name", "rowguid", "modifieddate"::text
      """
    }
    q.updateReturning(AddresstypeRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  def insertStreaming(
    unsaved: java.util.Iterator[AddresstypeRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "person"."addresstype"("addresstypeid", "name", "rowguid", "modifieddate") FROM STDIN""", batchSize, unsaved, c, AddresstypeRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(
    unsaved: java.util.Iterator[AddresstypeRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = streamingInsert.insertUnchecked(s"""COPY "person"."addresstype"("name", "addresstypeid", "rowguid", "modifieddate") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""", batchSize, unsaved, c, AddresstypeRowUnsaved.pgText)

  def select: SelectBuilder[AddresstypeFields, AddresstypeRow] = SelectBuilder.of("person.addresstype", AddresstypeFields.structure, AddresstypeRow.`_rowParser`)

  def selectAll(using c: Connection): java.util.List[AddresstypeRow] = {
    interpolate"""select "addresstypeid", "name", "rowguid", "modifieddate"::text
    from "person"."addresstype"
    """.as(AddresstypeRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectById(addresstypeid: AddresstypeId)(using c: Connection): Optional[AddresstypeRow] = {
    interpolate"""select "addresstypeid", "name", "rowguid", "modifieddate"::text
    from "person"."addresstype"
    where "addresstypeid" = ${AddresstypeId.pgType.encode(addresstypeid)}""".as(AddresstypeRow.`_rowParser`.first()).runUnchecked(c)
  }

  def selectByIds(addresstypeids: Array[AddresstypeId])(using c: Connection): java.util.List[AddresstypeRow] = {
    interpolate"""select "addresstypeid", "name", "rowguid", "modifieddate"::text
    from "person"."addresstype"
    where "addresstypeid" = ANY(${AddresstypeId.pgTypeArray.encode(addresstypeids)})""".as(AddresstypeRow.`_rowParser`.all()).runUnchecked(c)
  }

  def selectByIdsTracked(addresstypeids: Array[AddresstypeId])(using c: Connection): java.util.Map[AddresstypeId, AddresstypeRow] = {
    val ret: java.util.Map[AddresstypeId, AddresstypeRow] = new HashMap()
    selectByIds(addresstypeids)(using c).forEach(row => ret.put(row.addresstypeid, row): @scala.annotation.nowarn)
    ret
  }

  def update: UpdateBuilder[AddresstypeFields, AddresstypeRow] = UpdateBuilder.of("person.addresstype", AddresstypeFields.structure, AddresstypeRow.`_rowParser`.all())

  def update(row: AddresstypeRow)(using c: Connection): java.lang.Boolean = {
    val addresstypeid: AddresstypeId = row.addresstypeid
    interpolate"""update "person"."addresstype"
    set "name" = ${Name.pgType.encode(row.name)}::varchar,
    "rowguid" = ${TypoUUID.pgType.encode(row.rowguid)}::uuid,
    "modifieddate" = ${TypoLocalDateTime.pgType.encode(row.modifieddate)}::timestamp
    where "addresstypeid" = ${AddresstypeId.pgType.encode(addresstypeid)}""".update().runUnchecked(c) > 0
  }

  def upsert(unsaved: AddresstypeRow)(using c: Connection): AddresstypeRow = {
  interpolate"""insert into "person"."addresstype"("addresstypeid", "name", "rowguid", "modifieddate")
    values (${AddresstypeId.pgType.encode(unsaved.addresstypeid)}::int4, ${Name.pgType.encode(unsaved.name)}::varchar, ${TypoUUID.pgType.encode(unsaved.rowguid)}::uuid, ${TypoLocalDateTime.pgType.encode(unsaved.modifieddate)}::timestamp)
    on conflict ("addresstypeid")
    do update set
      "name" = EXCLUDED."name",
    "rowguid" = EXCLUDED."rowguid",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "addresstypeid", "name", "rowguid", "modifieddate"::text
    """
    .updateReturning(AddresstypeRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  def upsertBatch(unsaved: java.util.Iterator[AddresstypeRow])(using c: Connection): java.util.List[AddresstypeRow] = {
    interpolate"""insert into "person"."addresstype"("addresstypeid", "name", "rowguid", "modifieddate")
    values (?::int4, ?::varchar, ?::uuid, ?::timestamp)
    on conflict ("addresstypeid")
    do update set
      "name" = EXCLUDED."name",
    "rowguid" = EXCLUDED."rowguid",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "addresstypeid", "name", "rowguid", "modifieddate"::text
    """
      .updateManyReturning(AddresstypeRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[AddresstypeRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    interpolate"""create temporary table addresstype_TEMP (like "person"."addresstype") on commit drop""".update().runUnchecked(c): @scala.annotation.nowarn
    streamingInsert.insertUnchecked(s"""copy addresstype_TEMP("addresstypeid", "name", "rowguid", "modifieddate") from stdin""", batchSize, unsaved, c, AddresstypeRow.pgText): @scala.annotation.nowarn
    interpolate"""insert into "person"."addresstype"("addresstypeid", "name", "rowguid", "modifieddate")
    select * from addresstype_TEMP
    on conflict ("addresstypeid")
    do update set
      "name" = EXCLUDED."name",
    "rowguid" = EXCLUDED."rowguid",
    "modifieddate" = EXCLUDED."modifieddate"
    ;
    drop table addresstype_TEMP;""".update().runUnchecked(c)
  }
}