/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders

import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal
import java.time.LocalDate
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import typo.kotlindsl.KotlinDbTypes
import typo.kotlindsl.nullable
import typo.runtime.DuckDbText
import typo.runtime.DuckDbTypes

/** This class corresponds to a row in table `orders` which has not been persisted yet */
data class OrdersRowUnsaved(
  @JsonProperty("order_id") val orderId: OrdersId,
  @JsonProperty("customer_id") val customerId: Int,
  @JsonProperty("total_amount") val totalAmount: BigDecimal? = null,
  /** Default: current_date */
  @JsonProperty("order_date") val orderDate: Defaulted<LocalDate> = UseDefault(),
  /** Default: 'pending' */
  val status: Defaulted<String?> = UseDefault()
) {
  fun toRow(
    orderDateDefault: () -> LocalDate,
    statusDefault: () -> String?
  ): OrdersRow = OrdersRow(orderId = orderId, customerId = customerId, orderDate = orderDate.getOrElse(orderDateDefault), totalAmount = totalAmount, status = status.getOrElse(statusDefault))

  companion object {
    val duckDbText: DuckDbText<OrdersRowUnsaved> =
      DuckDbText.instance({ row, sb -> OrdersId.duckDbType.duckDbText().unsafeEncode(row.orderId, sb)
      sb.append(DuckDbText.DELIMETER)
      KotlinDbTypes.DuckDbTypes.integer.duckDbText().unsafeEncode(row.customerId, sb)
      sb.append(DuckDbText.DELIMETER)
      DuckDbTypes.numeric.nullable().duckDbText().unsafeEncode(row.totalAmount, sb)
      sb.append(DuckDbText.DELIMETER)
      Defaulted.duckDbText(DuckDbTypes.date.duckDbText()).unsafeEncode(row.orderDate, sb)
      sb.append(DuckDbText.DELIMETER)
      Defaulted.duckDbText(DuckDbTypes.varchar.nullable().duckDbText()).unsafeEncode(row.status, sb) })
  }
}