/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.personphone

import adventureworks.person.businessentity.BusinessentityId
import adventureworks.person.phonenumbertype.PhonenumbertypeId
import adventureworks.public.Phone

/** Type for the composite primary key of table `person.personphone` */
case class PersonphoneId(
  businessentityid: BusinessentityId,
  phonenumber: Phone,
  phonenumbertypeid: PhonenumbertypeId
)